// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.20.0
// source: build_orders.sql

package dbgen

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const cancelBuildOrder = `-- name: CancelBuildOrder :one
UPDATE build_orders
SET status     = 'CANCELLED',
    updated_at = NOW()
WHERE id = $1
  AND status IN ('DRAFT', 'RELEASED')
  AND tenant_id = $2
RETURNING id, public_id, tenant_id, bo_number, bom_id, output_material_id, status, planned_qty, actual_qty, unit_of_measure, planned_start, planned_finish, actual_start, actual_finish, priority, notes, created_by, released_by, released_at, completed_by, completed_at, created_at, updated_at
`

type CancelBuildOrderParams struct {
	ID       int64 `json:"id"`
	TenantID int64 `json:"tenant_id"`
}

func (q *Queries) CancelBuildOrder(ctx context.Context, arg CancelBuildOrderParams) (BuildOrder, error) {
	row := q.db.QueryRow(ctx, cancelBuildOrder, arg.ID, arg.TenantID)
	var i BuildOrder
	err := row.Scan(
		&i.ID,
		&i.PublicID,
		&i.TenantID,
		&i.BoNumber,
		&i.BomID,
		&i.OutputMaterialID,
		&i.Status,
		&i.PlannedQty,
		&i.ActualQty,
		&i.UnitOfMeasure,
		&i.PlannedStart,
		&i.PlannedFinish,
		&i.ActualStart,
		&i.ActualFinish,
		&i.Priority,
		&i.Notes,
		&i.CreatedBy,
		&i.ReleasedBy,
		&i.ReleasedAt,
		&i.CompletedBy,
		&i.CompletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const completeBuildOrder = `-- name: CompleteBuildOrder :one
UPDATE build_orders
SET status        = 'COMPLETED',
    actual_qty    = $2,
    actual_finish = NOW(),
    completed_by  = $3,
    completed_at  = NOW(),
    updated_at    = NOW()
WHERE id = $1
  AND status = 'IN_PROGRESS'
  AND tenant_id = $4
RETURNING id, public_id, tenant_id, bo_number, bom_id, output_material_id, status, planned_qty, actual_qty, unit_of_measure, planned_start, planned_finish, actual_start, actual_finish, priority, notes, created_by, released_by, released_at, completed_by, completed_at, created_at, updated_at
`

type CompleteBuildOrderParams struct {
	ID          int64          `json:"id"`
	ActualQty   pgtype.Numeric `json:"actual_qty"`
	CompletedBy pgtype.Int8    `json:"completed_by"`
	TenantID    int64          `json:"tenant_id"`
}

func (q *Queries) CompleteBuildOrder(ctx context.Context, arg CompleteBuildOrderParams) (BuildOrder, error) {
	row := q.db.QueryRow(ctx, completeBuildOrder,
		arg.ID,
		arg.ActualQty,
		arg.CompletedBy,
		arg.TenantID,
	)
	var i BuildOrder
	err := row.Scan(
		&i.ID,
		&i.PublicID,
		&i.TenantID,
		&i.BoNumber,
		&i.BomID,
		&i.OutputMaterialID,
		&i.Status,
		&i.PlannedQty,
		&i.ActualQty,
		&i.UnitOfMeasure,
		&i.PlannedStart,
		&i.PlannedFinish,
		&i.ActualStart,
		&i.ActualFinish,
		&i.Priority,
		&i.Notes,
		&i.CreatedBy,
		&i.ReleasedBy,
		&i.ReleasedAt,
		&i.CompletedBy,
		&i.CompletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createBuildOrder = `-- name: CreateBuildOrder :one
INSERT INTO build_orders (
    tenant_id, output_material_id, bom_id,
    planned_qty, unit_of_measure,
    planned_start, planned_finish,
    priority, notes, created_by
) VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10)
RETURNING id, public_id, tenant_id, bo_number, bom_id, output_material_id, status, planned_qty, actual_qty, unit_of_measure, planned_start, planned_finish, actual_start, actual_finish, priority, notes, created_by, released_by, released_at, completed_by, completed_at, created_at, updated_at
`

type CreateBuildOrderParams struct {
	TenantID         int64          `json:"tenant_id"`
	OutputMaterialID int64          `json:"output_material_id"`
	BomID            pgtype.Int8    `json:"bom_id"`
	PlannedQty       pgtype.Numeric `json:"planned_qty"`
	UnitOfMeasure    string         `json:"unit_of_measure"`
	PlannedStart     pgtype.Date    `json:"planned_start"`
	PlannedFinish    pgtype.Date    `json:"planned_finish"`
	Priority         pgtype.Text    `json:"priority"`
	Notes            pgtype.Text    `json:"notes"`
	CreatedBy        pgtype.Int8    `json:"created_by"`
}

func (q *Queries) CreateBuildOrder(ctx context.Context, arg CreateBuildOrderParams) (BuildOrder, error) {
	row := q.db.QueryRow(ctx, createBuildOrder,
		arg.TenantID,
		arg.OutputMaterialID,
		arg.BomID,
		arg.PlannedQty,
		arg.UnitOfMeasure,
		arg.PlannedStart,
		arg.PlannedFinish,
		arg.Priority,
		arg.Notes,
		arg.CreatedBy,
	)
	var i BuildOrder
	err := row.Scan(
		&i.ID,
		&i.PublicID,
		&i.TenantID,
		&i.BoNumber,
		&i.BomID,
		&i.OutputMaterialID,
		&i.Status,
		&i.PlannedQty,
		&i.ActualQty,
		&i.UnitOfMeasure,
		&i.PlannedStart,
		&i.PlannedFinish,
		&i.ActualStart,
		&i.ActualFinish,
		&i.Priority,
		&i.Notes,
		&i.CreatedBy,
		&i.ReleasedBy,
		&i.ReleasedAt,
		&i.CompletedBy,
		&i.CompletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getBOMByOutputMaterial = `-- name: GetBOMByOutputMaterial :one
SELECT bom.id, bom.public_id, bom.tenant_id, bom.output_material_id, bom.bom_code, bom.description, bom.base_qty, bom.unit_of_measure, bom.is_active, bom.version, bom.created_at, bom.updated_at, m.code AS output_code, m.name AS output_name
FROM bill_of_materials bom
JOIN products m ON m.id = bom.output_material_id
WHERE bom.tenant_id = $1
  AND bom.output_material_id = $2
  AND bom.is_active = true
ORDER BY bom.version DESC
LIMIT 1
`

type GetBOMByOutputMaterialParams struct {
	TenantID         int64 `json:"tenant_id"`
	OutputMaterialID int64 `json:"output_material_id"`
}

type GetBOMByOutputMaterialRow struct {
	ID               int64              `json:"id"`
	PublicID         uuid.UUID          `json:"public_id"`
	TenantID         int64              `json:"tenant_id"`
	OutputMaterialID int64              `json:"output_material_id"`
	BomCode          string             `json:"bom_code"`
	Description      pgtype.Text        `json:"description"`
	BaseQty          pgtype.Numeric     `json:"base_qty"`
	UnitOfMeasure    string             `json:"unit_of_measure"`
	IsActive         pgtype.Bool        `json:"is_active"`
	Version          pgtype.Int4        `json:"version"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
	UpdatedAt        pgtype.Timestamptz `json:"updated_at"`
	OutputCode       string             `json:"output_code"`
	OutputName       string             `json:"output_name"`
}

func (q *Queries) GetBOMByOutputMaterial(ctx context.Context, arg GetBOMByOutputMaterialParams) (GetBOMByOutputMaterialRow, error) {
	row := q.db.QueryRow(ctx, getBOMByOutputMaterial, arg.TenantID, arg.OutputMaterialID)
	var i GetBOMByOutputMaterialRow
	err := row.Scan(
		&i.ID,
		&i.PublicID,
		&i.TenantID,
		&i.OutputMaterialID,
		&i.BomCode,
		&i.Description,
		&i.BaseQty,
		&i.UnitOfMeasure,
		&i.IsActive,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.OutputCode,
		&i.OutputName,
	)
	return i, err
}

const getBOMLines = `-- name: GetBOMLines :many
SELECT
    bl.id, bl.bom_id, bl.line_number, bl.component_material_id, bl.quantity, bl.unit_of_measure, bl.scrap_pct, bl.notes,
    m.code AS component_code,
    m.name AS component_name,
    m.base_unit AS component_uom
FROM bom_lines bl
JOIN products m ON m.id = bl.component_material_id
WHERE bl.bom_id = $1
ORDER BY bl.line_number
`

type GetBOMLinesRow struct {
	ID                  int64          `json:"id"`
	BomID               int64          `json:"bom_id"`
	LineNumber          int32          `json:"line_number"`
	ComponentMaterialID int64          `json:"component_material_id"`
	Quantity            pgtype.Numeric `json:"quantity"`
	UnitOfMeasure       string         `json:"unit_of_measure"`
	ScrapPct            pgtype.Numeric `json:"scrap_pct"`
	Notes               pgtype.Text    `json:"notes"`
	ComponentCode       string         `json:"component_code"`
	ComponentName       string         `json:"component_name"`
	ComponentUom        string         `json:"component_uom"`
}

func (q *Queries) GetBOMLines(ctx context.Context, bomID int64) ([]GetBOMLinesRow, error) {
	rows, err := q.db.Query(ctx, getBOMLines, bomID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetBOMLinesRow{}
	for rows.Next() {
		var i GetBOMLinesRow
		if err := rows.Scan(
			&i.ID,
			&i.BomID,
			&i.LineNumber,
			&i.ComponentMaterialID,
			&i.Quantity,
			&i.UnitOfMeasure,
			&i.ScrapPct,
			&i.Notes,
			&i.ComponentCode,
			&i.ComponentName,
			&i.ComponentUom,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getBuildOrderByPublicID = `-- name: GetBuildOrderByPublicID :one
SELECT
    bo.id, bo.public_id, bo.tenant_id, bo.bo_number, bo.bom_id, bo.output_material_id, bo.status, bo.planned_qty, bo.actual_qty, bo.unit_of_measure, bo.planned_start, bo.planned_finish, bo.actual_start, bo.actual_finish, bo.priority, bo.notes, bo.created_by, bo.released_by, bo.released_at, bo.completed_by, bo.completed_at, bo.created_at, bo.updated_at,
    m.code AS output_material_code,
    m.name AS output_material_name
FROM build_orders bo
JOIN products m ON m.id = bo.output_material_id
WHERE bo.public_id = $1 AND bo.tenant_id = $2
`

type GetBuildOrderByPublicIDParams struct {
	PublicID uuid.UUID `json:"public_id"`
	TenantID int64     `json:"tenant_id"`
}

type GetBuildOrderByPublicIDRow struct {
	ID                 int64              `json:"id"`
	PublicID           uuid.UUID          `json:"public_id"`
	TenantID           int64              `json:"tenant_id"`
	BoNumber           string             `json:"bo_number"`
	BomID              pgtype.Int8        `json:"bom_id"`
	OutputMaterialID   int64              `json:"output_material_id"`
	Status             string             `json:"status"`
	PlannedQty         pgtype.Numeric     `json:"planned_qty"`
	ActualQty          pgtype.Numeric     `json:"actual_qty"`
	UnitOfMeasure      string             `json:"unit_of_measure"`
	PlannedStart       pgtype.Date        `json:"planned_start"`
	PlannedFinish      pgtype.Date        `json:"planned_finish"`
	ActualStart        pgtype.Timestamptz `json:"actual_start"`
	ActualFinish       pgtype.Timestamptz `json:"actual_finish"`
	Priority           pgtype.Text        `json:"priority"`
	Notes              pgtype.Text        `json:"notes"`
	CreatedBy          pgtype.Int8        `json:"created_by"`
	ReleasedBy         pgtype.Int8        `json:"released_by"`
	ReleasedAt         pgtype.Timestamptz `json:"released_at"`
	CompletedBy        pgtype.Int8        `json:"completed_by"`
	CompletedAt        pgtype.Timestamptz `json:"completed_at"`
	CreatedAt          pgtype.Timestamptz `json:"created_at"`
	UpdatedAt          pgtype.Timestamptz `json:"updated_at"`
	OutputMaterialCode string             `json:"output_material_code"`
	OutputMaterialName string             `json:"output_material_name"`
}

func (q *Queries) GetBuildOrderByPublicID(ctx context.Context, arg GetBuildOrderByPublicIDParams) (GetBuildOrderByPublicIDRow, error) {
	row := q.db.QueryRow(ctx, getBuildOrderByPublicID, arg.PublicID, arg.TenantID)
	var i GetBuildOrderByPublicIDRow
	err := row.Scan(
		&i.ID,
		&i.PublicID,
		&i.TenantID,
		&i.BoNumber,
		&i.BomID,
		&i.OutputMaterialID,
		&i.Status,
		&i.PlannedQty,
		&i.ActualQty,
		&i.UnitOfMeasure,
		&i.PlannedStart,
		&i.PlannedFinish,
		&i.ActualStart,
		&i.ActualFinish,
		&i.Priority,
		&i.Notes,
		&i.CreatedBy,
		&i.ReleasedBy,
		&i.ReleasedAt,
		&i.CompletedBy,
		&i.CompletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.OutputMaterialCode,
		&i.OutputMaterialName,
	)
	return i, err
}

const getBuildOrderDashboard = `-- name: GetBuildOrderDashboard :one
SELECT
    COUNT(*)                                              AS total_orders,
    COUNT(*) FILTER (WHERE status = 'DRAFT')             AS draft,
    COUNT(*) FILTER (WHERE status = 'RELEASED')          AS released,
    COUNT(*) FILTER (WHERE status = 'IN_PROGRESS')       AS in_progress,
    COUNT(*) FILTER (WHERE status = 'COMPLETED')         AS completed,
    COUNT(*) FILTER (WHERE status = 'CANCELLED')         AS cancelled,
    COUNT(*) FILTER (WHERE priority = 'URGENT'
      AND status NOT IN ('COMPLETED','CANCELLED'))       AS urgent_open,
    COUNT(*) FILTER (WHERE planned_finish < CURRENT_DATE
      AND status NOT IN ('COMPLETED','CANCELLED'))       AS overdue
FROM build_orders
WHERE tenant_id = $1
`

type GetBuildOrderDashboardRow struct {
	TotalOrders int64 `json:"total_orders"`
	Draft       int64 `json:"draft"`
	Released    int64 `json:"released"`
	InProgress  int64 `json:"in_progress"`
	Completed   int64 `json:"completed"`
	Cancelled   int64 `json:"cancelled"`
	UrgentOpen  int64 `json:"urgent_open"`
	Overdue     int64 `json:"overdue"`
}

func (q *Queries) GetBuildOrderDashboard(ctx context.Context, tenantID int64) (GetBuildOrderDashboardRow, error) {
	row := q.db.QueryRow(ctx, getBuildOrderDashboard, tenantID)
	var i GetBuildOrderDashboardRow
	err := row.Scan(
		&i.TotalOrders,
		&i.Draft,
		&i.Released,
		&i.InProgress,
		&i.Completed,
		&i.Cancelled,
		&i.UrgentOpen,
		&i.Overdue,
	)
	return i, err
}

const getBuildOrderIssues = `-- name: GetBuildOrderIssues :many
SELECT
    boi.id, boi.public_id, boi.build_order_id, boi.material_id, boi.issued_qty, boi.unit_of_measure, boi.issued_at, boi.issued_by, boi.notes,
    m.code AS material_code,
    m.name AS material_name
FROM build_order_issues boi
JOIN products m ON m.id = boi.material_id
WHERE boi.build_order_id = $1
ORDER BY boi.issued_at DESC
`

type GetBuildOrderIssuesRow struct {
	ID            int64              `json:"id"`
	PublicID      uuid.UUID          `json:"public_id"`
	BuildOrderID  int64              `json:"build_order_id"`
	MaterialID    int64              `json:"material_id"`
	IssuedQty     pgtype.Numeric     `json:"issued_qty"`
	UnitOfMeasure string             `json:"unit_of_measure"`
	IssuedAt      pgtype.Timestamptz `json:"issued_at"`
	IssuedBy      pgtype.Int8        `json:"issued_by"`
	Notes         pgtype.Text        `json:"notes"`
	MaterialCode  string             `json:"material_code"`
	MaterialName  string             `json:"material_name"`
}

func (q *Queries) GetBuildOrderIssues(ctx context.Context, buildOrderID int64) ([]GetBuildOrderIssuesRow, error) {
	rows, err := q.db.Query(ctx, getBuildOrderIssues, buildOrderID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetBuildOrderIssuesRow{}
	for rows.Next() {
		var i GetBuildOrderIssuesRow
		if err := rows.Scan(
			&i.ID,
			&i.PublicID,
			&i.BuildOrderID,
			&i.MaterialID,
			&i.IssuedQty,
			&i.UnitOfMeasure,
			&i.IssuedAt,
			&i.IssuedBy,
			&i.Notes,
			&i.MaterialCode,
			&i.MaterialName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const issueComponentToBuildOrder = `-- name: IssueComponentToBuildOrder :one
INSERT INTO build_order_issues (
    build_order_id, material_id,
    issued_qty, unit_of_measure,
    issued_by, notes
) VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, public_id, build_order_id, material_id, issued_qty, unit_of_measure, issued_at, issued_by, notes
`

type IssueComponentToBuildOrderParams struct {
	BuildOrderID  int64          `json:"build_order_id"`
	MaterialID    int64          `json:"material_id"`
	IssuedQty     pgtype.Numeric `json:"issued_qty"`
	UnitOfMeasure string         `json:"unit_of_measure"`
	IssuedBy      pgtype.Int8    `json:"issued_by"`
	Notes         pgtype.Text    `json:"notes"`
}

func (q *Queries) IssueComponentToBuildOrder(ctx context.Context, arg IssueComponentToBuildOrderParams) (BuildOrderIssue, error) {
	row := q.db.QueryRow(ctx, issueComponentToBuildOrder,
		arg.BuildOrderID,
		arg.MaterialID,
		arg.IssuedQty,
		arg.UnitOfMeasure,
		arg.IssuedBy,
		arg.Notes,
	)
	var i BuildOrderIssue
	err := row.Scan(
		&i.ID,
		&i.PublicID,
		&i.BuildOrderID,
		&i.MaterialID,
		&i.IssuedQty,
		&i.UnitOfMeasure,
		&i.IssuedAt,
		&i.IssuedBy,
		&i.Notes,
	)
	return i, err
}

const listBuildOrders = `-- name: ListBuildOrders :many
SELECT
    bo.id, bo.public_id, bo.tenant_id, bo.bo_number, bo.bom_id, bo.output_material_id, bo.status, bo.planned_qty, bo.actual_qty, bo.unit_of_measure, bo.planned_start, bo.planned_finish, bo.actual_start, bo.actual_finish, bo.priority, bo.notes, bo.created_by, bo.released_by, bo.released_at, bo.completed_by, bo.completed_at, bo.created_at, bo.updated_at,
    m.code AS output_material_code,
    m.name AS output_material_name
FROM build_orders bo
JOIN products m ON m.id = bo.output_material_id
WHERE bo.tenant_id = $1
ORDER BY
    CASE bo.priority
        WHEN 'URGENT' THEN 1
        WHEN 'HIGH'   THEN 2
        WHEN 'NORMAL' THEN 3
        WHEN 'LOW'    THEN 4
    END,
    bo.created_at DESC
LIMIT $2 OFFSET $3
`

type ListBuildOrdersParams struct {
	TenantID int64 `json:"tenant_id"`
	Limit    int32 `json:"limit"`
	Offset   int32 `json:"offset"`
}

type ListBuildOrdersRow struct {
	ID                 int64              `json:"id"`
	PublicID           uuid.UUID          `json:"public_id"`
	TenantID           int64              `json:"tenant_id"`
	BoNumber           string             `json:"bo_number"`
	BomID              pgtype.Int8        `json:"bom_id"`
	OutputMaterialID   int64              `json:"output_material_id"`
	Status             string             `json:"status"`
	PlannedQty         pgtype.Numeric     `json:"planned_qty"`
	ActualQty          pgtype.Numeric     `json:"actual_qty"`
	UnitOfMeasure      string             `json:"unit_of_measure"`
	PlannedStart       pgtype.Date        `json:"planned_start"`
	PlannedFinish      pgtype.Date        `json:"planned_finish"`
	ActualStart        pgtype.Timestamptz `json:"actual_start"`
	ActualFinish       pgtype.Timestamptz `json:"actual_finish"`
	Priority           pgtype.Text        `json:"priority"`
	Notes              pgtype.Text        `json:"notes"`
	CreatedBy          pgtype.Int8        `json:"created_by"`
	ReleasedBy         pgtype.Int8        `json:"released_by"`
	ReleasedAt         pgtype.Timestamptz `json:"released_at"`
	CompletedBy        pgtype.Int8        `json:"completed_by"`
	CompletedAt        pgtype.Timestamptz `json:"completed_at"`
	CreatedAt          pgtype.Timestamptz `json:"created_at"`
	UpdatedAt          pgtype.Timestamptz `json:"updated_at"`
	OutputMaterialCode string             `json:"output_material_code"`
	OutputMaterialName string             `json:"output_material_name"`
}

func (q *Queries) ListBuildOrders(ctx context.Context, arg ListBuildOrdersParams) ([]ListBuildOrdersRow, error) {
	rows, err := q.db.Query(ctx, listBuildOrders, arg.TenantID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListBuildOrdersRow{}
	for rows.Next() {
		var i ListBuildOrdersRow
		if err := rows.Scan(
			&i.ID,
			&i.PublicID,
			&i.TenantID,
			&i.BoNumber,
			&i.BomID,
			&i.OutputMaterialID,
			&i.Status,
			&i.PlannedQty,
			&i.ActualQty,
			&i.UnitOfMeasure,
			&i.PlannedStart,
			&i.PlannedFinish,
			&i.ActualStart,
			&i.ActualFinish,
			&i.Priority,
			&i.Notes,
			&i.CreatedBy,
			&i.ReleasedBy,
			&i.ReleasedAt,
			&i.CompletedBy,
			&i.CompletedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.OutputMaterialCode,
			&i.OutputMaterialName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const releaseBuildOrder = `-- name: ReleaseBuildOrder :one
UPDATE build_orders
SET status      = 'RELEASED',
    released_by = $2,
    released_at = NOW(),
    updated_at  = NOW()
WHERE id = $1
  AND status = 'DRAFT'
  AND tenant_id = $3
RETURNING id, public_id, tenant_id, bo_number, bom_id, output_material_id, status, planned_qty, actual_qty, unit_of_measure, planned_start, planned_finish, actual_start, actual_finish, priority, notes, created_by, released_by, released_at, completed_by, completed_at, created_at, updated_at
`

type ReleaseBuildOrderParams struct {
	ID         int64       `json:"id"`
	ReleasedBy pgtype.Int8 `json:"released_by"`
	TenantID   int64       `json:"tenant_id"`
}

func (q *Queries) ReleaseBuildOrder(ctx context.Context, arg ReleaseBuildOrderParams) (BuildOrder, error) {
	row := q.db.QueryRow(ctx, releaseBuildOrder, arg.ID, arg.ReleasedBy, arg.TenantID)
	var i BuildOrder
	err := row.Scan(
		&i.ID,
		&i.PublicID,
		&i.TenantID,
		&i.BoNumber,
		&i.BomID,
		&i.OutputMaterialID,
		&i.Status,
		&i.PlannedQty,
		&i.ActualQty,
		&i.UnitOfMeasure,
		&i.PlannedStart,
		&i.PlannedFinish,
		&i.ActualStart,
		&i.ActualFinish,
		&i.Priority,
		&i.Notes,
		&i.CreatedBy,
		&i.ReleasedBy,
		&i.ReleasedAt,
		&i.CompletedBy,
		&i.CompletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const startBuildOrder = `-- name: StartBuildOrder :one
UPDATE build_orders
SET status       = 'IN_PROGRESS',
    actual_start = NOW(),
    updated_at   = NOW()
WHERE id = $1
  AND status = 'RELEASED'
  AND tenant_id = $2
RETURNING id, public_id, tenant_id, bo_number, bom_id, output_material_id, status, planned_qty, actual_qty, unit_of_measure, planned_start, planned_finish, actual_start, actual_finish, priority, notes, created_by, released_by, released_at, completed_by, completed_at, created_at, updated_at
`

type StartBuildOrderParams struct {
	ID       int64 `json:"id"`
	TenantID int64 `json:"tenant_id"`
}

func (q *Queries) StartBuildOrder(ctx context.Context, arg StartBuildOrderParams) (BuildOrder, error) {
	row := q.db.QueryRow(ctx, startBuildOrder, arg.ID, arg.TenantID)
	var i BuildOrder
	err := row.Scan(
		&i.ID,
		&i.PublicID,
		&i.TenantID,
		&i.BoNumber,
		&i.BomID,
		&i.OutputMaterialID,
		&i.Status,
		&i.PlannedQty,
		&i.ActualQty,
		&i.UnitOfMeasure,
		&i.PlannedStart,
		&i.PlannedFinish,
		&i.ActualStart,
		&i.ActualFinish,
		&i.Priority,
		&i.Notes,
		&i.CreatedBy,
		&i.ReleasedBy,
		&i.ReleasedAt,
		&i.CompletedBy,
		&i.CompletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
