// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.20.0
// source: dispatch.sql

package dbgen

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createDispatchRule = `-- name: CreateDispatchRule :one
INSERT INTO dispatch_rules (
    tenant_id, rule_name, trigger_event, channel,
    recipient_type, recipient_value,
    subject_template, body_template
) VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
RETURNING id, public_id, tenant_id, rule_name, trigger_event, channel, recipient_type, recipient_value, subject_template, body_template, is_active, created_at, updated_at
`

type CreateDispatchRuleParams struct {
	TenantID        int64       `json:"tenant_id"`
	RuleName        string      `json:"rule_name"`
	TriggerEvent    string      `json:"trigger_event"`
	Channel         string      `json:"channel"`
	RecipientType   string      `json:"recipient_type"`
	RecipientValue  string      `json:"recipient_value"`
	SubjectTemplate pgtype.Text `json:"subject_template"`
	BodyTemplate    pgtype.Text `json:"body_template"`
}

func (q *Queries) CreateDispatchRule(ctx context.Context, arg CreateDispatchRuleParams) (DispatchRule, error) {
	row := q.db.QueryRow(ctx, createDispatchRule,
		arg.TenantID,
		arg.RuleName,
		arg.TriggerEvent,
		arg.Channel,
		arg.RecipientType,
		arg.RecipientValue,
		arg.SubjectTemplate,
		arg.BodyTemplate,
	)
	var i DispatchRule
	err := row.Scan(
		&i.ID,
		&i.PublicID,
		&i.TenantID,
		&i.RuleName,
		&i.TriggerEvent,
		&i.Channel,
		&i.RecipientType,
		&i.RecipientValue,
		&i.SubjectTemplate,
		&i.BodyTemplate,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getDispatchRulesByEvent = `-- name: GetDispatchRulesByEvent :many
SELECT id, public_id, tenant_id, rule_name, trigger_event, channel, recipient_type, recipient_value, subject_template, body_template, is_active, created_at, updated_at FROM dispatch_rules
WHERE tenant_id = $1
  AND trigger_event = $2
  AND is_active = true
`

type GetDispatchRulesByEventParams struct {
	TenantID     int64  `json:"tenant_id"`
	TriggerEvent string `json:"trigger_event"`
}

func (q *Queries) GetDispatchRulesByEvent(ctx context.Context, arg GetDispatchRulesByEventParams) ([]DispatchRule, error) {
	rows, err := q.db.Query(ctx, getDispatchRulesByEvent, arg.TenantID, arg.TriggerEvent)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []DispatchRule{}
	for rows.Next() {
		var i DispatchRule
		if err := rows.Scan(
			&i.ID,
			&i.PublicID,
			&i.TenantID,
			&i.RuleName,
			&i.TriggerEvent,
			&i.Channel,
			&i.RecipientType,
			&i.RecipientValue,
			&i.SubjectTemplate,
			&i.BodyTemplate,
			&i.IsActive,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getDispatchSummary = `-- name: GetDispatchSummary :one
SELECT
    COUNT(*)                                           AS total_dispatched,
    COUNT(*) FILTER (WHERE status = 'SENT')            AS sent,
    COUNT(*) FILTER (WHERE status = 'FAILED')          AS failed,
    COUNT(*) FILTER (WHERE status = 'PENDING')         AS pending,
    COUNT(*) FILTER (WHERE channel = 'EMAIL'
                      AND status = 'SENT')             AS emails_sent,
    COUNT(*) FILTER (WHERE channel = 'WEBHOOK'
                      AND status = 'SENT')             AS webhooks_sent,
    COUNT(*) FILTER (WHERE created_at >= NOW() - INTERVAL '24 hours') AS last_24h
FROM dispatch_logs
WHERE tenant_id = $1
`

type GetDispatchSummaryRow struct {
	TotalDispatched int64 `json:"total_dispatched"`
	Sent            int64 `json:"sent"`
	Failed          int64 `json:"failed"`
	Pending         int64 `json:"pending"`
	EmailsSent      int64 `json:"emails_sent"`
	WebhooksSent    int64 `json:"webhooks_sent"`
	Last24h         int64 `json:"last_24h"`
}

func (q *Queries) GetDispatchSummary(ctx context.Context, tenantID int64) (GetDispatchSummaryRow, error) {
	row := q.db.QueryRow(ctx, getDispatchSummary, tenantID)
	var i GetDispatchSummaryRow
	err := row.Scan(
		&i.TotalDispatched,
		&i.Sent,
		&i.Failed,
		&i.Pending,
		&i.EmailsSent,
		&i.WebhooksSent,
		&i.Last24h,
	)
	return i, err
}

const listDispatchLogs = `-- name: ListDispatchLogs :many
SELECT
    dl.id, dl.public_id, dl.tenant_id, dl.dispatch_rule_id, dl.trigger_event, dl.reference_type, dl.reference_id, dl.reference_code, dl.channel, dl.recipient, dl.subject, dl.status, dl.error_message, dl.sent_at, dl.created_at,
    dr.rule_name
FROM dispatch_logs dl
LEFT JOIN dispatch_rules dr ON dr.id = dl.dispatch_rule_id
WHERE dl.tenant_id = $1
ORDER BY dl.created_at DESC
LIMIT $2 OFFSET $3
`

type ListDispatchLogsParams struct {
	TenantID int64 `json:"tenant_id"`
	Limit    int32 `json:"limit"`
	Offset   int32 `json:"offset"`
}

type ListDispatchLogsRow struct {
	ID             int64              `json:"id"`
	PublicID       uuid.UUID          `json:"public_id"`
	TenantID       int64              `json:"tenant_id"`
	DispatchRuleID pgtype.Int8        `json:"dispatch_rule_id"`
	TriggerEvent   string             `json:"trigger_event"`
	ReferenceType  pgtype.Text        `json:"reference_type"`
	ReferenceID    pgtype.Int8        `json:"reference_id"`
	ReferenceCode  pgtype.Text        `json:"reference_code"`
	Channel        string             `json:"channel"`
	Recipient      string             `json:"recipient"`
	Subject        pgtype.Text        `json:"subject"`
	Status         string             `json:"status"`
	ErrorMessage   pgtype.Text        `json:"error_message"`
	SentAt         pgtype.Timestamptz `json:"sent_at"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	RuleName       pgtype.Text        `json:"rule_name"`
}

func (q *Queries) ListDispatchLogs(ctx context.Context, arg ListDispatchLogsParams) ([]ListDispatchLogsRow, error) {
	rows, err := q.db.Query(ctx, listDispatchLogs, arg.TenantID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListDispatchLogsRow{}
	for rows.Next() {
		var i ListDispatchLogsRow
		if err := rows.Scan(
			&i.ID,
			&i.PublicID,
			&i.TenantID,
			&i.DispatchRuleID,
			&i.TriggerEvent,
			&i.ReferenceType,
			&i.ReferenceID,
			&i.ReferenceCode,
			&i.Channel,
			&i.Recipient,
			&i.Subject,
			&i.Status,
			&i.ErrorMessage,
			&i.SentAt,
			&i.CreatedAt,
			&i.RuleName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDispatchRules = `-- name: ListDispatchRules :many
SELECT id, public_id, tenant_id, rule_name, trigger_event, channel, recipient_type, recipient_value, subject_template, body_template, is_active, created_at, updated_at FROM dispatch_rules
WHERE tenant_id = $1
ORDER BY trigger_event, channel
`

func (q *Queries) ListDispatchRules(ctx context.Context, tenantID int64) ([]DispatchRule, error) {
	rows, err := q.db.Query(ctx, listDispatchRules, tenantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []DispatchRule{}
	for rows.Next() {
		var i DispatchRule
		if err := rows.Scan(
			&i.ID,
			&i.PublicID,
			&i.TenantID,
			&i.RuleName,
			&i.TriggerEvent,
			&i.Channel,
			&i.RecipientType,
			&i.RecipientValue,
			&i.SubjectTemplate,
			&i.BodyTemplate,
			&i.IsActive,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const logDispatch = `-- name: LogDispatch :one
INSERT INTO dispatch_logs (
    tenant_id, dispatch_rule_id,
    trigger_event, reference_type, reference_id, reference_code,
    channel, recipient, subject, status, error_message, sent_at
) VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12)
RETURNING id, public_id, tenant_id, dispatch_rule_id, trigger_event, reference_type, reference_id, reference_code, channel, recipient, subject, status, error_message, sent_at, created_at
`

type LogDispatchParams struct {
	TenantID       int64              `json:"tenant_id"`
	DispatchRuleID pgtype.Int8        `json:"dispatch_rule_id"`
	TriggerEvent   string             `json:"trigger_event"`
	ReferenceType  pgtype.Text        `json:"reference_type"`
	ReferenceID    pgtype.Int8        `json:"reference_id"`
	ReferenceCode  pgtype.Text        `json:"reference_code"`
	Channel        string             `json:"channel"`
	Recipient      string             `json:"recipient"`
	Subject        pgtype.Text        `json:"subject"`
	Status         string             `json:"status"`
	ErrorMessage   pgtype.Text        `json:"error_message"`
	SentAt         pgtype.Timestamptz `json:"sent_at"`
}

func (q *Queries) LogDispatch(ctx context.Context, arg LogDispatchParams) (DispatchLog, error) {
	row := q.db.QueryRow(ctx, logDispatch,
		arg.TenantID,
		arg.DispatchRuleID,
		arg.TriggerEvent,
		arg.ReferenceType,
		arg.ReferenceID,
		arg.ReferenceCode,
		arg.Channel,
		arg.Recipient,
		arg.Subject,
		arg.Status,
		arg.ErrorMessage,
		arg.SentAt,
	)
	var i DispatchLog
	err := row.Scan(
		&i.ID,
		&i.PublicID,
		&i.TenantID,
		&i.DispatchRuleID,
		&i.TriggerEvent,
		&i.ReferenceType,
		&i.ReferenceID,
		&i.ReferenceCode,
		&i.Channel,
		&i.Recipient,
		&i.Subject,
		&i.Status,
		&i.ErrorMessage,
		&i.SentAt,
		&i.CreatedAt,
	)
	return i, err
}

const updateDispatchRule = `-- name: UpdateDispatchRule :one
UPDATE dispatch_rules
SET is_active      = $2,
    recipient_value = COALESCE($3, recipient_value),
    updated_at     = NOW()
WHERE id = $1 AND tenant_id = $4
RETURNING id, public_id, tenant_id, rule_name, trigger_event, channel, recipient_type, recipient_value, subject_template, body_template, is_active, created_at, updated_at
`

type UpdateDispatchRuleParams struct {
	ID             int64       `json:"id"`
	IsActive       pgtype.Bool `json:"is_active"`
	RecipientValue string      `json:"recipient_value"`
	TenantID       int64       `json:"tenant_id"`
}

func (q *Queries) UpdateDispatchRule(ctx context.Context, arg UpdateDispatchRuleParams) (DispatchRule, error) {
	row := q.db.QueryRow(ctx, updateDispatchRule,
		arg.ID,
		arg.IsActive,
		arg.RecipientValue,
		arg.TenantID,
	)
	var i DispatchRule
	err := row.Scan(
		&i.ID,
		&i.PublicID,
		&i.TenantID,
		&i.RuleName,
		&i.TriggerEvent,
		&i.Channel,
		&i.RecipientType,
		&i.RecipientValue,
		&i.SubjectTemplate,
		&i.BodyTemplate,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
