// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.20.0
// source: gr_stock.sql

package dbgen

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createGRHold = `-- name: CreateGRHold :one
INSERT INTO gr_overdelivery_holds (
    tenant_id, gr_id, po_line_id, po_quantity, received_quantity, requested_by, status
) VALUES (
    $1::BIGINT, $2::BIGINT, $3::BIGINT, $4, $5, $6::BIGINT, 'PENDING'
) RETURNING id, tenant_id, public_id, gr_id, po_line_id, po_quantity, received_quantity, excess_quantity, excess_pct, status, requested_by, approved_by, resolved_at, notes, created_at
`

type CreateGRHoldParams struct {
	TenantID         int64          `json:"tenant_id"`
	GrID             int64          `json:"gr_id"`
	PoLineID         int64          `json:"po_line_id"`
	PoQuantity       pgtype.Numeric `json:"po_quantity"`
	ReceivedQuantity pgtype.Numeric `json:"received_quantity"`
	RequestedBy      int64          `json:"requested_by"`
}

func (q *Queries) CreateGRHold(ctx context.Context, arg CreateGRHoldParams) (GrOverdeliveryHold, error) {
	row := q.db.QueryRow(ctx, createGRHold,
		arg.TenantID,
		arg.GrID,
		arg.PoLineID,
		arg.PoQuantity,
		arg.ReceivedQuantity,
		arg.RequestedBy,
	)
	var i GrOverdeliveryHold
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.PublicID,
		&i.GrID,
		&i.PoLineID,
		&i.PoQuantity,
		&i.ReceivedQuantity,
		&i.ExcessQuantity,
		&i.ExcessPct,
		&i.Status,
		&i.RequestedBy,
		&i.ApprovedBy,
		&i.ResolvedAt,
		&i.Notes,
		&i.CreatedAt,
	)
	return i, err
}

const getPOLineForGR = `-- name: GetPOLineForGR :one
SELECT 
    pol.id, pol.quantity, pol.qty_received, pol.overdelivery_tolerance_pct, 
    pol.overdelivery_requires_approval, pol.tenant_id
FROM purchase_order_lines pol
WHERE pol.id = $1::BIGINT AND pol.tenant_id = $2::BIGINT
`

type GetPOLineForGRParams struct {
	ID       int64 `json:"id"`
	TenantID int64 `json:"tenant_id"`
}

type GetPOLineForGRRow struct {
	ID                           int64          `json:"id"`
	Quantity                     pgtype.Numeric `json:"quantity"`
	QtyReceived                  pgtype.Numeric `json:"qty_received"`
	OverdeliveryTolerancePct     pgtype.Numeric `json:"overdelivery_tolerance_pct"`
	OverdeliveryRequiresApproval bool           `json:"overdelivery_requires_approval"`
	TenantID                     int64          `json:"tenant_id"`
}

func (q *Queries) GetPOLineForGR(ctx context.Context, arg GetPOLineForGRParams) (GetPOLineForGRRow, error) {
	row := q.db.QueryRow(ctx, getPOLineForGR, arg.ID, arg.TenantID)
	var i GetPOLineForGRRow
	err := row.Scan(
		&i.ID,
		&i.Quantity,
		&i.QtyReceived,
		&i.OverdeliveryTolerancePct,
		&i.OverdeliveryRequiresApproval,
		&i.TenantID,
	)
	return i, err
}

const getPendingOverdeliveryHolds = `-- name: GetPendingOverdeliveryHolds :many
SELECT id, tenant_id, public_id, gr_id, po_line_id, po_quantity, received_quantity, excess_quantity, excess_pct, status, requested_by, approved_by, resolved_at, notes, created_at FROM gr_overdelivery_holds
WHERE tenant_id = $1::BIGINT AND status = 'PENDING'
ORDER BY created_at DESC
`

func (q *Queries) GetPendingOverdeliveryHolds(ctx context.Context, tenantID int64) ([]GrOverdeliveryHold, error) {
	rows, err := q.db.Query(ctx, getPendingOverdeliveryHolds, tenantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GrOverdeliveryHold{}
	for rows.Next() {
		var i GrOverdeliveryHold
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.PublicID,
			&i.GrID,
			&i.PoLineID,
			&i.PoQuantity,
			&i.ReceivedQuantity,
			&i.ExcessQuantity,
			&i.ExcessPct,
			&i.Status,
			&i.RequestedBy,
			&i.ApprovedBy,
			&i.ResolvedAt,
			&i.Notes,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getStockByMaterialAndTenant = `-- name: GetStockByMaterialAndTenant :many
SELECT
  z.code AS zone_code, z.zone_type,
  ie.stock_type,
  SUM(ie.quantity) AS quantity
FROM inventory_events ie
JOIN zones z ON z.id = ie.zone_id
WHERE ie.tenant_id = $1::BIGINT AND ie.product_id = $2::BIGINT
GROUP BY z.code, z.zone_type, ie.stock_type
HAVING SUM(ie.quantity) > 0
`

type GetStockByMaterialAndTenantParams struct {
	TenantID  int64 `json:"tenant_id"`
	ProductID int64 `json:"product_id"`
}

type GetStockByMaterialAndTenantRow struct {
	ZoneCode  string `json:"zone_code"`
	ZoneType  string `json:"zone_type"`
	StockType string `json:"stock_type"`
	Quantity  int64  `json:"quantity"`
}

func (q *Queries) GetStockByMaterialAndTenant(ctx context.Context, arg GetStockByMaterialAndTenantParams) ([]GetStockByMaterialAndTenantRow, error) {
	rows, err := q.db.Query(ctx, getStockByMaterialAndTenant, arg.TenantID, arg.ProductID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetStockByMaterialAndTenantRow{}
	for rows.Next() {
		var i GetStockByMaterialAndTenantRow
		if err := rows.Scan(
			&i.ZoneCode,
			&i.ZoneType,
			&i.StockType,
			&i.Quantity,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const resolveOverdeliveryHold = `-- name: ResolveOverdeliveryHold :one
UPDATE gr_overdelivery_holds
SET status = $1, approved_by = $2::BIGINT, resolved_at = NOW(), notes = $3
WHERE public_id = $4 AND tenant_id = $5::BIGINT
RETURNING id, tenant_id, public_id, gr_id, po_line_id, po_quantity, received_quantity, excess_quantity, excess_pct, status, requested_by, approved_by, resolved_at, notes, created_at
`

type ResolveOverdeliveryHoldParams struct {
	Status     string      `json:"status"`
	ApprovedBy int64       `json:"approved_by"`
	Notes      pgtype.Text `json:"notes"`
	PublicID   uuid.UUID   `json:"public_id"`
	TenantID   int64       `json:"tenant_id"`
}

func (q *Queries) ResolveOverdeliveryHold(ctx context.Context, arg ResolveOverdeliveryHoldParams) (GrOverdeliveryHold, error) {
	row := q.db.QueryRow(ctx, resolveOverdeliveryHold,
		arg.Status,
		arg.ApprovedBy,
		arg.Notes,
		arg.PublicID,
		arg.TenantID,
	)
	var i GrOverdeliveryHold
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.PublicID,
		&i.GrID,
		&i.PoLineID,
		&i.PoQuantity,
		&i.ReceivedQuantity,
		&i.ExcessQuantity,
		&i.ExcessPct,
		&i.Status,
		&i.RequestedBy,
		&i.ApprovedBy,
		&i.ResolvedAt,
		&i.Notes,
		&i.CreatedAt,
	)
	return i, err
}

const updateGRStatus = `-- name: UpdateGRStatus :one
UPDATE gr_documents SET status = $1 WHERE id = $2::BIGINT AND tenant_id = $3::BIGINT
RETURNING id, tenant_id, public_id, organisation_id, site_id, zone_id, gr_number, status, supplier_ref, notes, posted_at, created_by, created_at, updated_at, document_date, posting_date, movement_type, fiscal_year, supplier_id, delivery_note_number, bill_of_lading, reversal_of_gr_id, posted_by, delivering_zone_id
`

type UpdateGRStatusParams struct {
	Status   string `json:"status"`
	ID       int64  `json:"id"`
	TenantID int64  `json:"tenant_id"`
}

func (q *Queries) UpdateGRStatus(ctx context.Context, arg UpdateGRStatusParams) (GrDocument, error) {
	row := q.db.QueryRow(ctx, updateGRStatus, arg.Status, arg.ID, arg.TenantID)
	var i GrDocument
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.PublicID,
		&i.OrganisationID,
		&i.SiteID,
		&i.ZoneID,
		&i.GrNumber,
		&i.Status,
		&i.SupplierRef,
		&i.Notes,
		&i.PostedAt,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DocumentDate,
		&i.PostingDate,
		&i.MovementType,
		&i.FiscalYear,
		&i.SupplierID,
		&i.DeliveryNoteNumber,
		&i.BillOfLading,
		&i.ReversalOfGrID,
		&i.PostedBy,
		&i.DeliveringZoneID,
	)
	return i, err
}
