// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.20.0

package dbgen

import (
	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type AuditLog struct {
	ID             int64              `json:"id"`
	TenantID       pgtype.Int8        `json:"tenant_id"`
	ActorID        pgtype.Int8        `json:"actor_id"`
	Action         string             `json:"action"`
	EntityType     string             `json:"entity_type"`
	EntityPublicID pgtype.UUID        `json:"entity_public_id"`
	PayloadBefore  []byte             `json:"payload_before"`
	PayloadAfter   []byte             `json:"payload_after"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
}

type Barcode struct {
	ID         int64              `json:"id"`
	TenantID   pgtype.Int8        `json:"tenant_id"`
	Code       string             `json:"code"`
	EntityType string             `json:"entity_type"`
	EntityID   int64              `json:"entity_id"`
	IsActive   pgtype.Bool        `json:"is_active"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
}

type Batch struct {
	ID          int64              `json:"id"`
	TenantID    pgtype.Int8        `json:"tenant_id"`
	ProductID   pgtype.Int8        `json:"product_id"`
	BatchNumber pgtype.Text        `json:"batch_number"`
	ExpiryDate  pgtype.Date        `json:"expiry_date"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
}

type BlockedOperation struct {
	ID        int64              `json:"id"`
	TenantID  pgtype.Int8        `json:"tenant_id"`
	Reason    string             `json:"reason"`
	Context   []byte             `json:"context"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type BomLine struct {
	ID                int64          `json:"id"`
	ProductionOrderID pgtype.Int8    `json:"production_order_id"`
	ProductID         pgtype.Int8    `json:"product_id"`
	RequiredQty       pgtype.Numeric `json:"required_qty"`
	ConsumedQty       pgtype.Numeric `json:"consumed_qty"`
	Unit              pgtype.Text    `json:"unit"`
}

type ExecutionTrace struct {
	ID        int64              `json:"id"`
	TraceID   uuid.UUID          `json:"trace_id"`
	TenantID  pgtype.Int8        `json:"tenant_id"`
	Operation string             `json:"operation"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type ExecutionTraceStep struct {
	ID        int64              `json:"id"`
	TraceID   uuid.UUID          `json:"trace_id"`
	AgentName string             `json:"agent_name"`
	Action    string             `json:"action"`
	Status    string             `json:"status"`
	Payload   []byte             `json:"payload"`
	StepOrder int32              `json:"step_order"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type GrDocument struct {
	ID                 int64              `json:"id"`
	TenantID           int64              `json:"tenant_id"`
	PublicID           pgtype.UUID        `json:"public_id"`
	OrganisationID     int64              `json:"organisation_id"`
	SiteID             int64              `json:"site_id"`
	ZoneID             int64              `json:"zone_id"`
	GrNumber           string             `json:"gr_number"`
	Status             string             `json:"status"`
	SupplierRef        pgtype.Text        `json:"supplier_ref"`
	Notes              pgtype.Text        `json:"notes"`
	PostedAt           pgtype.Timestamptz `json:"posted_at"`
	CreatedBy          pgtype.Int8        `json:"created_by"`
	CreatedAt          pgtype.Timestamptz `json:"created_at"`
	UpdatedAt          pgtype.Timestamptz `json:"updated_at"`
	DocumentDate       pgtype.Date        `json:"document_date"`
	PostingDate        pgtype.Date        `json:"posting_date"`
	MovementType       string             `json:"movement_type"`
	FiscalYear         pgtype.Int4        `json:"fiscal_year"`
	SupplierID         pgtype.Int8        `json:"supplier_id"`
	DeliveryNoteNumber pgtype.Text        `json:"delivery_note_number"`
	BillOfLading       pgtype.Text        `json:"bill_of_lading"`
	ReversalOfGrID     pgtype.Int8        `json:"reversal_of_gr_id"`
	PostedBy           pgtype.Int8        `json:"posted_by"`
}

type GrLine struct {
	ID           int64              `json:"id"`
	TenantID     int64              `json:"tenant_id"`
	PublicID     pgtype.UUID        `json:"public_id"`
	GrDocumentID int64              `json:"gr_document_id"`
	ProductID    int64              `json:"product_id"`
	Quantity     pgtype.Numeric     `json:"quantity"`
	Unit         string             `json:"unit"`
	BatchRef     pgtype.Text        `json:"batch_ref"`
	HuID         pgtype.Int8        `json:"hu_id"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	LineNumber   int32              `json:"line_number"`
	ShortText    pgtype.Text        `json:"short_text"`
	ExpiryDate   pgtype.Date        `json:"expiry_date"`
	StockType    string             `json:"stock_type"`
	MovementType pgtype.Text        `json:"movement_type"`
	UnitPrice    pgtype.Numeric     `json:"unit_price"`
	LineValue    pgtype.Numeric     `json:"line_value"`
	Currency     pgtype.Text        `json:"currency"`
	LineNotes    pgtype.Text        `json:"line_notes"`
}

type HandlingUnit struct {
	ID           int64              `json:"id"`
	PublicID     pgtype.UUID        `json:"public_id"`
	TenantID     pgtype.Int8        `json:"tenant_id"`
	ParentHuID   pgtype.Int8        `json:"parent_hu_id"`
	ProductID    pgtype.Int8        `json:"product_id"`
	BatchID      pgtype.Int8        `json:"batch_id"`
	LocationID   pgtype.Int8        `json:"location_id"`
	Code         pgtype.Text        `json:"code"`
	Quantity     pgtype.Numeric     `json:"quantity"`
	Unit         string             `json:"unit"`
	Status       string             `json:"status"`
	LabelVersion int32              `json:"label_version"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
	SiteID       pgtype.Int8        `json:"site_id"`
	ZoneID       pgtype.Int8        `json:"zone_id"`
	ConsumedAt   pgtype.Timestamptz `json:"consumed_at"`
	ConsumedBy   pgtype.Int8        `json:"consumed_by"`
}

type InspectionLot struct {
	ID          int64              `json:"id"`
	TenantID    pgtype.Int8        `json:"tenant_id"`
	TriggerType pgtype.Text        `json:"trigger_type"`
	HuID        pgtype.Int8        `json:"hu_id"`
	Status      pgtype.Text        `json:"status"`
	Results     []byte             `json:"results"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
}

type InventoryEvent struct {
	ID             pgtype.Int8        `json:"id"`
	TenantID       pgtype.Int8        `json:"tenant_id"`
	EventType      string             `json:"event_type"`
	HuID           pgtype.Int8        `json:"hu_id"`
	ChildHuID      pgtype.Int8        `json:"child_hu_id"`
	ProductID      pgtype.Int8        `json:"product_id"`
	FromLocationID pgtype.Int8        `json:"from_location_id"`
	ToLocationID   pgtype.Int8        `json:"to_location_id"`
	Quantity       pgtype.Numeric     `json:"quantity"`
	Unit           pgtype.Text        `json:"unit"`
	ActorUserID    pgtype.Int8        `json:"actor_user_id"`
	ReferenceDoc   pgtype.Text        `json:"reference_doc"`
	Metadata       []byte             `json:"metadata"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	SiteID         pgtype.Int8        `json:"site_id"`
	ZoneID         pgtype.Int8        `json:"zone_id"`
	FromZoneID     pgtype.Int8        `json:"from_zone_id"`
	ToZoneID       pgtype.Int8        `json:"to_zone_id"`
	Notes          pgtype.Text        `json:"notes"`
}

type InventoryEvents2025 struct {
	ID             pgtype.Int8        `json:"id"`
	TenantID       pgtype.Int8        `json:"tenant_id"`
	EventType      string             `json:"event_type"`
	HuID           pgtype.Int8        `json:"hu_id"`
	ChildHuID      pgtype.Int8        `json:"child_hu_id"`
	ProductID      pgtype.Int8        `json:"product_id"`
	FromLocationID pgtype.Int8        `json:"from_location_id"`
	ToLocationID   pgtype.Int8        `json:"to_location_id"`
	Quantity       pgtype.Numeric     `json:"quantity"`
	Unit           pgtype.Text        `json:"unit"`
	ActorUserID    pgtype.Int8        `json:"actor_user_id"`
	ReferenceDoc   pgtype.Text        `json:"reference_doc"`
	Metadata       []byte             `json:"metadata"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
}

type InventoryEvents2026 struct {
	ID             pgtype.Int8        `json:"id"`
	TenantID       pgtype.Int8        `json:"tenant_id"`
	EventType      string             `json:"event_type"`
	HuID           pgtype.Int8        `json:"hu_id"`
	ChildHuID      pgtype.Int8        `json:"child_hu_id"`
	ProductID      pgtype.Int8        `json:"product_id"`
	FromLocationID pgtype.Int8        `json:"from_location_id"`
	ToLocationID   pgtype.Int8        `json:"to_location_id"`
	Quantity       pgtype.Numeric     `json:"quantity"`
	Unit           pgtype.Text        `json:"unit"`
	ActorUserID    pgtype.Int8        `json:"actor_user_id"`
	ReferenceDoc   pgtype.Text        `json:"reference_doc"`
	Metadata       []byte             `json:"metadata"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
}

type Location struct {
	ID          int64          `json:"id"`
	PublicID    pgtype.UUID    `json:"public_id"`
	TenantID    pgtype.Int8    `json:"tenant_id"`
	WarehouseID pgtype.Int8    `json:"warehouse_id"`
	Code        string         `json:"code"`
	Zone        pgtype.Text    `json:"zone"`
	Capacity    pgtype.Numeric `json:"capacity"`
	Unit        pgtype.Text    `json:"unit"`
	IsActive    pgtype.Bool    `json:"is_active"`
}

type OpeningBalanceImport struct {
	ID          int64              `json:"id"`
	TenantID    int64              `json:"tenant_id"`
	PublicID    pgtype.UUID        `json:"public_id"`
	ImportDate  pgtype.Date        `json:"import_date"`
	TotalLines  int32              `json:"total_lines"`
	PostedLines int32              `json:"posted_lines"`
	FailedLines int32              `json:"failed_lines"`
	Status      string             `json:"status"`
	ErrorLog    []byte             `json:"error_log"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
}

type Organisation struct {
	ID              int64              `json:"id"`
	TenantID        int64              `json:"tenant_id"`
	PublicID        pgtype.UUID        `json:"public_id"`
	Name            string             `json:"name"`
	LegalName       pgtype.Text        `json:"legal_name"`
	Currency        string             `json:"currency"`
	FiscalYearStart int32              `json:"fiscal_year_start"`
	IsActive        bool               `json:"is_active"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	UpdatedAt       pgtype.Timestamptz `json:"updated_at"`
}

type PriceVersion struct {
	ID        int64              `json:"id"`
	TenantID  pgtype.Int8        `json:"tenant_id"`
	ProductID pgtype.Int8        `json:"product_id"`
	Price     pgtype.Numeric     `json:"price"`
	Currency  string             `json:"currency"`
	ValidFrom pgtype.Timestamptz `json:"valid_from"`
	ValidTo   pgtype.Timestamptz `json:"valid_to"`
	CreatedBy pgtype.Int8        `json:"created_by"`
}

type Product struct {
	ID                  int64              `json:"id"`
	PublicID            pgtype.UUID        `json:"public_id"`
	TenantID            pgtype.Int8        `json:"tenant_id"`
	Code                string             `json:"code"`
	Name                string             `json:"name"`
	BaseUnit            string             `json:"base_unit"`
	Description         pgtype.Text        `json:"description"`
	Attributes          []byte             `json:"attributes"`
	CreatedAt           pgtype.Timestamptz `json:"created_at"`
	IsActive            pgtype.Bool        `json:"is_active"`
	UomConversions      []byte             `json:"uom_conversions"`
	PreferredSupplierID pgtype.Int8        `json:"preferred_supplier_id"`
}

type ProductionOrder struct {
	ID           int64              `json:"id"`
	TenantID     pgtype.Int8        `json:"tenant_id"`
	ProductID    pgtype.Int8        `json:"product_id"`
	PlannedQty   pgtype.Numeric     `json:"planned_qty"`
	ActualQty    pgtype.Numeric     `json:"actual_qty"`
	Status       pgtype.Text        `json:"status"`
	PlannedStart pgtype.Timestamptz `json:"planned_start"`
	ActualStart  pgtype.Timestamptz `json:"actual_start"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
}

type PurchaseOrder struct {
	ID                   int64              `json:"id"`
	PublicID             pgtype.UUID        `json:"public_id"`
	TenantID             int64              `json:"tenant_id"`
	PoNumber             string             `json:"po_number"`
	SupplierID           int64              `json:"supplier_id"`
	PrID                 pgtype.Int8        `json:"pr_id"`
	Status               string             `json:"status"`
	Currency             string             `json:"currency"`
	TotalValue           pgtype.Numeric     `json:"total_value"`
	ExpectedDeliveryDate pgtype.Date        `json:"expected_delivery_date"`
	Notes                pgtype.Text        `json:"notes"`
	CreatedBy            pgtype.Int8        `json:"created_by"`
	ApprovedBy           pgtype.Int8        `json:"approved_by"`
	ApprovedAt           pgtype.Timestamptz `json:"approved_at"`
	CreatedAt            pgtype.Timestamptz `json:"created_at"`
	UpdatedAt            pgtype.Timestamptz `json:"updated_at"`
	DocumentType         string             `json:"document_type"`
	DocumentDate         pgtype.Date        `json:"document_date"`
	PostingDate          pgtype.Date        `json:"posting_date"`
	SupplierNameSnapshot pgtype.Text        `json:"supplier_name_snapshot"`
	PurchasingOrg        pgtype.Text        `json:"purchasing_org"`
	PurchasingGroup      pgtype.Text        `json:"purchasing_group"`
	CompanyCode          pgtype.Text        `json:"company_code"`
	ExchangeRate         pgtype.Numeric     `json:"exchange_rate"`
	PaymentTermsDays     pgtype.Int4        `json:"payment_terms_days"`
	Incoterms            pgtype.Text        `json:"incoterms"`
	IncotermsLocation    pgtype.Text        `json:"incoterms_location"`
	GoodsReceiptExpected bool               `json:"goods_receipt_expected"`
	InvoiceExpected      bool               `json:"invoice_expected"`
	TotalNetValue        pgtype.Numeric     `json:"total_net_value"`
	TotalTax             pgtype.Numeric     `json:"total_tax"`
	TotalGrossValue      pgtype.Numeric     `json:"total_gross_value"`
	RejectionReason      pgtype.Text        `json:"rejection_reason"`
	RejectedAt           pgtype.Timestamptz `json:"rejected_at"`
	RejectedBy           pgtype.Int8        `json:"rejected_by"`
	RfqID                pgtype.Int8        `json:"rfq_id"`
	SupplierRef          pgtype.Text        `json:"supplier_ref"`
	DeliveryAddress      pgtype.Text        `json:"delivery_address"`
}

type PurchaseOrderLine struct {
	ID                        int64              `json:"id"`
	PublicID                  pgtype.UUID        `json:"public_id"`
	TenantID                  int64              `json:"tenant_id"`
	PoID                      int64              `json:"po_id"`
	ProductID                 int64              `json:"product_id"`
	Quantity                  pgtype.Numeric     `json:"quantity"`
	Unit                      string             `json:"unit"`
	UnitPrice                 pgtype.Numeric     `json:"unit_price"`
	LineValue                 pgtype.Numeric     `json:"line_value"`
	QtyReceived               pgtype.Numeric     `json:"qty_received"`
	CreatedAt                 pgtype.Timestamptz `json:"created_at"`
	LineNumber                int32              `json:"line_number"`
	ShortText                 pgtype.Text        `json:"short_text"`
	Currency                  pgtype.Text        `json:"currency"`
	LineNetValue              pgtype.Numeric     `json:"line_net_value"`
	TaxCode                   pgtype.Text        `json:"tax_code"`
	TaxAmount                 pgtype.Numeric     `json:"tax_amount"`
	LineGrossValue            pgtype.Numeric     `json:"line_gross_value"`
	DeliveryDate              pgtype.Date        `json:"delivery_date"`
	ReceivingZoneID           pgtype.Int8        `json:"receiving_zone_id"`
	OverdeliveryTolerancePct  pgtype.Numeric     `json:"overdelivery_tolerance_pct"`
	UnderdeliveryTolerancePct pgtype.Numeric     `json:"underdelivery_tolerance_pct"`
	PriceLocked               bool               `json:"price_locked"`
	AccountAssignmentType     pgtype.Text        `json:"account_assignment_type"`
	CostCentre                pgtype.Text        `json:"cost_centre"`
	QtyInvoiced               pgtype.Numeric     `json:"qty_invoiced"`
	LineNotes                 pgtype.Text        `json:"line_notes"`
	LineStatus                string             `json:"line_status"`
}

type PurchaseRequest struct {
	ID              int64              `json:"id"`
	PublicID        pgtype.UUID        `json:"public_id"`
	TenantID        int64              `json:"tenant_id"`
	PrNumber        string             `json:"pr_number"`
	Status          string             `json:"status"`
	RequiredByDate  pgtype.Date        `json:"required_by_date"`
	Notes           pgtype.Text        `json:"notes"`
	CreatedBy       pgtype.Int8        `json:"created_by"`
	ApprovedBy      pgtype.Int8        `json:"approved_by"`
	ApprovedAt      pgtype.Timestamptz `json:"approved_at"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	UpdatedAt       pgtype.Timestamptz `json:"updated_at"`
	DocumentDate    pgtype.Date        `json:"document_date"`
	PostingDate     pgtype.Date        `json:"posting_date"`
	PurchasingGroup pgtype.Text        `json:"purchasing_group"`
	CostCentre      pgtype.Text        `json:"cost_centre"`
	Priority        string             `json:"priority"`
	ReferenceDoc    pgtype.Text        `json:"reference_doc"`
	RejectionReason pgtype.Text        `json:"rejection_reason"`
	RejectionAt     pgtype.Timestamptz `json:"rejection_at"`
	RejectedBy      pgtype.Int8        `json:"rejected_by"`
	ConvertedToPoID pgtype.Int8        `json:"converted_to_po_id"`
	ConvertedAt     pgtype.Timestamptz `json:"converted_at"`
}

type PurchaseRequestLine struct {
	ID                    int64              `json:"id"`
	TenantID              int64              `json:"tenant_id"`
	PrID                  int64              `json:"pr_id"`
	ProductID             int64              `json:"product_id"`
	Quantity              pgtype.Numeric     `json:"quantity"`
	Unit                  string             `json:"unit"`
	EstimatedPrice        pgtype.Numeric     `json:"estimated_price"`
	CreatedAt             pgtype.Timestamptz `json:"created_at"`
	LineNumber            int32              `json:"line_number"`
	ShortText             pgtype.Text        `json:"short_text"`
	RequiredByDate        pgtype.Date        `json:"required_by_date"`
	EstimatedUnitPrice    pgtype.Numeric     `json:"estimated_unit_price"`
	Currency              pgtype.Text        `json:"currency"`
	LineValue             pgtype.Numeric     `json:"line_value"`
	PreferredSupplierID   pgtype.Int8        `json:"preferred_supplier_id"`
	AccountAssignmentType pgtype.Text        `json:"account_assignment_type"`
	CostCentre            pgtype.Text        `json:"cost_centre"`
	LineNotes             pgtype.Text        `json:"line_notes"`
	LineStatus            string             `json:"line_status"`
}

type Role struct {
	ID   int64  `json:"id"`
	Name string `json:"name"`
}

type SalesOrder struct {
	ID         int64              `json:"id"`
	TenantID   pgtype.Int8        `json:"tenant_id"`
	Customer   pgtype.Text        `json:"customer"`
	Status     pgtype.Text        `json:"status"`
	TotalValue pgtype.Numeric     `json:"total_value"`
	Currency   pgtype.Text        `json:"currency"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
}

type SalesOrderLine struct {
	ID        int64          `json:"id"`
	SoID      pgtype.Int8    `json:"so_id"`
	ProductID pgtype.Int8    `json:"product_id"`
	Qty       pgtype.Numeric `json:"qty"`
	Unit      pgtype.Text    `json:"unit"`
	UnitPrice pgtype.Numeric `json:"unit_price"`
}

type Shipment struct {
	ID              int64              `json:"id"`
	TenantID        pgtype.Int8        `json:"tenant_id"`
	Carrier         pgtype.Text        `json:"carrier"`
	TrackingRef     pgtype.Text        `json:"tracking_ref"`
	Status          pgtype.Text        `json:"status"`
	PlannedDispatch pgtype.Timestamptz `json:"planned_dispatch"`
	ActualDispatch  pgtype.Timestamptz `json:"actual_dispatch"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
}

type Site struct {
	ID             int64              `json:"id"`
	TenantID       int64              `json:"tenant_id"`
	OrganisationID int64              `json:"organisation_id"`
	PublicID       pgtype.UUID        `json:"public_id"`
	Code           string             `json:"code"`
	Name           string             `json:"name"`
	Address        []byte             `json:"address"`
	Timezone       string             `json:"timezone"`
	IsActive       bool               `json:"is_active"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	UpdatedAt      pgtype.Timestamptz `json:"updated_at"`
}

type StockAdjustment struct {
	ID                 int64              `json:"id"`
	PublicID           pgtype.UUID        `json:"public_id"`
	TenantID           int64              `json:"tenant_id"`
	SaNumber           string             `json:"sa_number"`
	DocumentDate       pgtype.Date        `json:"document_date"`
	PostingDate        pgtype.Date        `json:"posting_date"`
	AdjustmentType     string             `json:"adjustment_type"`
	HuID               pgtype.Int8        `json:"hu_id"`
	ProductID          int64              `json:"product_id"`
	ZoneID             int64              `json:"zone_id"`
	SiteID             int64              `json:"site_id"`
	SystemQuantity     pgtype.Numeric     `json:"system_quantity"`
	PhysicalCount      pgtype.Numeric     `json:"physical_count"`
	QuantityDifference pgtype.Numeric     `json:"quantity_difference"`
	Unit               string             `json:"unit"`
	ReasonCode         pgtype.Text        `json:"reason_code"`
	ReasonText         string             `json:"reason_text"`
	CountedBy          pgtype.Int8        `json:"counted_by"`
	PostedBy           pgtype.Int8        `json:"posted_by"`
	InventoryEventID   pgtype.Int8        `json:"inventory_event_id"`
	CreatedAt          pgtype.Timestamptz `json:"created_at"`
}

type Supplier struct {
	ID                int64              `json:"id"`
	PublicID          pgtype.UUID        `json:"public_id"`
	TenantID          int64              `json:"tenant_id"`
	Code              string             `json:"code"`
	Name              string             `json:"name"`
	ContactName       pgtype.Text        `json:"contact_name"`
	Email             pgtype.Text        `json:"email"`
	Phone             pgtype.Text        `json:"phone"`
	Currency          string             `json:"currency"`
	PaymentTermsDays  int32              `json:"payment_terms_days"`
	IsActive          bool               `json:"is_active"`
	Notes             pgtype.Text        `json:"notes"`
	CreatedAt         pgtype.Timestamptz `json:"created_at"`
	UpdatedAt         pgtype.Timestamptz `json:"updated_at"`
	AddressLine1      pgtype.Text        `json:"address_line1"`
	AddressLine2      pgtype.Text        `json:"address_line2"`
	City              pgtype.Text        `json:"city"`
	Country           pgtype.Text        `json:"country"`
	PostalCode        pgtype.Text        `json:"postal_code"`
	TaxNumber         pgtype.Text        `json:"tax_number"`
	BankName          pgtype.Text        `json:"bank_name"`
	BankAccount       pgtype.Text        `json:"bank_account"`
	BankSortCode      pgtype.Text        `json:"bank_sort_code"`
	Incoterms         pgtype.Text        `json:"incoterms"`
	IncotermsLocation pgtype.Text        `json:"incoterms_location"`
	PreferredCurrency pgtype.Text        `json:"preferred_currency"`
	CreditLimit       pgtype.Numeric     `json:"credit_limit"`
	SupplierGroup     pgtype.Text        `json:"supplier_group"`
	Rating            pgtype.Text        `json:"rating"`
	Website           pgtype.Text        `json:"website"`
	OnHold            bool               `json:"on_hold"`
	OnHoldReason      pgtype.Text        `json:"on_hold_reason"`
}

type Tenant struct {
	ID        int64              `json:"id"`
	PublicID  pgtype.UUID        `json:"public_id"`
	Name      string             `json:"name"`
	Slug      string             `json:"slug"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type TenantConfig struct {
	ID                   int64              `json:"id"`
	TenantID             int64              `json:"tenant_id"`
	GrSequenceStart      int64              `json:"gr_sequence_start"`
	PoSequenceStart      int64              `json:"po_sequence_start"`
	HuSequenceStart      int64              `json:"hu_sequence_start"`
	SoSequenceStart      int64              `json:"so_sequence_start"`
	GrNumberFormat       string             `json:"gr_number_format"`
	PoNumberFormat       string             `json:"po_number_format"`
	HuCodeFormat         string             `json:"hu_code_format"`
	SoNumberFormat       string             `json:"so_number_format"`
	DomainProfile        string             `json:"domain_profile"`
	DefaultCurrency      string             `json:"default_currency"`
	DefaultTimezone      string             `json:"default_timezone"`
	DefaultUom           string             `json:"default_uom"`
	BatchTracking        bool               `json:"batch_tracking"`
	ExpiryTracking       bool               `json:"expiry_tracking"`
	SerialTracking       bool               `json:"serial_tracking"`
	QcOnReceipt          bool               `json:"qc_on_receipt"`
	FifoEnforced         bool               `json:"fifo_enforced"`
	MigrationCompleted   bool               `json:"migration_completed"`
	MigrationCompletedAt pgtype.Timestamptz `json:"migration_completed_at"`
	GoLiveDate           pgtype.Date        `json:"go_live_date"`
	CreatedAt            pgtype.Timestamptz `json:"created_at"`
	UpdatedAt            pgtype.Timestamptz `json:"updated_at"`
	PrNumberFormat       string             `json:"pr_number_format"`
	PrSequenceStart      int64              `json:"pr_sequence_start"`
	PoApprovalThreshold  pgtype.Numeric     `json:"po_approval_threshold"`
	PoApprovalCurrency   string             `json:"po_approval_currency"`
	SaNumberFormat       string             `json:"sa_number_format"`
	RfqNumberFormat      string             `json:"rfq_number_format"`
	InvNumberFormat      string             `json:"inv_number_format"`
	TrNumberFormat       string             `json:"tr_number_format"`
}

type TenantSequence struct {
	TenantID     int64              `json:"tenant_id"`
	SequenceType string             `json:"sequence_type"`
	CurrentVal   int64              `json:"current_val"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
}

type User struct {
	ID           int64              `json:"id"`
	PublicID     pgtype.UUID        `json:"public_id"`
	TenantID     pgtype.Int8        `json:"tenant_id"`
	Username     string             `json:"username"`
	Email        pgtype.Text        `json:"email"`
	PasswordHash string             `json:"password_hash"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
}

type UserRole struct {
	UserID int64 `json:"user_id"`
	RoleID int64 `json:"role_id"`
}

type VHuLineage struct {
	ID           int64              `json:"id"`
	HuCode       pgtype.Text        `json:"hu_code"`
	ParentHuID   pgtype.Int8        `json:"parent_hu_id"`
	ProductID    pgtype.Int8        `json:"product_id"`
	Quantity     pgtype.Numeric     `json:"quantity"`
	BaseUnit     string             `json:"base_unit"`
	Status       string             `json:"status"`
	ZoneID       pgtype.Int8        `json:"zone_id"`
	SiteID       pgtype.Int8        `json:"site_id"`
	LabelVersion int32              `json:"label_version"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	Depth        int32              `json:"depth"`
	Path         interface{}        `json:"path"`
	ProductCode  string             `json:"product_code"`
	ProductName  string             `json:"product_name"`
	ZoneCode     pgtype.Text        `json:"zone_code"`
	ZoneType     pgtype.Text        `json:"zone_type"`
}

type VHuMovementHistory struct {
	TenantID      pgtype.Int8        `json:"tenant_id"`
	HuID          pgtype.Int8        `json:"hu_id"`
	HuCode        pgtype.Text        `json:"hu_code"`
	EventType     string             `json:"event_type"`
	Quantity      pgtype.Numeric     `json:"quantity"`
	BaseUnit      string             `json:"base_unit"`
	ZoneID        pgtype.Int8        `json:"zone_id"`
	ZoneCode      pgtype.Text        `json:"zone_code"`
	ZoneType      pgtype.Text        `json:"zone_type"`
	SiteID        pgtype.Int8        `json:"site_id"`
	SiteCode      pgtype.Text        `json:"site_code"`
	ReferenceType interface{}        `json:"reference_type"`
	ReferenceID   interface{}        `json:"reference_id"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
	CreatedBy     pgtype.Int8        `json:"created_by"`
}

type VProductStockSummary struct {
	TenantID       pgtype.Int8 `json:"tenant_id"`
	ProductID      pgtype.Int8 `json:"product_id"`
	ProductCode    string      `json:"product_code"`
	ProductName    string      `json:"product_name"`
	BaseUnit       string      `json:"base_unit"`
	TotalQuantity  int64       `json:"total_quantity"`
	TotalHuCount   int64       `json:"total_hu_count"`
	ZoneCount      int64       `json:"zone_count"`
	LastMovementAt interface{} `json:"last_movement_at"`
}

type VStockOnHand struct {
	TenantID       pgtype.Int8 `json:"tenant_id"`
	ProductID      pgtype.Int8 `json:"product_id"`
	ProductCode    string      `json:"product_code"`
	ProductName    string      `json:"product_name"`
	BaseUnit       string      `json:"base_unit"`
	ZoneID         pgtype.Int8 `json:"zone_id"`
	ZoneCode       string      `json:"zone_code"`
	ZoneName       string      `json:"zone_name"`
	ZoneType       string      `json:"zone_type"`
	SiteID         pgtype.Int8 `json:"site_id"`
	SiteCode       string      `json:"site_code"`
	SiteName       string      `json:"site_name"`
	HuCount        int64       `json:"hu_count"`
	QuantityOnHand int64       `json:"quantity_on_hand"`
	LastMovementAt interface{} `json:"last_movement_at"`
}

type VZoneStock struct {
	TenantID      pgtype.Int8 `json:"tenant_id"`
	ZoneID        pgtype.Int8 `json:"zone_id"`
	ZoneCode      string      `json:"zone_code"`
	ZoneName      string      `json:"zone_name"`
	ZoneType      string      `json:"zone_type"`
	SiteID        pgtype.Int8 `json:"site_id"`
	SiteCode      string      `json:"site_code"`
	ProductCount  int64       `json:"product_count"`
	HuCount       int64       `json:"hu_count"`
	TotalQuantity interface{} `json:"total_quantity"`
	Products      []byte      `json:"products"`
}

type Warehouse struct {
	ID       int64       `json:"id"`
	TenantID pgtype.Int8 `json:"tenant_id"`
	Name     string      `json:"name"`
	Code     string      `json:"code"`
}

type WarehouseTask struct {
	ID             int64              `json:"id"`
	PublicID       pgtype.UUID        `json:"public_id"`
	TenantID       pgtype.Int8        `json:"tenant_id"`
	TaskType       string             `json:"task_type"`
	Priority       pgtype.Int4        `json:"priority"`
	Status         string             `json:"status"`
	HuID           pgtype.Int8        `json:"hu_id"`
	FromLocationID pgtype.Int8        `json:"from_location_id"`
	ToLocationID   pgtype.Int8        `json:"to_location_id"`
	AssignedTo     pgtype.Int8        `json:"assigned_to"`
	OpenedAt       pgtype.Timestamptz `json:"opened_at"`
	ConfirmedAt    pgtype.Timestamptz `json:"confirmed_at"`
	FromSiteID     pgtype.Int8        `json:"from_site_id"`
	FromZoneID     pgtype.Int8        `json:"from_zone_id"`
	ToSiteID       pgtype.Int8        `json:"to_site_id"`
	ToZoneID       pgtype.Int8        `json:"to_zone_id"`
}

type Zone struct {
	ID        int64              `json:"id"`
	TenantID  int64              `json:"tenant_id"`
	SiteID    int64              `json:"site_id"`
	PublicID  pgtype.UUID        `json:"public_id"`
	Code      string             `json:"code"`
	Name      string             `json:"name"`
	ZoneType  string             `json:"zone_type"`
	IsActive  bool               `json:"is_active"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}
