// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.20.0
// source: pricing_ui.sql

package dbgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const closeProductPriceHistory = `-- name: CloseProductPriceHistory :exec
UPDATE product_price_history
SET valid_to = now()
WHERE product_id = $1 AND tenant_id = $2 AND price_type = 'STANDARD' AND valid_to IS NULL
`

type CloseProductPriceHistoryParams struct {
	ProductID int64 `json:"product_id"`
	TenantID  int64 `json:"tenant_id"`
}

func (q *Queries) CloseProductPriceHistory(ctx context.Context, arg CloseProductPriceHistoryParams) error {
	_, err := q.db.Exec(ctx, closeProductPriceHistory, arg.ProductID, arg.TenantID)
	return err
}

const countConditionTypes = `-- name: CountConditionTypes :one
SELECT COUNT(*) FROM condition_types WHERE tenant_id = $1
`

func (q *Queries) CountConditionTypes(ctx context.Context, tenantID int64) (int64, error) {
	row := q.db.QueryRow(ctx, countConditionTypes, tenantID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createCalculationSchema = `-- name: CreateCalculationSchema :one
INSERT INTO calculation_schemas (tenant_id, code, name, is_active)
VALUES ($1, $2, $3, $4) RETURNING id
`

type CreateCalculationSchemaParams struct {
	TenantID int64  `json:"tenant_id"`
	Code     string `json:"code"`
	Name     string `json:"name"`
	IsActive bool   `json:"is_active"`
}

func (q *Queries) CreateCalculationSchema(ctx context.Context, arg CreateCalculationSchemaParams) (int64, error) {
	row := q.db.QueryRow(ctx, createCalculationSchema,
		arg.TenantID,
		arg.Code,
		arg.Name,
		arg.IsActive,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const createCalculationSchemaStep = `-- name: CreateCalculationSchemaStep :exec
INSERT INTO calculation_schema_steps (
    tenant_id, schema_id, step_number, condition_type_id, subtotal_flag, is_statistical
) VALUES (
    $1, $2, $3, $4, $5, $6
)
`

type CreateCalculationSchemaStepParams struct {
	TenantID        int64       `json:"tenant_id"`
	SchemaID        int64       `json:"schema_id"`
	StepNumber      int32       `json:"step_number"`
	ConditionTypeID pgtype.Int8 `json:"condition_type_id"`
	SubtotalFlag    pgtype.Text `json:"subtotal_flag"`
	IsStatistical   bool        `json:"is_statistical"`
}

func (q *Queries) CreateCalculationSchemaStep(ctx context.Context, arg CreateCalculationSchemaStepParams) error {
	_, err := q.db.Exec(ctx, createCalculationSchemaStep,
		arg.TenantID,
		arg.SchemaID,
		arg.StepNumber,
		arg.ConditionTypeID,
		arg.SubtotalFlag,
		arg.IsStatistical,
	)
	return err
}

const createConditionType = `-- name: CreateConditionType :one
INSERT INTO condition_types (
    tenant_id, code, name, condition_class, calculation_type, plus_minus, base_step, is_active
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8
) RETURNING id
`

type CreateConditionTypeParams struct {
	TenantID        int64       `json:"tenant_id"`
	Code            string      `json:"code"`
	Name            string      `json:"name"`
	ConditionClass  string      `json:"condition_class"`
	CalculationType string      `json:"calculation_type"`
	PlusMinus       string      `json:"plus_minus"`
	BaseStep        pgtype.Int4 `json:"base_step"`
	IsActive        bool        `json:"is_active"`
}

func (q *Queries) CreateConditionType(ctx context.Context, arg CreateConditionTypeParams) (int64, error) {
	row := q.db.QueryRow(ctx, createConditionType,
		arg.TenantID,
		arg.Code,
		arg.Name,
		arg.ConditionClass,
		arg.CalculationType,
		arg.PlusMinus,
		arg.BaseStep,
		arg.IsActive,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const createProductPriceHistory = `-- name: CreateProductPriceHistory :exec
INSERT INTO product_price_history (
    tenant_id, product_id, price_type, price, currency, valid_from, changed_by_username, change_reason, source_document
) VALUES (
    $1, $2, $3, $4, $5, now(), $6, $7, $8
)
`

type CreateProductPriceHistoryParams struct {
	TenantID          int64          `json:"tenant_id"`
	ProductID         int64          `json:"product_id"`
	PriceType         string         `json:"price_type"`
	Price             pgtype.Numeric `json:"price"`
	Currency          string         `json:"currency"`
	ChangedByUsername pgtype.Text    `json:"changed_by_username"`
	ChangeReason      pgtype.Text    `json:"change_reason"`
	SourceDocument    pgtype.Text    `json:"source_document"`
}

func (q *Queries) CreateProductPriceHistory(ctx context.Context, arg CreateProductPriceHistoryParams) error {
	_, err := q.db.Exec(ctx, createProductPriceHistory,
		arg.TenantID,
		arg.ProductID,
		arg.PriceType,
		arg.Price,
		arg.Currency,
		arg.ChangedByUsername,
		arg.ChangeReason,
		arg.SourceDocument,
	)
	return err
}

const generateNextInfoRecordSequence = `-- name: GenerateNextInfoRecordSequence :one
UPDATE tenant_sequences
SET current_val = current_val + 1
WHERE tenant_id = $1 AND sequence_type = 'ir'
RETURNING current_val
`

func (q *Queries) GenerateNextInfoRecordSequence(ctx context.Context, tenantID int64) (int64, error) {
	row := q.db.QueryRow(ctx, generateNextInfoRecordSequence, tenantID)
	var current_val int64
	err := row.Scan(&current_val)
	return current_val, err
}

const getIRNumberFormat = `-- name: GetIRNumberFormat :one
SELECT ir_number_format FROM tenant_config WHERE tenant_id = $1
`

func (q *Queries) GetIRNumberFormat(ctx context.Context, tenantID int64) (string, error) {
	row := q.db.QueryRow(ctx, getIRNumberFormat, tenantID)
	var ir_number_format string
	err := row.Scan(&ir_number_format)
	return ir_number_format, err
}

const getPricingConfig = `-- name: GetPricingConfig :one
SELECT approval_mode, flat_pr_threshold, flat_po_threshold, default_tolerance_pct, default_currency, condition_types_seeded
FROM tenant_config WHERE tenant_id = $1
`

type GetPricingConfigRow struct {
	ApprovalMode         string         `json:"approval_mode"`
	FlatPrThreshold      pgtype.Numeric `json:"flat_pr_threshold"`
	FlatPoThreshold      pgtype.Numeric `json:"flat_po_threshold"`
	DefaultTolerancePct  pgtype.Numeric `json:"default_tolerance_pct"`
	DefaultCurrency      string         `json:"default_currency"`
	ConditionTypesSeeded bool           `json:"condition_types_seeded"`
}

func (q *Queries) GetPricingConfig(ctx context.Context, tenantID int64) (GetPricingConfigRow, error) {
	row := q.db.QueryRow(ctx, getPricingConfig, tenantID)
	var i GetPricingConfigRow
	err := row.Scan(
		&i.ApprovalMode,
		&i.FlatPrThreshold,
		&i.FlatPoThreshold,
		&i.DefaultTolerancePct,
		&i.DefaultCurrency,
		&i.ConditionTypesSeeded,
	)
	return i, err
}

const getProductPricing = `-- name: GetProductPricing :one
SELECT price_control, standard_price, standard_price_unit, standard_currency, map_price, last_po_price, last_po_date, auto_approve_tolerance_pct, requires_quotation, reorder_point, safety_stock, max_stock_level, procurement_type
FROM products WHERE id = $1 AND tenant_id = $2
`

type GetProductPricingParams struct {
	ID       int64       `json:"id"`
	TenantID pgtype.Int8 `json:"tenant_id"`
}

type GetProductPricingRow struct {
	PriceControl            string         `json:"price_control"`
	StandardPrice           pgtype.Numeric `json:"standard_price"`
	StandardPriceUnit       pgtype.Numeric `json:"standard_price_unit"`
	StandardCurrency        string         `json:"standard_currency"`
	MapPrice                pgtype.Numeric `json:"map_price"`
	LastPoPrice             pgtype.Numeric `json:"last_po_price"`
	LastPoDate              pgtype.Date    `json:"last_po_date"`
	AutoApproveTolerancePct pgtype.Numeric `json:"auto_approve_tolerance_pct"`
	RequiresQuotation       bool           `json:"requires_quotation"`
	ReorderPoint            pgtype.Numeric `json:"reorder_point"`
	SafetyStock             pgtype.Numeric `json:"safety_stock"`
	MaxStockLevel           pgtype.Numeric `json:"max_stock_level"`
	ProcurementType         string         `json:"procurement_type"`
}

func (q *Queries) GetProductPricing(ctx context.Context, arg GetProductPricingParams) (GetProductPricingRow, error) {
	row := q.db.QueryRow(ctx, getProductPricing, arg.ID, arg.TenantID)
	var i GetProductPricingRow
	err := row.Scan(
		&i.PriceControl,
		&i.StandardPrice,
		&i.StandardPriceUnit,
		&i.StandardCurrency,
		&i.MapPrice,
		&i.LastPoPrice,
		&i.LastPoDate,
		&i.AutoApproveTolerancePct,
		&i.RequiresQuotation,
		&i.ReorderPoint,
		&i.SafetyStock,
		&i.MaxStockLevel,
		&i.ProcurementType,
	)
	return i, err
}

const listAllInfoRecords = `-- name: ListAllInfoRecords :many
SELECT ir.id, ir.tenant_id, ir.public_id, ir.info_record_number, ir.supplier_id, ir.product_id, ir.site_id, ir.purchasing_org, ir.supplier_material_num, ir.planned_delivery_time_days, ir.standard_qty, ir.minimum_qty, ir.max_order_quantity, ir.overdelivery_tolerance_pct, ir.underdelivery_tolerance_pct, ir.auto_approve_below, ir.requires_quotation, ir.net_price, ir.currency, ir.per_quantity, ir.per_unit, ir.valid_from, ir.valid_to, ir.is_active, ir.created_at, ir.updated_at, s.name as supplier_name, p.code as product_code, p.name as product_name
FROM purchasing_info_records ir
JOIN suppliers s ON ir.supplier_id = s.id
JOIN products p ON ir.product_id = p.id
WHERE ir.tenant_id = $1 AND ($2::boolean = false OR ir.is_active = true)
ORDER BY s.name ASC, p.name ASC
`

type ListAllInfoRecordsParams struct {
	TenantID   int64       `json:"tenant_id"`
	ActiveOnly pgtype.Bool `json:"active_only"`
}

type ListAllInfoRecordsRow struct {
	ID                        int64              `json:"id"`
	TenantID                  int64              `json:"tenant_id"`
	PublicID                  pgtype.UUID        `json:"public_id"`
	InfoRecordNumber          string             `json:"info_record_number"`
	SupplierID                int64              `json:"supplier_id"`
	ProductID                 int64              `json:"product_id"`
	SiteID                    pgtype.Int8        `json:"site_id"`
	PurchasingOrg             pgtype.Text        `json:"purchasing_org"`
	SupplierMaterialNum       pgtype.Text        `json:"supplier_material_num"`
	PlannedDeliveryTimeDays   pgtype.Int4        `json:"planned_delivery_time_days"`
	StandardQty               pgtype.Numeric     `json:"standard_qty"`
	MinimumQty                pgtype.Numeric     `json:"minimum_qty"`
	MaxOrderQuantity          pgtype.Numeric     `json:"max_order_quantity"`
	OverdeliveryTolerancePct  pgtype.Numeric     `json:"overdelivery_tolerance_pct"`
	UnderdeliveryTolerancePct pgtype.Numeric     `json:"underdelivery_tolerance_pct"`
	AutoApproveBelow          pgtype.Numeric     `json:"auto_approve_below"`
	RequiresQuotation         bool               `json:"requires_quotation"`
	NetPrice                  pgtype.Numeric     `json:"net_price"`
	Currency                  pgtype.Text        `json:"currency"`
	PerQuantity               pgtype.Numeric     `json:"per_quantity"`
	PerUnit                   pgtype.Text        `json:"per_unit"`
	ValidFrom                 pgtype.Date        `json:"valid_from"`
	ValidTo                   pgtype.Date        `json:"valid_to"`
	IsActive                  bool               `json:"is_active"`
	CreatedAt                 pgtype.Timestamptz `json:"created_at"`
	UpdatedAt                 pgtype.Timestamptz `json:"updated_at"`
	SupplierName              string             `json:"supplier_name"`
	ProductCode               string             `json:"product_code"`
	ProductName               string             `json:"product_name"`
}

func (q *Queries) ListAllInfoRecords(ctx context.Context, arg ListAllInfoRecordsParams) ([]ListAllInfoRecordsRow, error) {
	rows, err := q.db.Query(ctx, listAllInfoRecords, arg.TenantID, arg.ActiveOnly)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListAllInfoRecordsRow{}
	for rows.Next() {
		var i ListAllInfoRecordsRow
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.PublicID,
			&i.InfoRecordNumber,
			&i.SupplierID,
			&i.ProductID,
			&i.SiteID,
			&i.PurchasingOrg,
			&i.SupplierMaterialNum,
			&i.PlannedDeliveryTimeDays,
			&i.StandardQty,
			&i.MinimumQty,
			&i.MaxOrderQuantity,
			&i.OverdeliveryTolerancePct,
			&i.UnderdeliveryTolerancePct,
			&i.AutoApproveBelow,
			&i.RequiresQuotation,
			&i.NetPrice,
			&i.Currency,
			&i.PerQuantity,
			&i.PerUnit,
			&i.ValidFrom,
			&i.ValidTo,
			&i.IsActive,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.SupplierName,
			&i.ProductCode,
			&i.ProductName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listProductPriceHistory = `-- name: ListProductPriceHistory :many
SELECT id, tenant_id, product_id, price_type, price, currency, valid_from, valid_to, changed_by_username, change_reason, source_document, created_at FROM product_price_history
WHERE product_id = $1 AND tenant_id = $2
ORDER BY valid_from DESC
`

type ListProductPriceHistoryParams struct {
	ProductID int64 `json:"product_id"`
	TenantID  int64 `json:"tenant_id"`
}

func (q *Queries) ListProductPriceHistory(ctx context.Context, arg ListProductPriceHistoryParams) ([]ProductPriceHistory, error) {
	rows, err := q.db.Query(ctx, listProductPriceHistory, arg.ProductID, arg.TenantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ProductPriceHistory{}
	for rows.Next() {
		var i ProductPriceHistory
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.ProductID,
			&i.PriceType,
			&i.Price,
			&i.Currency,
			&i.ValidFrom,
			&i.ValidTo,
			&i.ChangedByUsername,
			&i.ChangeReason,
			&i.SourceDocument,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSupplierInfoRecords = `-- name: ListSupplierInfoRecords :many
SELECT ir.id, ir.tenant_id, ir.public_id, ir.info_record_number, ir.supplier_id, ir.product_id, ir.site_id, ir.purchasing_org, ir.supplier_material_num, ir.planned_delivery_time_days, ir.standard_qty, ir.minimum_qty, ir.max_order_quantity, ir.overdelivery_tolerance_pct, ir.underdelivery_tolerance_pct, ir.auto_approve_below, ir.requires_quotation, ir.net_price, ir.currency, ir.per_quantity, ir.per_unit, ir.valid_from, ir.valid_to, ir.is_active, ir.created_at, ir.updated_at, p.code as product_code, p.name as product_name
FROM purchasing_info_records ir
JOIN products p ON ir.product_id = p.id
WHERE ir.tenant_id = $1 AND ir.supplier_id = $2 AND ir.is_active = true
ORDER BY ir.created_at DESC
`

type ListSupplierInfoRecordsParams struct {
	TenantID   int64 `json:"tenant_id"`
	SupplierID int64 `json:"supplier_id"`
}

type ListSupplierInfoRecordsRow struct {
	ID                        int64              `json:"id"`
	TenantID                  int64              `json:"tenant_id"`
	PublicID                  pgtype.UUID        `json:"public_id"`
	InfoRecordNumber          string             `json:"info_record_number"`
	SupplierID                int64              `json:"supplier_id"`
	ProductID                 int64              `json:"product_id"`
	SiteID                    pgtype.Int8        `json:"site_id"`
	PurchasingOrg             pgtype.Text        `json:"purchasing_org"`
	SupplierMaterialNum       pgtype.Text        `json:"supplier_material_num"`
	PlannedDeliveryTimeDays   pgtype.Int4        `json:"planned_delivery_time_days"`
	StandardQty               pgtype.Numeric     `json:"standard_qty"`
	MinimumQty                pgtype.Numeric     `json:"minimum_qty"`
	MaxOrderQuantity          pgtype.Numeric     `json:"max_order_quantity"`
	OverdeliveryTolerancePct  pgtype.Numeric     `json:"overdelivery_tolerance_pct"`
	UnderdeliveryTolerancePct pgtype.Numeric     `json:"underdelivery_tolerance_pct"`
	AutoApproveBelow          pgtype.Numeric     `json:"auto_approve_below"`
	RequiresQuotation         bool               `json:"requires_quotation"`
	NetPrice                  pgtype.Numeric     `json:"net_price"`
	Currency                  pgtype.Text        `json:"currency"`
	PerQuantity               pgtype.Numeric     `json:"per_quantity"`
	PerUnit                   pgtype.Text        `json:"per_unit"`
	ValidFrom                 pgtype.Date        `json:"valid_from"`
	ValidTo                   pgtype.Date        `json:"valid_to"`
	IsActive                  bool               `json:"is_active"`
	CreatedAt                 pgtype.Timestamptz `json:"created_at"`
	UpdatedAt                 pgtype.Timestamptz `json:"updated_at"`
	ProductCode               string             `json:"product_code"`
	ProductName               string             `json:"product_name"`
}

func (q *Queries) ListSupplierInfoRecords(ctx context.Context, arg ListSupplierInfoRecordsParams) ([]ListSupplierInfoRecordsRow, error) {
	rows, err := q.db.Query(ctx, listSupplierInfoRecords, arg.TenantID, arg.SupplierID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListSupplierInfoRecordsRow{}
	for rows.Next() {
		var i ListSupplierInfoRecordsRow
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.PublicID,
			&i.InfoRecordNumber,
			&i.SupplierID,
			&i.ProductID,
			&i.SiteID,
			&i.PurchasingOrg,
			&i.SupplierMaterialNum,
			&i.PlannedDeliveryTimeDays,
			&i.StandardQty,
			&i.MinimumQty,
			&i.MaxOrderQuantity,
			&i.OverdeliveryTolerancePct,
			&i.UnderdeliveryTolerancePct,
			&i.AutoApproveBelow,
			&i.RequiresQuotation,
			&i.NetPrice,
			&i.Currency,
			&i.PerQuantity,
			&i.PerUnit,
			&i.ValidFrom,
			&i.ValidTo,
			&i.IsActive,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ProductCode,
			&i.ProductName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markConditionTypesSeeded = `-- name: MarkConditionTypesSeeded :exec
UPDATE tenant_config
SET condition_types_seeded = true
WHERE tenant_id = $1
`

func (q *Queries) MarkConditionTypesSeeded(ctx context.Context, tenantID int64) error {
	_, err := q.db.Exec(ctx, markConditionTypesSeeded, tenantID)
	return err
}

const updatePricingConfig = `-- name: UpdatePricingConfig :exec
UPDATE tenant_config
SET approval_mode = $2, flat_pr_threshold = $3, flat_po_threshold = $4, default_tolerance_pct = $5, default_currency = $6
WHERE tenant_id = $1
`

type UpdatePricingConfigParams struct {
	TenantID            int64          `json:"tenant_id"`
	ApprovalMode        string         `json:"approval_mode"`
	FlatPrThreshold     pgtype.Numeric `json:"flat_pr_threshold"`
	FlatPoThreshold     pgtype.Numeric `json:"flat_po_threshold"`
	DefaultTolerancePct pgtype.Numeric `json:"default_tolerance_pct"`
	DefaultCurrency     string         `json:"default_currency"`
}

func (q *Queries) UpdatePricingConfig(ctx context.Context, arg UpdatePricingConfigParams) error {
	_, err := q.db.Exec(ctx, updatePricingConfig,
		arg.TenantID,
		arg.ApprovalMode,
		arg.FlatPrThreshold,
		arg.FlatPoThreshold,
		arg.DefaultTolerancePct,
		arg.DefaultCurrency,
	)
	return err
}

const updateProductPricing = `-- name: UpdateProductPricing :exec
UPDATE products
SET price_control = $3,
    standard_price = $4,
    standard_price_unit = $5,
    standard_currency = $6,
    map_price = $7,
    auto_approve_tolerance_pct = $8,
    requires_quotation = $9,
    reorder_point = $10,
    safety_stock = $11,
    max_stock_level = $12,
    procurement_type = $13
WHERE id = $1 AND tenant_id = $2
`

type UpdateProductPricingParams struct {
	ID                      int64          `json:"id"`
	TenantID                pgtype.Int8    `json:"tenant_id"`
	PriceControl            string         `json:"price_control"`
	StandardPrice           pgtype.Numeric `json:"standard_price"`
	StandardPriceUnit       pgtype.Numeric `json:"standard_price_unit"`
	StandardCurrency        string         `json:"standard_currency"`
	MapPrice                pgtype.Numeric `json:"map_price"`
	AutoApproveTolerancePct pgtype.Numeric `json:"auto_approve_tolerance_pct"`
	RequiresQuotation       bool           `json:"requires_quotation"`
	ReorderPoint            pgtype.Numeric `json:"reorder_point"`
	SafetyStock             pgtype.Numeric `json:"safety_stock"`
	MaxStockLevel           pgtype.Numeric `json:"max_stock_level"`
	ProcurementType         string         `json:"procurement_type"`
}

func (q *Queries) UpdateProductPricing(ctx context.Context, arg UpdateProductPricingParams) error {
	_, err := q.db.Exec(ctx, updateProductPricing,
		arg.ID,
		arg.TenantID,
		arg.PriceControl,
		arg.StandardPrice,
		arg.StandardPriceUnit,
		arg.StandardCurrency,
		arg.MapPrice,
		arg.AutoApproveTolerancePct,
		arg.RequiresQuotation,
		arg.ReorderPoint,
		arg.SafetyStock,
		arg.MaxStockLevel,
		arg.ProcurementType,
	)
	return err
}
