// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0
// source: pricing.sql

package dbgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createPurchasingInfoRecord = `-- name: CreatePurchasingInfoRecord :one
INSERT INTO purchasing_info_records (
    tenant_id, info_record_number, supplier_id, product_id, site_id, purchasing_org, 
    supplier_material_num, planned_delivery_time_days, standard_qty, 
    minimum_qty, max_order_quantity, overdelivery_tolerance_pct, underdelivery_tolerance_pct,
    auto_approve_below, requires_quotation, net_price, currency, per_quantity, per_unit,
    valid_from, valid_to, is_active
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15, $16, $17, $18, $19, $20, $21, $22
) RETURNING id, tenant_id, public_id, info_record_number, supplier_id, product_id, site_id, purchasing_org, supplier_material_num, planned_delivery_time_days, standard_qty, minimum_qty, max_order_quantity, overdelivery_tolerance_pct, underdelivery_tolerance_pct, auto_approve_below, requires_quotation, net_price, currency, per_quantity, per_unit, valid_from, valid_to, is_active, created_at, updated_at
`

type CreatePurchasingInfoRecordParams struct {
	TenantID                  int64          `json:"tenant_id"`
	InfoRecordNumber          string         `json:"info_record_number"`
	SupplierID                int64          `json:"supplier_id"`
	ProductID                 int64          `json:"product_id"`
	SiteID                    pgtype.Int8    `json:"site_id"`
	PurchasingOrg             pgtype.Text    `json:"purchasing_org"`
	SupplierMaterialNum       pgtype.Text    `json:"supplier_material_num"`
	PlannedDeliveryTimeDays   pgtype.Int4    `json:"planned_delivery_time_days"`
	StandardQty               pgtype.Numeric `json:"standard_qty"`
	MinimumQty                pgtype.Numeric `json:"minimum_qty"`
	MaxOrderQuantity          pgtype.Numeric `json:"max_order_quantity"`
	OverdeliveryTolerancePct  pgtype.Numeric `json:"overdelivery_tolerance_pct"`
	UnderdeliveryTolerancePct pgtype.Numeric `json:"underdelivery_tolerance_pct"`
	AutoApproveBelow          pgtype.Numeric `json:"auto_approve_below"`
	RequiresQuotation         bool           `json:"requires_quotation"`
	NetPrice                  pgtype.Numeric `json:"net_price"`
	Currency                  pgtype.Text    `json:"currency"`
	PerQuantity               pgtype.Numeric `json:"per_quantity"`
	PerUnit                   pgtype.Text    `json:"per_unit"`
	ValidFrom                 pgtype.Date    `json:"valid_from"`
	ValidTo                   pgtype.Date    `json:"valid_to"`
	IsActive                  bool           `json:"is_active"`
}

func (q *Queries) CreatePurchasingInfoRecord(ctx context.Context, arg CreatePurchasingInfoRecordParams) (PurchasingInfoRecord, error) {
	row := q.db.QueryRow(ctx, createPurchasingInfoRecord,
		arg.TenantID,
		arg.InfoRecordNumber,
		arg.SupplierID,
		arg.ProductID,
		arg.SiteID,
		arg.PurchasingOrg,
		arg.SupplierMaterialNum,
		arg.PlannedDeliveryTimeDays,
		arg.StandardQty,
		arg.MinimumQty,
		arg.MaxOrderQuantity,
		arg.OverdeliveryTolerancePct,
		arg.UnderdeliveryTolerancePct,
		arg.AutoApproveBelow,
		arg.RequiresQuotation,
		arg.NetPrice,
		arg.Currency,
		arg.PerQuantity,
		arg.PerUnit,
		arg.ValidFrom,
		arg.ValidTo,
		arg.IsActive,
	)
	var i PurchasingInfoRecord
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.PublicID,
		&i.InfoRecordNumber,
		&i.SupplierID,
		&i.ProductID,
		&i.SiteID,
		&i.PurchasingOrg,
		&i.SupplierMaterialNum,
		&i.PlannedDeliveryTimeDays,
		&i.StandardQty,
		&i.MinimumQty,
		&i.MaxOrderQuantity,
		&i.OverdeliveryTolerancePct,
		&i.UnderdeliveryTolerancePct,
		&i.AutoApproveBelow,
		&i.RequiresQuotation,
		&i.NetPrice,
		&i.Currency,
		&i.PerQuantity,
		&i.PerUnit,
		&i.ValidFrom,
		&i.ValidTo,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getAccessSequenceSteps = `-- name: GetAccessSequenceSteps :many
SELECT s.id, s.tenant_id, s.access_sequence_id, s.step_number, s.table_name 
FROM access_sequence_steps s
WHERE s.tenant_id = $1 AND s.access_sequence_id = $2
ORDER BY s.step_number ASC
`

type GetAccessSequenceStepsParams struct {
	TenantID         int64 `json:"tenant_id"`
	AccessSequenceID int64 `json:"access_sequence_id"`
}

func (q *Queries) GetAccessSequenceSteps(ctx context.Context, arg GetAccessSequenceStepsParams) ([]AccessSequenceStep, error) {
	rows, err := q.db.Query(ctx, getAccessSequenceSteps, arg.TenantID, arg.AccessSequenceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AccessSequenceStep{}
	for rows.Next() {
		var i AccessSequenceStep
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.AccessSequenceID,
			&i.StepNumber,
			&i.TableName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getCalculationSchema = `-- name: GetCalculationSchema :one
SELECT id, tenant_id, code, name, is_active FROM calculation_schemas
WHERE tenant_id = $1 AND code = $2 LIMIT 1
`

type GetCalculationSchemaParams struct {
	TenantID int64  `json:"tenant_id"`
	Code     string `json:"code"`
}

func (q *Queries) GetCalculationSchema(ctx context.Context, arg GetCalculationSchemaParams) (CalculationSchema, error) {
	row := q.db.QueryRow(ctx, getCalculationSchema, arg.TenantID, arg.Code)
	var i CalculationSchema
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Code,
		&i.Name,
		&i.IsActive,
	)
	return i, err
}

const getCalculationSchemaSteps = `-- name: GetCalculationSchemaSteps :many
SELECT s.id, s.tenant_id, s.schema_id, s.step_number, s.condition_type_id, s.is_required, s.is_statistical, s.subtotal_flag, c.code as condition_type_code, c.calculation_type, c.condition_class, c.base_step, c.plus_minus
FROM calculation_schema_steps s
LEFT JOIN condition_types c ON s.condition_type_id = c.id
WHERE s.tenant_id = $1 AND s.schema_id = $2
ORDER BY s.step_number ASC
`

type GetCalculationSchemaStepsParams struct {
	TenantID int64 `json:"tenant_id"`
	SchemaID int64 `json:"schema_id"`
}

type GetCalculationSchemaStepsRow struct {
	ID                int64       `json:"id"`
	TenantID          int64       `json:"tenant_id"`
	SchemaID          int64       `json:"schema_id"`
	StepNumber        int32       `json:"step_number"`
	ConditionTypeID   pgtype.Int8 `json:"condition_type_id"`
	IsRequired        bool        `json:"is_required"`
	IsStatistical     bool        `json:"is_statistical"`
	SubtotalFlag      pgtype.Text `json:"subtotal_flag"`
	ConditionTypeCode pgtype.Text `json:"condition_type_code"`
	CalculationType   pgtype.Text `json:"calculation_type"`
	ConditionClass    pgtype.Text `json:"condition_class"`
	BaseStep          pgtype.Int4 `json:"base_step"`
	PlusMinus         pgtype.Text `json:"plus_minus"`
}

func (q *Queries) GetCalculationSchemaSteps(ctx context.Context, arg GetCalculationSchemaStepsParams) ([]GetCalculationSchemaStepsRow, error) {
	rows, err := q.db.Query(ctx, getCalculationSchemaSteps, arg.TenantID, arg.SchemaID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetCalculationSchemaStepsRow{}
	for rows.Next() {
		var i GetCalculationSchemaStepsRow
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.SchemaID,
			&i.StepNumber,
			&i.ConditionTypeID,
			&i.IsRequired,
			&i.IsStatistical,
			&i.SubtotalFlag,
			&i.ConditionTypeCode,
			&i.CalculationType,
			&i.ConditionClass,
			&i.BaseStep,
			&i.PlusMinus,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getConditionTypeByCode = `-- name: GetConditionTypeByCode :one
SELECT id, tenant_id, code, name, condition_class, calculation_type, plus_minus, base_step, is_active, access_sequence_id FROM condition_types 
WHERE tenant_id = $1 AND code = $2 LIMIT 1
`

type GetConditionTypeByCodeParams struct {
	TenantID int64  `json:"tenant_id"`
	Code     string `json:"code"`
}

func (q *Queries) GetConditionTypeByCode(ctx context.Context, arg GetConditionTypeByCodeParams) (ConditionType, error) {
	row := q.db.QueryRow(ctx, getConditionTypeByCode, arg.TenantID, arg.Code)
	var i ConditionType
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Code,
		&i.Name,
		&i.ConditionClass,
		&i.CalculationType,
		&i.PlusMinus,
		&i.BaseStep,
		&i.IsActive,
		&i.AccessSequenceID,
	)
	return i, err
}

const getPurchasingInfoRecord = `-- name: GetPurchasingInfoRecord :one
SELECT id, tenant_id, public_id, info_record_number, supplier_id, product_id, site_id, purchasing_org, supplier_material_num, planned_delivery_time_days, standard_qty, minimum_qty, max_order_quantity, overdelivery_tolerance_pct, underdelivery_tolerance_pct, auto_approve_below, requires_quotation, net_price, currency, per_quantity, per_unit, valid_from, valid_to, is_active, created_at, updated_at FROM purchasing_info_records
WHERE tenant_id = $1 
  AND supplier_id = $2
  AND product_id = $3
  AND ($4::bigint IS NULL OR site_id = $4)
LIMIT 1
`

type GetPurchasingInfoRecordParams struct {
	TenantID   int64       `json:"tenant_id"`
	SupplierID int64       `json:"supplier_id"`
	ProductID  int64       `json:"product_id"`
	SiteID     pgtype.Int8 `json:"site_id"`
}

func (q *Queries) GetPurchasingInfoRecord(ctx context.Context, arg GetPurchasingInfoRecordParams) (PurchasingInfoRecord, error) {
	row := q.db.QueryRow(ctx, getPurchasingInfoRecord,
		arg.TenantID,
		arg.SupplierID,
		arg.ProductID,
		arg.SiteID,
	)
	var i PurchasingInfoRecord
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.PublicID,
		&i.InfoRecordNumber,
		&i.SupplierID,
		&i.ProductID,
		&i.SiteID,
		&i.PurchasingOrg,
		&i.SupplierMaterialNum,
		&i.PlannedDeliveryTimeDays,
		&i.StandardQty,
		&i.MinimumQty,
		&i.MaxOrderQuantity,
		&i.OverdeliveryTolerancePct,
		&i.UnderdeliveryTolerancePct,
		&i.AutoApproveBelow,
		&i.RequiresQuotation,
		&i.NetPrice,
		&i.Currency,
		&i.PerQuantity,
		&i.PerUnit,
		&i.ValidFrom,
		&i.ValidTo,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getValidConditionRecord = `-- name: GetValidConditionRecord :one
SELECT id, tenant_id, public_id, condition_type_id, supplier_id, product_id, site_id, purchasing_org, valid_from, valid_to, rate_amount, currency, pricing_unit, uom, created_at, updated_at FROM pricing_condition_records
WHERE tenant_id = $1 
  AND condition_type_id = $2
  AND valid_from <= $3 
  AND valid_to >= $3
  AND ($4::bigint IS NULL OR supplier_id = $4)
  AND ($5::bigint IS NULL OR product_id = $5)
  AND ($6::bigint IS NULL OR site_id = $6)
ORDER BY rate_amount DESC
LIMIT 1
`

type GetValidConditionRecordParams struct {
	TenantID        int64              `json:"tenant_id"`
	ConditionTypeID int64              `json:"condition_type_id"`
	ValidFrom       pgtype.Timestamptz `json:"valid_from"`
	SupplierID      pgtype.Int8        `json:"supplier_id"`
	ProductID       pgtype.Int8        `json:"product_id"`
	SiteID          pgtype.Int8        `json:"site_id"`
}

func (q *Queries) GetValidConditionRecord(ctx context.Context, arg GetValidConditionRecordParams) (PricingConditionRecord, error) {
	row := q.db.QueryRow(ctx, getValidConditionRecord,
		arg.TenantID,
		arg.ConditionTypeID,
		arg.ValidFrom,
		arg.SupplierID,
		arg.ProductID,
		arg.SiteID,
	)
	var i PricingConditionRecord
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.PublicID,
		&i.ConditionTypeID,
		&i.SupplierID,
		&i.ProductID,
		&i.SiteID,
		&i.PurchasingOrg,
		&i.ValidFrom,
		&i.ValidTo,
		&i.RateAmount,
		&i.Currency,
		&i.PricingUnit,
		&i.Uom,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listConditionTypes = `-- name: ListConditionTypes :many
SELECT id, tenant_id, code, name, condition_class, calculation_type, plus_minus, base_step, is_active, access_sequence_id FROM condition_types 
WHERE tenant_id = $1 AND is_active = true
ORDER BY code ASC
`

func (q *Queries) ListConditionTypes(ctx context.Context, tenantID int64) ([]ConditionType, error) {
	rows, err := q.db.Query(ctx, listConditionTypes, tenantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ConditionType{}
	for rows.Next() {
		var i ConditionType
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.Code,
			&i.Name,
			&i.ConditionClass,
			&i.CalculationType,
			&i.PlusMinus,
			&i.BaseStep,
			&i.IsActive,
			&i.AccessSequenceID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updatePurchasingInfoRecord = `-- name: UpdatePurchasingInfoRecord :one
UPDATE purchasing_info_records
SET
    supplier_material_num = $3,
    planned_delivery_time_days = $4,
    standard_qty = $5,
    minimum_qty = $6,
    max_order_quantity = $7,
    overdelivery_tolerance_pct = $8,
    underdelivery_tolerance_pct = $9,
    auto_approve_below = $10,
    requires_quotation = $11,
    net_price = $12,
    currency = $13,
    per_quantity = $14,
    per_unit = $15,
    valid_from = $16,
    valid_to = $17,
    is_active = $18,
    updated_at = now()
WHERE id = $1 AND tenant_id = $2
RETURNING id, tenant_id, public_id, info_record_number, supplier_id, product_id, site_id, purchasing_org, supplier_material_num, planned_delivery_time_days, standard_qty, minimum_qty, max_order_quantity, overdelivery_tolerance_pct, underdelivery_tolerance_pct, auto_approve_below, requires_quotation, net_price, currency, per_quantity, per_unit, valid_from, valid_to, is_active, created_at, updated_at
`

type UpdatePurchasingInfoRecordParams struct {
	ID                        int64          `json:"id"`
	TenantID                  int64          `json:"tenant_id"`
	SupplierMaterialNum       pgtype.Text    `json:"supplier_material_num"`
	PlannedDeliveryTimeDays   pgtype.Int4    `json:"planned_delivery_time_days"`
	StandardQty               pgtype.Numeric `json:"standard_qty"`
	MinimumQty                pgtype.Numeric `json:"minimum_qty"`
	MaxOrderQuantity          pgtype.Numeric `json:"max_order_quantity"`
	OverdeliveryTolerancePct  pgtype.Numeric `json:"overdelivery_tolerance_pct"`
	UnderdeliveryTolerancePct pgtype.Numeric `json:"underdelivery_tolerance_pct"`
	AutoApproveBelow          pgtype.Numeric `json:"auto_approve_below"`
	RequiresQuotation         bool           `json:"requires_quotation"`
	NetPrice                  pgtype.Numeric `json:"net_price"`
	Currency                  pgtype.Text    `json:"currency"`
	PerQuantity               pgtype.Numeric `json:"per_quantity"`
	PerUnit                   pgtype.Text    `json:"per_unit"`
	ValidFrom                 pgtype.Date    `json:"valid_from"`
	ValidTo                   pgtype.Date    `json:"valid_to"`
	IsActive                  bool           `json:"is_active"`
}

func (q *Queries) UpdatePurchasingInfoRecord(ctx context.Context, arg UpdatePurchasingInfoRecordParams) (PurchasingInfoRecord, error) {
	row := q.db.QueryRow(ctx, updatePurchasingInfoRecord,
		arg.ID,
		arg.TenantID,
		arg.SupplierMaterialNum,
		arg.PlannedDeliveryTimeDays,
		arg.StandardQty,
		arg.MinimumQty,
		arg.MaxOrderQuantity,
		arg.OverdeliveryTolerancePct,
		arg.UnderdeliveryTolerancePct,
		arg.AutoApproveBelow,
		arg.RequiresQuotation,
		arg.NetPrice,
		arg.Currency,
		arg.PerQuantity,
		arg.PerUnit,
		arg.ValidFrom,
		arg.ValidTo,
		arg.IsActive,
	)
	var i PurchasingInfoRecord
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.PublicID,
		&i.InfoRecordNumber,
		&i.SupplierID,
		&i.ProductID,
		&i.SiteID,
		&i.PurchasingOrg,
		&i.SupplierMaterialNum,
		&i.PlannedDeliveryTimeDays,
		&i.StandardQty,
		&i.MinimumQty,
		&i.MaxOrderQuantity,
		&i.OverdeliveryTolerancePct,
		&i.UnderdeliveryTolerancePct,
		&i.AutoApproveBelow,
		&i.RequiresQuotation,
		&i.NetPrice,
		&i.Currency,
		&i.PerQuantity,
		&i.PerUnit,
		&i.ValidFrom,
		&i.ValidTo,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
