// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0
// source: purchasing.sql

package dbgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createPurchaseOrder = `-- name: CreatePurchaseOrder :one
INSERT INTO purchase_orders (
  tenant_id, po_number, supplier_id, pr_id, status, currency, total_value, expected_delivery_date, notes, created_by, approved_by, approved_at,
  purchasing_org, purchasing_group, company_code, exchange_rate, payment_terms_days, incoterms, incoterms_location,
  goods_receipt_expected, invoice_expected, total_net_value, total_tax, total_gross_value, 
  rfq_id, supplier_ref, delivery_address, decision_factor, pricing_breakdown
) VALUES (
  $1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15, $16, $17, $18, $19, $20, $21, $22, $23, $24, $25, $26, $27, $28, $29
) RETURNING id, public_id, tenant_id, po_number, supplier_id, pr_id, status, currency, total_value, expected_delivery_date, notes, created_by, approved_by, approved_at, created_at, updated_at, document_type, document_date, posting_date, supplier_name_snapshot, purchasing_org, purchasing_group, company_code, exchange_rate, payment_terms_days, incoterms, incoterms_location, goods_receipt_expected, invoice_expected, total_net_value, total_tax, total_gross_value, rejection_reason, rejected_at, rejected_by, rfq_id, supplier_ref, delivery_address, decision_factor, pricing_breakdown
`

type CreatePurchaseOrderParams struct {
	TenantID             int64              `json:"tenant_id"`
	PoNumber             string             `json:"po_number"`
	SupplierID           int64              `json:"supplier_id"`
	PrID                 pgtype.Int8        `json:"pr_id"`
	Status               string             `json:"status"`
	Currency             string             `json:"currency"`
	TotalValue           pgtype.Numeric     `json:"total_value"`
	ExpectedDeliveryDate pgtype.Date        `json:"expected_delivery_date"`
	Notes                pgtype.Text        `json:"notes"`
	CreatedBy            pgtype.Int8        `json:"created_by"`
	ApprovedBy           pgtype.Int8        `json:"approved_by"`
	ApprovedAt           pgtype.Timestamptz `json:"approved_at"`
	PurchasingOrg        pgtype.Text        `json:"purchasing_org"`
	PurchasingGroup      pgtype.Text        `json:"purchasing_group"`
	CompanyCode          pgtype.Text        `json:"company_code"`
	ExchangeRate         pgtype.Numeric     `json:"exchange_rate"`
	PaymentTermsDays     pgtype.Int4        `json:"payment_terms_days"`
	Incoterms            pgtype.Text        `json:"incoterms"`
	IncotermsLocation    pgtype.Text        `json:"incoterms_location"`
	GoodsReceiptExpected bool               `json:"goods_receipt_expected"`
	InvoiceExpected      bool               `json:"invoice_expected"`
	TotalNetValue        pgtype.Numeric     `json:"total_net_value"`
	TotalTax             pgtype.Numeric     `json:"total_tax"`
	TotalGrossValue      pgtype.Numeric     `json:"total_gross_value"`
	RfqID                pgtype.Int8        `json:"rfq_id"`
	SupplierRef          pgtype.Text        `json:"supplier_ref"`
	DeliveryAddress      pgtype.Text        `json:"delivery_address"`
	DecisionFactor       pgtype.Text        `json:"decision_factor"`
	PricingBreakdown     []byte             `json:"pricing_breakdown"`
}

func (q *Queries) CreatePurchaseOrder(ctx context.Context, arg CreatePurchaseOrderParams) (PurchaseOrder, error) {
	row := q.db.QueryRow(ctx, createPurchaseOrder,
		arg.TenantID,
		arg.PoNumber,
		arg.SupplierID,
		arg.PrID,
		arg.Status,
		arg.Currency,
		arg.TotalValue,
		arg.ExpectedDeliveryDate,
		arg.Notes,
		arg.CreatedBy,
		arg.ApprovedBy,
		arg.ApprovedAt,
		arg.PurchasingOrg,
		arg.PurchasingGroup,
		arg.CompanyCode,
		arg.ExchangeRate,
		arg.PaymentTermsDays,
		arg.Incoterms,
		arg.IncotermsLocation,
		arg.GoodsReceiptExpected,
		arg.InvoiceExpected,
		arg.TotalNetValue,
		arg.TotalTax,
		arg.TotalGrossValue,
		arg.RfqID,
		arg.SupplierRef,
		arg.DeliveryAddress,
		arg.DecisionFactor,
		arg.PricingBreakdown,
	)
	var i PurchaseOrder
	err := row.Scan(
		&i.ID,
		&i.PublicID,
		&i.TenantID,
		&i.PoNumber,
		&i.SupplierID,
		&i.PrID,
		&i.Status,
		&i.Currency,
		&i.TotalValue,
		&i.ExpectedDeliveryDate,
		&i.Notes,
		&i.CreatedBy,
		&i.ApprovedBy,
		&i.ApprovedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DocumentType,
		&i.DocumentDate,
		&i.PostingDate,
		&i.SupplierNameSnapshot,
		&i.PurchasingOrg,
		&i.PurchasingGroup,
		&i.CompanyCode,
		&i.ExchangeRate,
		&i.PaymentTermsDays,
		&i.Incoterms,
		&i.IncotermsLocation,
		&i.GoodsReceiptExpected,
		&i.InvoiceExpected,
		&i.TotalNetValue,
		&i.TotalTax,
		&i.TotalGrossValue,
		&i.RejectionReason,
		&i.RejectedAt,
		&i.RejectedBy,
		&i.RfqID,
		&i.SupplierRef,
		&i.DeliveryAddress,
		&i.DecisionFactor,
		&i.PricingBreakdown,
	)
	return i, err
}

const createPurchaseOrderLine = `-- name: CreatePurchaseOrderLine :exec
INSERT INTO purchase_order_lines (
  tenant_id, po_id, product_id, quantity, unit, unit_price
) VALUES (
  $1, $2, $3, $4, $5, $6
)
`

type CreatePurchaseOrderLineParams struct {
	TenantID  int64          `json:"tenant_id"`
	PoID      int64          `json:"po_id"`
	ProductID int64          `json:"product_id"`
	Quantity  pgtype.Numeric `json:"quantity"`
	Unit      string         `json:"unit"`
	UnitPrice pgtype.Numeric `json:"unit_price"`
}

func (q *Queries) CreatePurchaseOrderLine(ctx context.Context, arg CreatePurchaseOrderLineParams) error {
	_, err := q.db.Exec(ctx, createPurchaseOrderLine,
		arg.TenantID,
		arg.PoID,
		arg.ProductID,
		arg.Quantity,
		arg.Unit,
		arg.UnitPrice,
	)
	return err
}

const createPurchaseRequest = `-- name: CreatePurchaseRequest :one
INSERT INTO purchase_requests (
  tenant_id, pr_number, status, required_by_date, notes, created_by,
  purchasing_group, cost_centre, priority, reference_doc, 
  decision_factor, pricing_breakdown
) VALUES (
  $1, $2, 'DRAFT', $3, $4, $5, $6, $7, $8, $9, $10, $11
) RETURNING id, public_id, tenant_id, pr_number, status, required_by_date, notes, created_by, approved_by, approved_at, created_at, updated_at, document_date, posting_date, purchasing_group, cost_centre, priority, reference_doc, rejection_reason, rejection_at, rejected_by, converted_to_po_id, converted_at, decision_factor, pricing_breakdown
`

type CreatePurchaseRequestParams struct {
	TenantID         int64       `json:"tenant_id"`
	PrNumber         string      `json:"pr_number"`
	RequiredByDate   pgtype.Date `json:"required_by_date"`
	Notes            pgtype.Text `json:"notes"`
	CreatedBy        pgtype.Int8 `json:"created_by"`
	PurchasingGroup  pgtype.Text `json:"purchasing_group"`
	CostCentre       pgtype.Text `json:"cost_centre"`
	Priority         string      `json:"priority"`
	ReferenceDoc     pgtype.Text `json:"reference_doc"`
	DecisionFactor   pgtype.Text `json:"decision_factor"`
	PricingBreakdown []byte      `json:"pricing_breakdown"`
}

func (q *Queries) CreatePurchaseRequest(ctx context.Context, arg CreatePurchaseRequestParams) (PurchaseRequest, error) {
	row := q.db.QueryRow(ctx, createPurchaseRequest,
		arg.TenantID,
		arg.PrNumber,
		arg.RequiredByDate,
		arg.Notes,
		arg.CreatedBy,
		arg.PurchasingGroup,
		arg.CostCentre,
		arg.Priority,
		arg.ReferenceDoc,
		arg.DecisionFactor,
		arg.PricingBreakdown,
	)
	var i PurchaseRequest
	err := row.Scan(
		&i.ID,
		&i.PublicID,
		&i.TenantID,
		&i.PrNumber,
		&i.Status,
		&i.RequiredByDate,
		&i.Notes,
		&i.CreatedBy,
		&i.ApprovedBy,
		&i.ApprovedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DocumentDate,
		&i.PostingDate,
		&i.PurchasingGroup,
		&i.CostCentre,
		&i.Priority,
		&i.ReferenceDoc,
		&i.RejectionReason,
		&i.RejectionAt,
		&i.RejectedBy,
		&i.ConvertedToPoID,
		&i.ConvertedAt,
		&i.DecisionFactor,
		&i.PricingBreakdown,
	)
	return i, err
}

const createPurchaseRequestLine = `-- name: CreatePurchaseRequestLine :exec
INSERT INTO purchase_request_lines (
  tenant_id, pr_id, product_id, quantity, unit, estimated_price
) VALUES (
  $1, $2, $3, $4, $5, $6
)
`

type CreatePurchaseRequestLineParams struct {
	TenantID       int64          `json:"tenant_id"`
	PrID           int64          `json:"pr_id"`
	ProductID      int64          `json:"product_id"`
	Quantity       pgtype.Numeric `json:"quantity"`
	Unit           string         `json:"unit"`
	EstimatedPrice pgtype.Numeric `json:"estimated_price"`
}

func (q *Queries) CreatePurchaseRequestLine(ctx context.Context, arg CreatePurchaseRequestLineParams) error {
	_, err := q.db.Exec(ctx, createPurchaseRequestLine,
		arg.TenantID,
		arg.PrID,
		arg.ProductID,
		arg.Quantity,
		arg.Unit,
		arg.EstimatedPrice,
	)
	return err
}

const createSupplier = `-- name: CreateSupplier :one
INSERT INTO suppliers (
  tenant_id, code, name, contact_name, email, phone, currency, payment_terms_days, notes
) VALUES (
  $1, $2, $3, $4, $5, $6, $7, $8, $9
) RETURNING id, public_id, tenant_id, code, name, contact_name, email, phone, currency, payment_terms_days, is_active, notes, created_at, updated_at, address_line1, address_line2, city, country, postal_code, tax_number, bank_name, bank_account, bank_sort_code, incoterms, incoterms_location, preferred_currency, credit_limit, supplier_group, rating, website, on_hold, on_hold_reason
`

type CreateSupplierParams struct {
	TenantID         int64       `json:"tenant_id"`
	Code             string      `json:"code"`
	Name             string      `json:"name"`
	ContactName      pgtype.Text `json:"contact_name"`
	Email            pgtype.Text `json:"email"`
	Phone            pgtype.Text `json:"phone"`
	Currency         string      `json:"currency"`
	PaymentTermsDays int32       `json:"payment_terms_days"`
	Notes            pgtype.Text `json:"notes"`
}

func (q *Queries) CreateSupplier(ctx context.Context, arg CreateSupplierParams) (Supplier, error) {
	row := q.db.QueryRow(ctx, createSupplier,
		arg.TenantID,
		arg.Code,
		arg.Name,
		arg.ContactName,
		arg.Email,
		arg.Phone,
		arg.Currency,
		arg.PaymentTermsDays,
		arg.Notes,
	)
	var i Supplier
	err := row.Scan(
		&i.ID,
		&i.PublicID,
		&i.TenantID,
		&i.Code,
		&i.Name,
		&i.ContactName,
		&i.Email,
		&i.Phone,
		&i.Currency,
		&i.PaymentTermsDays,
		&i.IsActive,
		&i.Notes,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.AddressLine1,
		&i.AddressLine2,
		&i.City,
		&i.Country,
		&i.PostalCode,
		&i.TaxNumber,
		&i.BankName,
		&i.BankAccount,
		&i.BankSortCode,
		&i.Incoterms,
		&i.IncotermsLocation,
		&i.PreferredCurrency,
		&i.CreditLimit,
		&i.SupplierGroup,
		&i.Rating,
		&i.Website,
		&i.OnHold,
		&i.OnHoldReason,
	)
	return i, err
}

const deactivateSupplier = `-- name: DeactivateSupplier :exec
UPDATE suppliers SET is_active = false, updated_at = now() WHERE tenant_id = $1 AND id = $2
`

type DeactivateSupplierParams struct {
	TenantID int64 `json:"tenant_id"`
	ID       int64 `json:"id"`
}

func (q *Queries) DeactivateSupplier(ctx context.Context, arg DeactivateSupplierParams) error {
	_, err := q.db.Exec(ctx, deactivateSupplier, arg.TenantID, arg.ID)
	return err
}

const getApprovalThresholds = `-- name: GetApprovalThresholds :one
SELECT flat_po_threshold, flat_pr_threshold, default_currency, approval_mode
FROM tenant_config
WHERE tenant_id = $1
`

type GetApprovalThresholdsRow struct {
	FlatPoThreshold pgtype.Numeric `json:"flat_po_threshold"`
	FlatPrThreshold pgtype.Numeric `json:"flat_pr_threshold"`
	DefaultCurrency string         `json:"default_currency"`
	ApprovalMode    string         `json:"approval_mode"`
}

func (q *Queries) GetApprovalThresholds(ctx context.Context, tenantID int64) (GetApprovalThresholdsRow, error) {
	row := q.db.QueryRow(ctx, getApprovalThresholds, tenantID)
	var i GetApprovalThresholdsRow
	err := row.Scan(
		&i.FlatPoThreshold,
		&i.FlatPrThreshold,
		&i.DefaultCurrency,
		&i.ApprovalMode,
	)
	return i, err
}

const getPurchaseOrderWithLines = `-- name: GetPurchaseOrderWithLines :many
SELECT po.id, po.public_id, po.tenant_id, po.po_number, po.supplier_id, po.pr_id, po.status, po.currency, po.total_value, po.expected_delivery_date, po.notes, po.created_by, po.approved_by, po.approved_at, po.created_at, po.updated_at, po.document_type, po.document_date, po.posting_date, po.supplier_name_snapshot, po.purchasing_org, po.purchasing_group, po.company_code, po.exchange_rate, po.payment_terms_days, po.incoterms, po.incoterms_location, po.goods_receipt_expected, po.invoice_expected, po.total_net_value, po.total_tax, po.total_gross_value, po.rejection_reason, po.rejected_at, po.rejected_by, po.rfq_id, po.supplier_ref, po.delivery_address, po.decision_factor, po.pricing_breakdown, 
       pol.id as line_id, pol.product_id, pol.quantity, pol.unit, pol.unit_price, pol.line_value, pol.qty_received, 
       pol.account_assignment_type, pol.cost_centre as cost_centre_line, pol.line_notes, pol.line_status,
       p.name as product_name, p.code as product_code, s.name as supplier_name
FROM purchase_orders po
JOIN purchase_order_lines pol ON pol.po_id = po.id
JOIN products p ON p.id = pol.product_id
JOIN suppliers s ON s.id = po.supplier_id
WHERE po.tenant_id = $1 AND po.id = $2
`

type GetPurchaseOrderWithLinesParams struct {
	TenantID int64 `json:"tenant_id"`
	ID       int64 `json:"id"`
}

type GetPurchaseOrderWithLinesRow struct {
	ID                    int64              `json:"id"`
	PublicID              pgtype.UUID        `json:"public_id"`
	TenantID              int64              `json:"tenant_id"`
	PoNumber              string             `json:"po_number"`
	SupplierID            int64              `json:"supplier_id"`
	PrID                  pgtype.Int8        `json:"pr_id"`
	Status                string             `json:"status"`
	Currency              string             `json:"currency"`
	TotalValue            pgtype.Numeric     `json:"total_value"`
	ExpectedDeliveryDate  pgtype.Date        `json:"expected_delivery_date"`
	Notes                 pgtype.Text        `json:"notes"`
	CreatedBy             pgtype.Int8        `json:"created_by"`
	ApprovedBy            pgtype.Int8        `json:"approved_by"`
	ApprovedAt            pgtype.Timestamptz `json:"approved_at"`
	CreatedAt             pgtype.Timestamptz `json:"created_at"`
	UpdatedAt             pgtype.Timestamptz `json:"updated_at"`
	DocumentType          string             `json:"document_type"`
	DocumentDate          pgtype.Date        `json:"document_date"`
	PostingDate           pgtype.Date        `json:"posting_date"`
	SupplierNameSnapshot  pgtype.Text        `json:"supplier_name_snapshot"`
	PurchasingOrg         pgtype.Text        `json:"purchasing_org"`
	PurchasingGroup       pgtype.Text        `json:"purchasing_group"`
	CompanyCode           pgtype.Text        `json:"company_code"`
	ExchangeRate          pgtype.Numeric     `json:"exchange_rate"`
	PaymentTermsDays      pgtype.Int4        `json:"payment_terms_days"`
	Incoterms             pgtype.Text        `json:"incoterms"`
	IncotermsLocation     pgtype.Text        `json:"incoterms_location"`
	GoodsReceiptExpected  bool               `json:"goods_receipt_expected"`
	InvoiceExpected       bool               `json:"invoice_expected"`
	TotalNetValue         pgtype.Numeric     `json:"total_net_value"`
	TotalTax              pgtype.Numeric     `json:"total_tax"`
	TotalGrossValue       pgtype.Numeric     `json:"total_gross_value"`
	RejectionReason       pgtype.Text        `json:"rejection_reason"`
	RejectedAt            pgtype.Timestamptz `json:"rejected_at"`
	RejectedBy            pgtype.Int8        `json:"rejected_by"`
	RfqID                 pgtype.Int8        `json:"rfq_id"`
	SupplierRef           pgtype.Text        `json:"supplier_ref"`
	DeliveryAddress       pgtype.Text        `json:"delivery_address"`
	DecisionFactor        pgtype.Text        `json:"decision_factor"`
	PricingBreakdown      []byte             `json:"pricing_breakdown"`
	LineID                int64              `json:"line_id"`
	ProductID             int64              `json:"product_id"`
	Quantity              pgtype.Numeric     `json:"quantity"`
	Unit                  string             `json:"unit"`
	UnitPrice             pgtype.Numeric     `json:"unit_price"`
	LineValue             pgtype.Numeric     `json:"line_value"`
	QtyReceived           pgtype.Numeric     `json:"qty_received"`
	AccountAssignmentType pgtype.Text        `json:"account_assignment_type"`
	CostCentreLine        pgtype.Text        `json:"cost_centre_line"`
	LineNotes             pgtype.Text        `json:"line_notes"`
	LineStatus            string             `json:"line_status"`
	ProductName           string             `json:"product_name"`
	ProductCode           string             `json:"product_code"`
	SupplierName          string             `json:"supplier_name"`
}

func (q *Queries) GetPurchaseOrderWithLines(ctx context.Context, arg GetPurchaseOrderWithLinesParams) ([]GetPurchaseOrderWithLinesRow, error) {
	rows, err := q.db.Query(ctx, getPurchaseOrderWithLines, arg.TenantID, arg.ID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetPurchaseOrderWithLinesRow{}
	for rows.Next() {
		var i GetPurchaseOrderWithLinesRow
		if err := rows.Scan(
			&i.ID,
			&i.PublicID,
			&i.TenantID,
			&i.PoNumber,
			&i.SupplierID,
			&i.PrID,
			&i.Status,
			&i.Currency,
			&i.TotalValue,
			&i.ExpectedDeliveryDate,
			&i.Notes,
			&i.CreatedBy,
			&i.ApprovedBy,
			&i.ApprovedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DocumentType,
			&i.DocumentDate,
			&i.PostingDate,
			&i.SupplierNameSnapshot,
			&i.PurchasingOrg,
			&i.PurchasingGroup,
			&i.CompanyCode,
			&i.ExchangeRate,
			&i.PaymentTermsDays,
			&i.Incoterms,
			&i.IncotermsLocation,
			&i.GoodsReceiptExpected,
			&i.InvoiceExpected,
			&i.TotalNetValue,
			&i.TotalTax,
			&i.TotalGrossValue,
			&i.RejectionReason,
			&i.RejectedAt,
			&i.RejectedBy,
			&i.RfqID,
			&i.SupplierRef,
			&i.DeliveryAddress,
			&i.DecisionFactor,
			&i.PricingBreakdown,
			&i.LineID,
			&i.ProductID,
			&i.Quantity,
			&i.Unit,
			&i.UnitPrice,
			&i.LineValue,
			&i.QtyReceived,
			&i.AccountAssignmentType,
			&i.CostCentreLine,
			&i.LineNotes,
			&i.LineStatus,
			&i.ProductName,
			&i.ProductCode,
			&i.SupplierName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getPurchaseRequestWithLines = `-- name: GetPurchaseRequestWithLines :many
SELECT pr.id, pr.public_id, pr.tenant_id, pr.pr_number, pr.status, pr.required_by_date, pr.notes, pr.created_by, pr.approved_by, pr.approved_at, pr.created_at, pr.updated_at, pr.document_date, pr.posting_date, pr.purchasing_group, pr.cost_centre, pr.priority, pr.reference_doc, pr.rejection_reason, pr.rejection_at, pr.rejected_by, pr.converted_to_po_id, pr.converted_at, pr.decision_factor, pr.pricing_breakdown, 
       prl.product_id, prl.quantity, prl.unit, prl.estimated_price, 
       prl.preferred_supplier_id,
       prl.account_assignment_type, prl.cost_centre as cost_centre_line, prl.line_notes, prl.line_status,
       p.name as product_name, p.code as product_code
FROM purchase_requests pr
JOIN purchase_request_lines prl ON prl.pr_id = pr.id
JOIN products p ON p.id = prl.product_id
WHERE pr.tenant_id = $1 AND pr.id = $2
`

type GetPurchaseRequestWithLinesParams struct {
	TenantID int64 `json:"tenant_id"`
	ID       int64 `json:"id"`
}

type GetPurchaseRequestWithLinesRow struct {
	ID                    int64              `json:"id"`
	PublicID              pgtype.UUID        `json:"public_id"`
	TenantID              int64              `json:"tenant_id"`
	PrNumber              string             `json:"pr_number"`
	Status                string             `json:"status"`
	RequiredByDate        pgtype.Date        `json:"required_by_date"`
	Notes                 pgtype.Text        `json:"notes"`
	CreatedBy             pgtype.Int8        `json:"created_by"`
	ApprovedBy            pgtype.Int8        `json:"approved_by"`
	ApprovedAt            pgtype.Timestamptz `json:"approved_at"`
	CreatedAt             pgtype.Timestamptz `json:"created_at"`
	UpdatedAt             pgtype.Timestamptz `json:"updated_at"`
	DocumentDate          pgtype.Date        `json:"document_date"`
	PostingDate           pgtype.Date        `json:"posting_date"`
	PurchasingGroup       pgtype.Text        `json:"purchasing_group"`
	CostCentre            pgtype.Text        `json:"cost_centre"`
	Priority              string             `json:"priority"`
	ReferenceDoc          pgtype.Text        `json:"reference_doc"`
	RejectionReason       pgtype.Text        `json:"rejection_reason"`
	RejectionAt           pgtype.Timestamptz `json:"rejection_at"`
	RejectedBy            pgtype.Int8        `json:"rejected_by"`
	ConvertedToPoID       pgtype.Int8        `json:"converted_to_po_id"`
	ConvertedAt           pgtype.Timestamptz `json:"converted_at"`
	DecisionFactor        pgtype.Text        `json:"decision_factor"`
	PricingBreakdown      []byte             `json:"pricing_breakdown"`
	ProductID             int64              `json:"product_id"`
	Quantity              pgtype.Numeric     `json:"quantity"`
	Unit                  string             `json:"unit"`
	EstimatedPrice        pgtype.Numeric     `json:"estimated_price"`
	PreferredSupplierID   pgtype.Int8        `json:"preferred_supplier_id"`
	AccountAssignmentType pgtype.Text        `json:"account_assignment_type"`
	CostCentreLine        pgtype.Text        `json:"cost_centre_line"`
	LineNotes             pgtype.Text        `json:"line_notes"`
	LineStatus            string             `json:"line_status"`
	ProductName           string             `json:"product_name"`
	ProductCode           string             `json:"product_code"`
}

func (q *Queries) GetPurchaseRequestWithLines(ctx context.Context, arg GetPurchaseRequestWithLinesParams) ([]GetPurchaseRequestWithLinesRow, error) {
	rows, err := q.db.Query(ctx, getPurchaseRequestWithLines, arg.TenantID, arg.ID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetPurchaseRequestWithLinesRow{}
	for rows.Next() {
		var i GetPurchaseRequestWithLinesRow
		if err := rows.Scan(
			&i.ID,
			&i.PublicID,
			&i.TenantID,
			&i.PrNumber,
			&i.Status,
			&i.RequiredByDate,
			&i.Notes,
			&i.CreatedBy,
			&i.ApprovedBy,
			&i.ApprovedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DocumentDate,
			&i.PostingDate,
			&i.PurchasingGroup,
			&i.CostCentre,
			&i.Priority,
			&i.ReferenceDoc,
			&i.RejectionReason,
			&i.RejectionAt,
			&i.RejectedBy,
			&i.ConvertedToPoID,
			&i.ConvertedAt,
			&i.DecisionFactor,
			&i.PricingBreakdown,
			&i.ProductID,
			&i.Quantity,
			&i.Unit,
			&i.EstimatedPrice,
			&i.PreferredSupplierID,
			&i.AccountAssignmentType,
			&i.CostCentreLine,
			&i.LineNotes,
			&i.LineStatus,
			&i.ProductName,
			&i.ProductCode,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getSupplierByCode = `-- name: GetSupplierByCode :one
SELECT id, public_id, tenant_id, code, name, contact_name, email, phone, currency, payment_terms_days, is_active, notes, created_at, updated_at, address_line1, address_line2, city, country, postal_code, tax_number, bank_name, bank_account, bank_sort_code, incoterms, incoterms_location, preferred_currency, credit_limit, supplier_group, rating, website, on_hold, on_hold_reason FROM suppliers WHERE tenant_id = $1 AND code = $2
`

type GetSupplierByCodeParams struct {
	TenantID int64  `json:"tenant_id"`
	Code     string `json:"code"`
}

func (q *Queries) GetSupplierByCode(ctx context.Context, arg GetSupplierByCodeParams) (Supplier, error) {
	row := q.db.QueryRow(ctx, getSupplierByCode, arg.TenantID, arg.Code)
	var i Supplier
	err := row.Scan(
		&i.ID,
		&i.PublicID,
		&i.TenantID,
		&i.Code,
		&i.Name,
		&i.ContactName,
		&i.Email,
		&i.Phone,
		&i.Currency,
		&i.PaymentTermsDays,
		&i.IsActive,
		&i.Notes,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.AddressLine1,
		&i.AddressLine2,
		&i.City,
		&i.Country,
		&i.PostalCode,
		&i.TaxNumber,
		&i.BankName,
		&i.BankAccount,
		&i.BankSortCode,
		&i.Incoterms,
		&i.IncotermsLocation,
		&i.PreferredCurrency,
		&i.CreditLimit,
		&i.SupplierGroup,
		&i.Rating,
		&i.Website,
		&i.OnHold,
		&i.OnHoldReason,
	)
	return i, err
}

const listPurchaseOrders = `-- name: ListPurchaseOrders :many
SELECT po.id, po.public_id, po.tenant_id, po.po_number, po.supplier_id, po.pr_id, po.status, po.currency, po.total_value, po.expected_delivery_date, po.notes, po.created_by, po.approved_by, po.approved_at, po.created_at, po.updated_at, po.document_type, po.document_date, po.posting_date, po.supplier_name_snapshot, po.purchasing_org, po.purchasing_group, po.company_code, po.exchange_rate, po.payment_terms_days, po.incoterms, po.incoterms_location, po.goods_receipt_expected, po.invoice_expected, po.total_net_value, po.total_tax, po.total_gross_value, po.rejection_reason, po.rejected_at, po.rejected_by, po.rfq_id, po.supplier_ref, po.delivery_address, po.decision_factor, po.pricing_breakdown, s.name as supplier_name, s.code as supplier_code
FROM purchase_orders po
JOIN suppliers s ON s.id = po.supplier_id
WHERE po.tenant_id = $1 AND ($2::text = '' OR po.status = $2)
ORDER BY po.created_at DESC
`

type ListPurchaseOrdersParams struct {
	TenantID int64  `json:"tenant_id"`
	Column2  string `json:"column_2"`
}

type ListPurchaseOrdersRow struct {
	ID                   int64              `json:"id"`
	PublicID             pgtype.UUID        `json:"public_id"`
	TenantID             int64              `json:"tenant_id"`
	PoNumber             string             `json:"po_number"`
	SupplierID           int64              `json:"supplier_id"`
	PrID                 pgtype.Int8        `json:"pr_id"`
	Status               string             `json:"status"`
	Currency             string             `json:"currency"`
	TotalValue           pgtype.Numeric     `json:"total_value"`
	ExpectedDeliveryDate pgtype.Date        `json:"expected_delivery_date"`
	Notes                pgtype.Text        `json:"notes"`
	CreatedBy            pgtype.Int8        `json:"created_by"`
	ApprovedBy           pgtype.Int8        `json:"approved_by"`
	ApprovedAt           pgtype.Timestamptz `json:"approved_at"`
	CreatedAt            pgtype.Timestamptz `json:"created_at"`
	UpdatedAt            pgtype.Timestamptz `json:"updated_at"`
	DocumentType         string             `json:"document_type"`
	DocumentDate         pgtype.Date        `json:"document_date"`
	PostingDate          pgtype.Date        `json:"posting_date"`
	SupplierNameSnapshot pgtype.Text        `json:"supplier_name_snapshot"`
	PurchasingOrg        pgtype.Text        `json:"purchasing_org"`
	PurchasingGroup      pgtype.Text        `json:"purchasing_group"`
	CompanyCode          pgtype.Text        `json:"company_code"`
	ExchangeRate         pgtype.Numeric     `json:"exchange_rate"`
	PaymentTermsDays     pgtype.Int4        `json:"payment_terms_days"`
	Incoterms            pgtype.Text        `json:"incoterms"`
	IncotermsLocation    pgtype.Text        `json:"incoterms_location"`
	GoodsReceiptExpected bool               `json:"goods_receipt_expected"`
	InvoiceExpected      bool               `json:"invoice_expected"`
	TotalNetValue        pgtype.Numeric     `json:"total_net_value"`
	TotalTax             pgtype.Numeric     `json:"total_tax"`
	TotalGrossValue      pgtype.Numeric     `json:"total_gross_value"`
	RejectionReason      pgtype.Text        `json:"rejection_reason"`
	RejectedAt           pgtype.Timestamptz `json:"rejected_at"`
	RejectedBy           pgtype.Int8        `json:"rejected_by"`
	RfqID                pgtype.Int8        `json:"rfq_id"`
	SupplierRef          pgtype.Text        `json:"supplier_ref"`
	DeliveryAddress      pgtype.Text        `json:"delivery_address"`
	DecisionFactor       pgtype.Text        `json:"decision_factor"`
	PricingBreakdown     []byte             `json:"pricing_breakdown"`
	SupplierName         string             `json:"supplier_name"`
	SupplierCode         string             `json:"supplier_code"`
}

func (q *Queries) ListPurchaseOrders(ctx context.Context, arg ListPurchaseOrdersParams) ([]ListPurchaseOrdersRow, error) {
	rows, err := q.db.Query(ctx, listPurchaseOrders, arg.TenantID, arg.Column2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListPurchaseOrdersRow{}
	for rows.Next() {
		var i ListPurchaseOrdersRow
		if err := rows.Scan(
			&i.ID,
			&i.PublicID,
			&i.TenantID,
			&i.PoNumber,
			&i.SupplierID,
			&i.PrID,
			&i.Status,
			&i.Currency,
			&i.TotalValue,
			&i.ExpectedDeliveryDate,
			&i.Notes,
			&i.CreatedBy,
			&i.ApprovedBy,
			&i.ApprovedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DocumentType,
			&i.DocumentDate,
			&i.PostingDate,
			&i.SupplierNameSnapshot,
			&i.PurchasingOrg,
			&i.PurchasingGroup,
			&i.CompanyCode,
			&i.ExchangeRate,
			&i.PaymentTermsDays,
			&i.Incoterms,
			&i.IncotermsLocation,
			&i.GoodsReceiptExpected,
			&i.InvoiceExpected,
			&i.TotalNetValue,
			&i.TotalTax,
			&i.TotalGrossValue,
			&i.RejectionReason,
			&i.RejectedAt,
			&i.RejectedBy,
			&i.RfqID,
			&i.SupplierRef,
			&i.DeliveryAddress,
			&i.DecisionFactor,
			&i.PricingBreakdown,
			&i.SupplierName,
			&i.SupplierCode,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPurchaseRequests = `-- name: ListPurchaseRequests :many
SELECT id, public_id, tenant_id, pr_number, status, required_by_date, notes, created_by, approved_by, approved_at, created_at, updated_at, document_date, posting_date, purchasing_group, cost_centre, priority, reference_doc, rejection_reason, rejection_at, rejected_by, converted_to_po_id, converted_at, decision_factor, pricing_breakdown FROM purchase_requests 
WHERE tenant_id = $1 AND ($2::text = '' OR status = $2)
ORDER BY created_at DESC
`

type ListPurchaseRequestsParams struct {
	TenantID int64  `json:"tenant_id"`
	Column2  string `json:"column_2"`
}

func (q *Queries) ListPurchaseRequests(ctx context.Context, arg ListPurchaseRequestsParams) ([]PurchaseRequest, error) {
	rows, err := q.db.Query(ctx, listPurchaseRequests, arg.TenantID, arg.Column2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []PurchaseRequest{}
	for rows.Next() {
		var i PurchaseRequest
		if err := rows.Scan(
			&i.ID,
			&i.PublicID,
			&i.TenantID,
			&i.PrNumber,
			&i.Status,
			&i.RequiredByDate,
			&i.Notes,
			&i.CreatedBy,
			&i.ApprovedBy,
			&i.ApprovedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DocumentDate,
			&i.PostingDate,
			&i.PurchasingGroup,
			&i.CostCentre,
			&i.Priority,
			&i.ReferenceDoc,
			&i.RejectionReason,
			&i.RejectionAt,
			&i.RejectedBy,
			&i.ConvertedToPoID,
			&i.ConvertedAt,
			&i.DecisionFactor,
			&i.PricingBreakdown,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSuppliers = `-- name: ListSuppliers :many
SELECT id, public_id, tenant_id, code, name, contact_name, email, phone, currency, payment_terms_days, is_active, notes, created_at, updated_at, address_line1, address_line2, city, country, postal_code, tax_number, bank_name, bank_account, bank_sort_code, incoterms, incoterms_location, preferred_currency, credit_limit, supplier_group, rating, website, on_hold, on_hold_reason FROM suppliers 
WHERE tenant_id = $1 AND is_active = true
ORDER BY code ASC
LIMIT $2 OFFSET $3
`

type ListSuppliersParams struct {
	TenantID int64 `json:"tenant_id"`
	Limit    int32 `json:"limit"`
	Offset   int32 `json:"offset"`
}

func (q *Queries) ListSuppliers(ctx context.Context, arg ListSuppliersParams) ([]Supplier, error) {
	rows, err := q.db.Query(ctx, listSuppliers, arg.TenantID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Supplier{}
	for rows.Next() {
		var i Supplier
		if err := rows.Scan(
			&i.ID,
			&i.PublicID,
			&i.TenantID,
			&i.Code,
			&i.Name,
			&i.ContactName,
			&i.Email,
			&i.Phone,
			&i.Currency,
			&i.PaymentTermsDays,
			&i.IsActive,
			&i.Notes,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.AddressLine1,
			&i.AddressLine2,
			&i.City,
			&i.Country,
			&i.PostalCode,
			&i.TaxNumber,
			&i.BankName,
			&i.BankAccount,
			&i.BankSortCode,
			&i.Incoterms,
			&i.IncotermsLocation,
			&i.PreferredCurrency,
			&i.CreditLimit,
			&i.SupplierGroup,
			&i.Rating,
			&i.Website,
			&i.OnHold,
			&i.OnHoldReason,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updatePurchaseOrderLineReceived = `-- name: UpdatePurchaseOrderLineReceived :exec
UPDATE purchase_order_lines
SET qty_received = qty_received + $3
WHERE tenant_id = $1 AND id = $2
`

type UpdatePurchaseOrderLineReceivedParams struct {
	TenantID    int64          `json:"tenant_id"`
	ID          int64          `json:"id"`
	QtyReceived pgtype.Numeric `json:"qty_received"`
}

func (q *Queries) UpdatePurchaseOrderLineReceived(ctx context.Context, arg UpdatePurchaseOrderLineReceivedParams) error {
	_, err := q.db.Exec(ctx, updatePurchaseOrderLineReceived, arg.TenantID, arg.ID, arg.QtyReceived)
	return err
}

const updatePurchaseOrderStatus = `-- name: UpdatePurchaseOrderStatus :exec
UPDATE purchase_orders
SET status = $3, updated_at = now()
WHERE tenant_id = $1 AND id = $2
`

type UpdatePurchaseOrderStatusParams struct {
	TenantID int64  `json:"tenant_id"`
	ID       int64  `json:"id"`
	Status   string `json:"status"`
}

func (q *Queries) UpdatePurchaseOrderStatus(ctx context.Context, arg UpdatePurchaseOrderStatusParams) error {
	_, err := q.db.Exec(ctx, updatePurchaseOrderStatus, arg.TenantID, arg.ID, arg.Status)
	return err
}

const updatePurchaseRequestStatus = `-- name: UpdatePurchaseRequestStatus :exec
UPDATE purchase_requests 
SET status = $3, approved_by = $4, approved_at = CASE WHEN $3 = 'APPROVED' THEN now() ELSE approved_at END, updated_at = now()
WHERE tenant_id = $1 AND id = $2
`

type UpdatePurchaseRequestStatusParams struct {
	TenantID   int64       `json:"tenant_id"`
	ID         int64       `json:"id"`
	Status     string      `json:"status"`
	ApprovedBy pgtype.Int8 `json:"approved_by"`
}

func (q *Queries) UpdatePurchaseRequestStatus(ctx context.Context, arg UpdatePurchaseRequestStatusParams) error {
	_, err := q.db.Exec(ctx, updatePurchaseRequestStatus,
		arg.TenantID,
		arg.ID,
		arg.Status,
		arg.ApprovedBy,
	)
	return err
}

const updateSupplier = `-- name: UpdateSupplier :one
UPDATE suppliers 
SET name = $3, contact_name = $4, email = $5, phone = $6, currency = $7, payment_terms_days = $8, notes = $9, updated_at = now()
WHERE tenant_id = $1 AND id = $2
RETURNING id, public_id, tenant_id, code, name, contact_name, email, phone, currency, payment_terms_days, is_active, notes, created_at, updated_at, address_line1, address_line2, city, country, postal_code, tax_number, bank_name, bank_account, bank_sort_code, incoterms, incoterms_location, preferred_currency, credit_limit, supplier_group, rating, website, on_hold, on_hold_reason
`

type UpdateSupplierParams struct {
	TenantID         int64       `json:"tenant_id"`
	ID               int64       `json:"id"`
	Name             string      `json:"name"`
	ContactName      pgtype.Text `json:"contact_name"`
	Email            pgtype.Text `json:"email"`
	Phone            pgtype.Text `json:"phone"`
	Currency         string      `json:"currency"`
	PaymentTermsDays int32       `json:"payment_terms_days"`
	Notes            pgtype.Text `json:"notes"`
}

func (q *Queries) UpdateSupplier(ctx context.Context, arg UpdateSupplierParams) (Supplier, error) {
	row := q.db.QueryRow(ctx, updateSupplier,
		arg.TenantID,
		arg.ID,
		arg.Name,
		arg.ContactName,
		arg.Email,
		arg.Phone,
		arg.Currency,
		arg.PaymentTermsDays,
		arg.Notes,
	)
	var i Supplier
	err := row.Scan(
		&i.ID,
		&i.PublicID,
		&i.TenantID,
		&i.Code,
		&i.Name,
		&i.ContactName,
		&i.Email,
		&i.Phone,
		&i.Currency,
		&i.PaymentTermsDays,
		&i.IsActive,
		&i.Notes,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.AddressLine1,
		&i.AddressLine2,
		&i.City,
		&i.Country,
		&i.PostalCode,
		&i.TaxNumber,
		&i.BankName,
		&i.BankAccount,
		&i.BankSortCode,
		&i.Incoterms,
		&i.IncotermsLocation,
		&i.PreferredCurrency,
		&i.CreditLimit,
		&i.SupplierGroup,
		&i.Rating,
		&i.Website,
		&i.OnHold,
		&i.OnHoldReason,
	)
	return i, err
}
