// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: quality_checks.sql

package dbgen

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const addQCFinding = `-- name: AddQCFinding :one
INSERT INTO quality_check_findings (
    quality_check_id, finding_number,
    finding_type, severity, description,
    quantity_affected
) VALUES (
    $1,
    (SELECT COALESCE(MAX(finding_number),0)+1
     FROM quality_check_findings
     WHERE quality_check_id = $1),
    $2, $3, $4, $5
)
RETURNING id, public_id, quality_check_id, finding_number, finding_type, severity, description, quantity_affected, is_resolved, resolution_notes, created_at
`

type AddQCFindingParams struct {
	QualityCheckID   int64          `json:"quality_check_id"`
	FindingType      string         `json:"finding_type"`
	Severity         string         `json:"severity"`
	Description      string         `json:"description"`
	QuantityAffected pgtype.Numeric `json:"quantity_affected"`
}

func (q *Queries) AddQCFinding(ctx context.Context, arg AddQCFindingParams) (QualityCheckFinding, error) {
	row := q.db.QueryRow(ctx, addQCFinding,
		arg.QualityCheckID,
		arg.FindingType,
		arg.Severity,
		arg.Description,
		arg.QuantityAffected,
	)
	var i QualityCheckFinding
	err := row.Scan(
		&i.ID,
		&i.PublicID,
		&i.QualityCheckID,
		&i.FindingNumber,
		&i.FindingType,
		&i.Severity,
		&i.Description,
		&i.QuantityAffected,
		&i.IsResolved,
		&i.ResolutionNotes,
		&i.CreatedAt,
	)
	return i, err
}

const createQualityCheck = `-- name: CreateQualityCheck :one
INSERT INTO quality_checks (
    tenant_id, reference_type, reference_id, reference_code,
    supplier_id, material_id, inspect_qty, unit_of_measure,
    notes, created_by
) VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10)
RETURNING id, public_id, tenant_id, qc_number, reference_type, reference_id, reference_code, supplier_id, material_id, inspect_qty, passed_qty, failed_qty, unit_of_measure, status, result, accepted_zone_id, rejected_zone_id, inspector_id, notes, started_at, completed_at, created_by, created_at, updated_at
`

type CreateQualityCheckParams struct {
	TenantID      int64          `json:"tenant_id"`
	ReferenceType string         `json:"reference_type"`
	ReferenceID   pgtype.Int8    `json:"reference_id"`
	ReferenceCode pgtype.Text    `json:"reference_code"`
	SupplierID    pgtype.Int8    `json:"supplier_id"`
	MaterialID    pgtype.Int8    `json:"material_id"`
	InspectQty    pgtype.Numeric `json:"inspect_qty"`
	UnitOfMeasure pgtype.Text    `json:"unit_of_measure"`
	Notes         pgtype.Text    `json:"notes"`
	CreatedBy     pgtype.Int8    `json:"created_by"`
}

func (q *Queries) CreateQualityCheck(ctx context.Context, arg CreateQualityCheckParams) (QualityCheck, error) {
	row := q.db.QueryRow(ctx, createQualityCheck,
		arg.TenantID,
		arg.ReferenceType,
		arg.ReferenceID,
		arg.ReferenceCode,
		arg.SupplierID,
		arg.MaterialID,
		arg.InspectQty,
		arg.UnitOfMeasure,
		arg.Notes,
		arg.CreatedBy,
	)
	var i QualityCheck
	err := row.Scan(
		&i.ID,
		&i.PublicID,
		&i.TenantID,
		&i.QcNumber,
		&i.ReferenceType,
		&i.ReferenceID,
		&i.ReferenceCode,
		&i.SupplierID,
		&i.MaterialID,
		&i.InspectQty,
		&i.PassedQty,
		&i.FailedQty,
		&i.UnitOfMeasure,
		&i.Status,
		&i.Result,
		&i.AcceptedZoneID,
		&i.RejectedZoneID,
		&i.InspectorID,
		&i.Notes,
		&i.StartedAt,
		&i.CompletedAt,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getQCFindings = `-- name: GetQCFindings :many
SELECT id, public_id, quality_check_id, finding_number, finding_type, severity, description, quantity_affected, is_resolved, resolution_notes, created_at FROM quality_check_findings
WHERE quality_check_id = $1
ORDER BY finding_number
`

func (q *Queries) GetQCFindings(ctx context.Context, qualityCheckID int64) ([]QualityCheckFinding, error) {
	rows, err := q.db.Query(ctx, getQCFindings, qualityCheckID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []QualityCheckFinding{}
	for rows.Next() {
		var i QualityCheckFinding
		if err := rows.Scan(
			&i.ID,
			&i.PublicID,
			&i.QualityCheckID,
			&i.FindingNumber,
			&i.FindingType,
			&i.Severity,
			&i.Description,
			&i.QuantityAffected,
			&i.IsResolved,
			&i.ResolutionNotes,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getQualityCheckByPublicID = `-- name: GetQualityCheckByPublicID :one
SELECT
    qc.id, qc.public_id, qc.tenant_id, qc.qc_number, qc.reference_type, qc.reference_id, qc.reference_code, qc.supplier_id, qc.material_id, qc.inspect_qty, qc.passed_qty, qc.failed_qty, qc.unit_of_measure, qc.status, qc.result, qc.accepted_zone_id, qc.rejected_zone_id, qc.inspector_id, qc.notes, qc.started_at, qc.completed_at, qc.created_by, qc.created_at, qc.updated_at,
    s.name AS supplier_name,
    m.code AS material_code,
    m.name AS material_name
FROM quality_checks qc
LEFT JOIN suppliers s ON s.id = qc.supplier_id
LEFT JOIN products m ON m.id = qc.material_id
WHERE qc.public_id = $1 AND qc.tenant_id = $2
`

type GetQualityCheckByPublicIDParams struct {
	PublicID uuid.UUID `json:"public_id"`
	TenantID int64     `json:"tenant_id"`
}

type GetQualityCheckByPublicIDRow struct {
	ID             int64              `json:"id"`
	PublicID       uuid.UUID          `json:"public_id"`
	TenantID       int64              `json:"tenant_id"`
	QcNumber       string             `json:"qc_number"`
	ReferenceType  string             `json:"reference_type"`
	ReferenceID    pgtype.Int8        `json:"reference_id"`
	ReferenceCode  pgtype.Text        `json:"reference_code"`
	SupplierID     pgtype.Int8        `json:"supplier_id"`
	MaterialID     pgtype.Int8        `json:"material_id"`
	InspectQty     pgtype.Numeric     `json:"inspect_qty"`
	PassedQty      pgtype.Numeric     `json:"passed_qty"`
	FailedQty      pgtype.Numeric     `json:"failed_qty"`
	UnitOfMeasure  pgtype.Text        `json:"unit_of_measure"`
	Status         string             `json:"status"`
	Result         pgtype.Text        `json:"result"`
	AcceptedZoneID pgtype.Int8        `json:"accepted_zone_id"`
	RejectedZoneID pgtype.Int8        `json:"rejected_zone_id"`
	InspectorID    pgtype.Int8        `json:"inspector_id"`
	Notes          pgtype.Text        `json:"notes"`
	StartedAt      pgtype.Timestamptz `json:"started_at"`
	CompletedAt    pgtype.Timestamptz `json:"completed_at"`
	CreatedBy      pgtype.Int8        `json:"created_by"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	UpdatedAt      pgtype.Timestamptz `json:"updated_at"`
	SupplierName   pgtype.Text        `json:"supplier_name"`
	MaterialCode   pgtype.Text        `json:"material_code"`
	MaterialName   pgtype.Text        `json:"material_name"`
}

func (q *Queries) GetQualityCheckByPublicID(ctx context.Context, arg GetQualityCheckByPublicIDParams) (GetQualityCheckByPublicIDRow, error) {
	row := q.db.QueryRow(ctx, getQualityCheckByPublicID, arg.PublicID, arg.TenantID)
	var i GetQualityCheckByPublicIDRow
	err := row.Scan(
		&i.ID,
		&i.PublicID,
		&i.TenantID,
		&i.QcNumber,
		&i.ReferenceType,
		&i.ReferenceID,
		&i.ReferenceCode,
		&i.SupplierID,
		&i.MaterialID,
		&i.InspectQty,
		&i.PassedQty,
		&i.FailedQty,
		&i.UnitOfMeasure,
		&i.Status,
		&i.Result,
		&i.AcceptedZoneID,
		&i.RejectedZoneID,
		&i.InspectorID,
		&i.Notes,
		&i.StartedAt,
		&i.CompletedAt,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.SupplierName,
		&i.MaterialCode,
		&i.MaterialName,
	)
	return i, err
}

const getQualityGateDashboard = `-- name: GetQualityGateDashboard :one
SELECT
    COUNT(*)                                              AS total_checks,
    COUNT(*) FILTER (WHERE status = 'PENDING')           AS pending,
    COUNT(*) FILTER (WHERE status = 'IN_PROGRESS')       AS in_progress,
    COUNT(*) FILTER (WHERE result = 'ACCEPT')            AS passed,
    COUNT(*) FILTER (WHERE result = 'REJECT')            AS failed,
    COUNT(*) FILTER (WHERE result = 'CONDITIONAL')       AS conditional,
    ROUND(
        100.0 * COUNT(*) FILTER (WHERE result = 'ACCEPT') /
        NULLIF(COUNT(*) FILTER (WHERE result IS NOT NULL), 0)
    , 1)                                                  AS pass_rate_pct
FROM quality_checks
WHERE tenant_id = $1
  AND created_at >= NOW() - INTERVAL '90 days'
`

type GetQualityGateDashboardRow struct {
	TotalChecks int64          `json:"total_checks"`
	Pending     int64          `json:"pending"`
	InProgress  int64          `json:"in_progress"`
	Passed      int64          `json:"passed"`
	Failed      int64          `json:"failed"`
	Conditional int64          `json:"conditional"`
	PassRatePct pgtype.Numeric `json:"pass_rate_pct"`
}

func (q *Queries) GetQualityGateDashboard(ctx context.Context, tenantID int64) (GetQualityGateDashboardRow, error) {
	row := q.db.QueryRow(ctx, getQualityGateDashboard, tenantID)
	var i GetQualityGateDashboardRow
	err := row.Scan(
		&i.TotalChecks,
		&i.Pending,
		&i.InProgress,
		&i.Passed,
		&i.Failed,
		&i.Conditional,
		&i.PassRatePct,
	)
	return i, err
}

const listQualityChecks = `-- name: ListQualityChecks :many
SELECT
    qc.id, qc.public_id, qc.tenant_id, qc.qc_number, qc.reference_type, qc.reference_id, qc.reference_code, qc.supplier_id, qc.material_id, qc.inspect_qty, qc.passed_qty, qc.failed_qty, qc.unit_of_measure, qc.status, qc.result, qc.accepted_zone_id, qc.rejected_zone_id, qc.inspector_id, qc.notes, qc.started_at, qc.completed_at, qc.created_by, qc.created_at, qc.updated_at,
    s.name  AS supplier_name,
    m.code  AS material_code,
    m.name  AS material_name
FROM quality_checks qc
LEFT JOIN suppliers s ON s.id = qc.supplier_id
LEFT JOIN products m ON m.id = qc.material_id
WHERE qc.tenant_id = $1
ORDER BY
    CASE qc.status WHEN 'PENDING' THEN 1
                   WHEN 'IN_PROGRESS' THEN 2
                   ELSE 3 END,
    qc.created_at DESC
LIMIT $2 OFFSET $3
`

type ListQualityChecksParams struct {
	TenantID int64 `json:"tenant_id"`
	Limit    int32 `json:"limit"`
	Offset   int32 `json:"offset"`
}

type ListQualityChecksRow struct {
	ID             int64              `json:"id"`
	PublicID       uuid.UUID          `json:"public_id"`
	TenantID       int64              `json:"tenant_id"`
	QcNumber       string             `json:"qc_number"`
	ReferenceType  string             `json:"reference_type"`
	ReferenceID    pgtype.Int8        `json:"reference_id"`
	ReferenceCode  pgtype.Text        `json:"reference_code"`
	SupplierID     pgtype.Int8        `json:"supplier_id"`
	MaterialID     pgtype.Int8        `json:"material_id"`
	InspectQty     pgtype.Numeric     `json:"inspect_qty"`
	PassedQty      pgtype.Numeric     `json:"passed_qty"`
	FailedQty      pgtype.Numeric     `json:"failed_qty"`
	UnitOfMeasure  pgtype.Text        `json:"unit_of_measure"`
	Status         string             `json:"status"`
	Result         pgtype.Text        `json:"result"`
	AcceptedZoneID pgtype.Int8        `json:"accepted_zone_id"`
	RejectedZoneID pgtype.Int8        `json:"rejected_zone_id"`
	InspectorID    pgtype.Int8        `json:"inspector_id"`
	Notes          pgtype.Text        `json:"notes"`
	StartedAt      pgtype.Timestamptz `json:"started_at"`
	CompletedAt    pgtype.Timestamptz `json:"completed_at"`
	CreatedBy      pgtype.Int8        `json:"created_by"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	UpdatedAt      pgtype.Timestamptz `json:"updated_at"`
	SupplierName   pgtype.Text        `json:"supplier_name"`
	MaterialCode   pgtype.Text        `json:"material_code"`
	MaterialName   pgtype.Text        `json:"material_name"`
}

func (q *Queries) ListQualityChecks(ctx context.Context, arg ListQualityChecksParams) ([]ListQualityChecksRow, error) {
	rows, err := q.db.Query(ctx, listQualityChecks, arg.TenantID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListQualityChecksRow{}
	for rows.Next() {
		var i ListQualityChecksRow
		if err := rows.Scan(
			&i.ID,
			&i.PublicID,
			&i.TenantID,
			&i.QcNumber,
			&i.ReferenceType,
			&i.ReferenceID,
			&i.ReferenceCode,
			&i.SupplierID,
			&i.MaterialID,
			&i.InspectQty,
			&i.PassedQty,
			&i.FailedQty,
			&i.UnitOfMeasure,
			&i.Status,
			&i.Result,
			&i.AcceptedZoneID,
			&i.RejectedZoneID,
			&i.InspectorID,
			&i.Notes,
			&i.StartedAt,
			&i.CompletedAt,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.SupplierName,
			&i.MaterialCode,
			&i.MaterialName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const recordQCResult = `-- name: RecordQCResult :one
UPDATE quality_checks
SET status       = $2,
    result       = $3,
    passed_qty   = $4,
    failed_qty   = $5,
    completed_at = NOW(),
    notes        = COALESCE($6, notes),
    updated_at   = NOW()
WHERE id = $1
  AND status = 'IN_PROGRESS'
  AND tenant_id = $7
RETURNING id, public_id, tenant_id, qc_number, reference_type, reference_id, reference_code, supplier_id, material_id, inspect_qty, passed_qty, failed_qty, unit_of_measure, status, result, accepted_zone_id, rejected_zone_id, inspector_id, notes, started_at, completed_at, created_by, created_at, updated_at
`

type RecordQCResultParams struct {
	ID        int64          `json:"id"`
	Status    string         `json:"status"`
	Result    pgtype.Text    `json:"result"`
	PassedQty pgtype.Numeric `json:"passed_qty"`
	FailedQty pgtype.Numeric `json:"failed_qty"`
	Notes     pgtype.Text    `json:"notes"`
	TenantID  int64          `json:"tenant_id"`
}

func (q *Queries) RecordQCResult(ctx context.Context, arg RecordQCResultParams) (QualityCheck, error) {
	row := q.db.QueryRow(ctx, recordQCResult,
		arg.ID,
		arg.Status,
		arg.Result,
		arg.PassedQty,
		arg.FailedQty,
		arg.Notes,
		arg.TenantID,
	)
	var i QualityCheck
	err := row.Scan(
		&i.ID,
		&i.PublicID,
		&i.TenantID,
		&i.QcNumber,
		&i.ReferenceType,
		&i.ReferenceID,
		&i.ReferenceCode,
		&i.SupplierID,
		&i.MaterialID,
		&i.InspectQty,
		&i.PassedQty,
		&i.FailedQty,
		&i.UnitOfMeasure,
		&i.Status,
		&i.Result,
		&i.AcceptedZoneID,
		&i.RejectedZoneID,
		&i.InspectorID,
		&i.Notes,
		&i.StartedAt,
		&i.CompletedAt,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const startQualityCheck = `-- name: StartQualityCheck :one
UPDATE quality_checks
SET status       = 'IN_PROGRESS',
    inspector_id = $2,
    started_at   = NOW(),
    updated_at   = NOW()
WHERE id = $1
  AND status = 'PENDING'
  AND tenant_id = $3
RETURNING id, public_id, tenant_id, qc_number, reference_type, reference_id, reference_code, supplier_id, material_id, inspect_qty, passed_qty, failed_qty, unit_of_measure, status, result, accepted_zone_id, rejected_zone_id, inspector_id, notes, started_at, completed_at, created_by, created_at, updated_at
`

type StartQualityCheckParams struct {
	ID          int64       `json:"id"`
	InspectorID pgtype.Int8 `json:"inspector_id"`
	TenantID    int64       `json:"tenant_id"`
}

func (q *Queries) StartQualityCheck(ctx context.Context, arg StartQualityCheckParams) (QualityCheck, error) {
	row := q.db.QueryRow(ctx, startQualityCheck, arg.ID, arg.InspectorID, arg.TenantID)
	var i QualityCheck
	err := row.Scan(
		&i.ID,
		&i.PublicID,
		&i.TenantID,
		&i.QcNumber,
		&i.ReferenceType,
		&i.ReferenceID,
		&i.ReferenceCode,
		&i.SupplierID,
		&i.MaterialID,
		&i.InspectQty,
		&i.PassedQty,
		&i.FailedQty,
		&i.UnitOfMeasure,
		&i.Status,
		&i.Result,
		&i.AcceptedZoneID,
		&i.RejectedZoneID,
		&i.InspectorID,
		&i.Notes,
		&i.StartedAt,
		&i.CompletedAt,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
