// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.20.0

package dbgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	CreateInventoryEvent(ctx context.Context, arg CreateInventoryEventParams) (InventoryEvent, error)
	CreatePurchaseOrder(ctx context.Context, arg CreatePurchaseOrderParams) (PurchaseOrder, error)
	CreatePurchaseOrderLine(ctx context.Context, arg CreatePurchaseOrderLineParams) error
	CreatePurchaseRequest(ctx context.Context, arg CreatePurchaseRequestParams) (PurchaseRequest, error)
	CreatePurchaseRequestLine(ctx context.Context, arg CreatePurchaseRequestLineParams) error
	CreateSupplier(ctx context.Context, arg CreateSupplierParams) (Supplier, error)
	DeactivateSupplier(ctx context.Context, arg DeactivateSupplierParams) error
	GetBarcode(ctx context.Context, arg GetBarcodeParams) (Barcode, error)
	GetHUByBarcode(ctx context.Context, arg GetHUByBarcodeParams) (HandlingUnit, error)
	GetHUByID(ctx context.Context, id int64) (HandlingUnit, error)
	GetHUWithDetails(ctx context.Context, id int64) (GetHUWithDetailsRow, error)
	GetLocationByBarcode(ctx context.Context, arg GetLocationByBarcodeParams) (Location, error)
	GetLocationStock(ctx context.Context, locationID pgtype.Int8) ([]GetLocationStockRow, error)
	GetPOApprovalThreshold(ctx context.Context, tenantID int64) (GetPOApprovalThresholdRow, error)
	GetPurchaseOrderWithLines(ctx context.Context, arg GetPurchaseOrderWithLinesParams) ([]GetPurchaseOrderWithLinesRow, error)
	GetPurchaseRequestWithLines(ctx context.Context, arg GetPurchaseRequestWithLinesParams) ([]GetPurchaseRequestWithLinesRow, error)
	GetSupplierByCode(ctx context.Context, arg GetSupplierByCodeParams) (Supplier, error)
	GetTenantByID(ctx context.Context, id int64) (Tenant, error)
	GetTenantBySlug(ctx context.Context, slug string) (Tenant, error)
	GetUserByUsername(ctx context.Context, username string) (User, error)
	GetUserRoles(ctx context.Context, userID int64) ([]string, error)
	ListLocations(ctx context.Context, tenantID pgtype.Int8) ([]Location, error)
	ListPurchaseOrders(ctx context.Context, arg ListPurchaseOrdersParams) ([]ListPurchaseOrdersRow, error)
	ListPurchaseRequests(ctx context.Context, arg ListPurchaseRequestsParams) ([]PurchaseRequest, error)
	ListRecentEvents(ctx context.Context, arg ListRecentEventsParams) ([]ListRecentEventsRow, error)
	ListRecentHUs(ctx context.Context, arg ListRecentHUsParams) ([]ListRecentHUsRow, error)
	ListSuppliers(ctx context.Context, arg ListSuppliersParams) ([]Supplier, error)
	UpdateHULocation(ctx context.Context, arg UpdateHULocationParams) error
	UpdateHUStatus(ctx context.Context, arg UpdateHUStatusParams) error
	UpdatePurchaseOrderLineReceived(ctx context.Context, arg UpdatePurchaseOrderLineReceivedParams) error
	UpdatePurchaseOrderStatus(ctx context.Context, arg UpdatePurchaseOrderStatusParams) error
	UpdatePurchaseRequestStatus(ctx context.Context, arg UpdatePurchaseRequestStatusParams) error
	UpdateSupplier(ctx context.Context, arg UpdateSupplierParams) (Supplier, error)
}

var _ Querier = (*Queries)(nil)
