// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package dbgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	CreateInventoryEvent(ctx context.Context, arg CreateInventoryEventParams) (InventoryEvent, error)
	GetBarcode(ctx context.Context, arg GetBarcodeParams) (Barcode, error)
	GetHUByBarcode(ctx context.Context, arg GetHUByBarcodeParams) (HandlingUnit, error)
	GetHUByID(ctx context.Context, id int64) (HandlingUnit, error)
	GetHUWithDetails(ctx context.Context, id int64) (GetHUWithDetailsRow, error)
	GetLocationByBarcode(ctx context.Context, arg GetLocationByBarcodeParams) (Location, error)
	GetLocationStock(ctx context.Context, locationID pgtype.Int8) ([]GetLocationStockRow, error)
	GetTenantByID(ctx context.Context, id int64) (Tenant, error)
	GetTenantBySlug(ctx context.Context, slug string) (Tenant, error)
	GetUserByUsername(ctx context.Context, username string) (User, error)
	GetUserRoles(ctx context.Context, userID int64) ([]string, error)
	ListLocations(ctx context.Context, tenantID pgtype.Int8) ([]Location, error)
	ListRecentEvents(ctx context.Context, arg ListRecentEventsParams) ([]ListRecentEventsRow, error)
	ListRecentHUs(ctx context.Context, arg ListRecentHUsParams) ([]ListRecentHUsRow, error)
	UpdateHULocation(ctx context.Context, arg UpdateHULocationParams) error
	UpdateHUStatus(ctx context.Context, arg UpdateHUStatusParams) error
}

var _ Querier = (*Queries)(nil)
