// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package dbgen

import (
	"context"
)

type Querier interface {
	GetTenantByID(ctx context.Context, id int64) (Tenant, error)
	GetTenantBySlug(ctx context.Context, slug string) (Tenant, error)
	GetUserByUsername(ctx context.Context, username string) (User, error)
	GetUserRoles(ctx context.Context, userID int64) ([]string, error)
}

var _ Querier = (*Queries)(nil)
