// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: rfq.sql

package dbgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createRFQ = `-- name: CreateRFQ :one

INSERT INTO rfq_documents (
    tenant_id, rfq_number, status, rfq_type, collective_number, 
    document_date, deadline_date, validity_start, validity_end,
    apply_by_date, binding_days, purchasing_org_code, purchasing_group_code,
    your_reference, our_reference, salesperson, telephone, language_key,
    notes, created_by
) VALUES (
    $1, $2, 'DRAFT', $3, $4, CURRENT_DATE, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15, $16, $17, $18
) RETURNING id, tenant_id, public_id, rfq_number, status, purchasing_org, purchasing_group, document_date, deadline_date, notes, created_by, created_at, updated_at, rfq_type, collective_number, validity_start, validity_end, apply_by_date, binding_days, purchasing_org_code, purchasing_group_code, your_reference, our_reference, salesperson, telephone, language_key, finalised_by, finalised_at, procurement_unit_id, procurement_team_id, requesting_site_id
`

type CreateRFQParams struct {
	TenantID            int64       `json:"tenant_id"`
	RfqNumber           string      `json:"rfq_number"`
	RfqType             string      `json:"rfq_type"`
	CollectiveNumber    pgtype.Text `json:"collective_number"`
	DeadlineDate        pgtype.Date `json:"deadline_date"`
	ValidityStart       pgtype.Date `json:"validity_start"`
	ValidityEnd         pgtype.Date `json:"validity_end"`
	ApplyByDate         pgtype.Date `json:"apply_by_date"`
	BindingDays         pgtype.Int4 `json:"binding_days"`
	PurchasingOrgCode   pgtype.Text `json:"purchasing_org_code"`
	PurchasingGroupCode pgtype.Text `json:"purchasing_group_code"`
	YourReference       pgtype.Text `json:"your_reference"`
	OurReference        pgtype.Text `json:"our_reference"`
	Salesperson         pgtype.Text `json:"salesperson"`
	Telephone           pgtype.Text `json:"telephone"`
	LanguageKey         pgtype.Text `json:"language_key"`
	Notes               pgtype.Text `json:"notes"`
	CreatedBy           pgtype.Int8 `json:"created_by"`
}

// RFQ Document Queries
func (q *Queries) CreateRFQ(ctx context.Context, arg CreateRFQParams) (RfqDocument, error) {
	row := q.db.QueryRow(ctx, createRFQ,
		arg.TenantID,
		arg.RfqNumber,
		arg.RfqType,
		arg.CollectiveNumber,
		arg.DeadlineDate,
		arg.ValidityStart,
		arg.ValidityEnd,
		arg.ApplyByDate,
		arg.BindingDays,
		arg.PurchasingOrgCode,
		arg.PurchasingGroupCode,
		arg.YourReference,
		arg.OurReference,
		arg.Salesperson,
		arg.Telephone,
		arg.LanguageKey,
		arg.Notes,
		arg.CreatedBy,
	)
	var i RfqDocument
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.PublicID,
		&i.RfqNumber,
		&i.Status,
		&i.PurchasingOrg,
		&i.PurchasingGroup,
		&i.DocumentDate,
		&i.DeadlineDate,
		&i.Notes,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.RfqType,
		&i.CollectiveNumber,
		&i.ValidityStart,
		&i.ValidityEnd,
		&i.ApplyByDate,
		&i.BindingDays,
		&i.PurchasingOrgCode,
		&i.PurchasingGroupCode,
		&i.YourReference,
		&i.OurReference,
		&i.Salesperson,
		&i.Telephone,
		&i.LanguageKey,
		&i.FinalisedBy,
		&i.FinalisedAt,
		&i.ProcurementUnitID,
		&i.ProcurementTeamID,
		&i.RequestingSiteID,
	)
	return i, err
}

const createRFQLine = `-- name: CreateRFQLine :one
INSERT INTO rfq_lines (
    tenant_id, rfq_id, line_number, product_id, short_text, quantity, unit, 
    delivery_date, item_category, storage_location, material_group,
    req_tracking_no, planned_deliv_days, reason_for_order, has_schedule
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15
) RETURNING id, tenant_id, rfq_id, line_number, product_id, short_text, quantity, unit, delivery_date, receiving_zone_id, item_category, storage_location, material_group, req_tracking_no, planned_deliv_days, reason_for_order, has_schedule
`

type CreateRFQLineParams struct {
	TenantID         int64          `json:"tenant_id"`
	RfqID            int64          `json:"rfq_id"`
	LineNumber       int32          `json:"line_number"`
	ProductID        int64          `json:"product_id"`
	ShortText        pgtype.Text    `json:"short_text"`
	Quantity         pgtype.Numeric `json:"quantity"`
	Unit             string         `json:"unit"`
	DeliveryDate     pgtype.Date    `json:"delivery_date"`
	ItemCategory     pgtype.Text    `json:"item_category"`
	StorageLocation  pgtype.Text    `json:"storage_location"`
	MaterialGroup    pgtype.Text    `json:"material_group"`
	ReqTrackingNo    pgtype.Text    `json:"req_tracking_no"`
	PlannedDelivDays pgtype.Int4    `json:"planned_deliv_days"`
	ReasonForOrder   pgtype.Text    `json:"reason_for_order"`
	HasSchedule      bool           `json:"has_schedule"`
}

func (q *Queries) CreateRFQLine(ctx context.Context, arg CreateRFQLineParams) (RfqLine, error) {
	row := q.db.QueryRow(ctx, createRFQLine,
		arg.TenantID,
		arg.RfqID,
		arg.LineNumber,
		arg.ProductID,
		arg.ShortText,
		arg.Quantity,
		arg.Unit,
		arg.DeliveryDate,
		arg.ItemCategory,
		arg.StorageLocation,
		arg.MaterialGroup,
		arg.ReqTrackingNo,
		arg.PlannedDelivDays,
		arg.ReasonForOrder,
		arg.HasSchedule,
	)
	var i RfqLine
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.RfqID,
		&i.LineNumber,
		&i.ProductID,
		&i.ShortText,
		&i.Quantity,
		&i.Unit,
		&i.DeliveryDate,
		&i.ReceivingZoneID,
		&i.ItemCategory,
		&i.StorageLocation,
		&i.MaterialGroup,
		&i.ReqTrackingNo,
		&i.PlannedDelivDays,
		&i.ReasonForOrder,
		&i.HasSchedule,
	)
	return i, err
}

const createRFQQuotation = `-- name: CreateRFQQuotation :one

INSERT INTO rfq_quotations (
    tenant_id, rfq_vendor_id, document_date, valid_to, status, 
    total_value, currency, your_reference, warranty_terms
) VALUES (
    $1, $2, $3, $4, 'SUBMITTED', $5, $6, $7, $8
) RETURNING id, tenant_id, public_id, rfq_vendor_id, document_date, valid_to, status, total_value, currency, created_at, binding_until, your_reference, warranty_terms
`

type CreateRFQQuotationParams struct {
	TenantID      int64          `json:"tenant_id"`
	RfqVendorID   int64          `json:"rfq_vendor_id"`
	DocumentDate  pgtype.Date    `json:"document_date"`
	ValidTo       pgtype.Date    `json:"valid_to"`
	TotalValue    pgtype.Numeric `json:"total_value"`
	Currency      string         `json:"currency"`
	YourReference pgtype.Text    `json:"your_reference"`
	WarrantyTerms pgtype.Text    `json:"warranty_terms"`
}

// Quotation Queries
func (q *Queries) CreateRFQQuotation(ctx context.Context, arg CreateRFQQuotationParams) (RfqQuotation, error) {
	row := q.db.QueryRow(ctx, createRFQQuotation,
		arg.TenantID,
		arg.RfqVendorID,
		arg.DocumentDate,
		arg.ValidTo,
		arg.TotalValue,
		arg.Currency,
		arg.YourReference,
		arg.WarrantyTerms,
	)
	var i RfqQuotation
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.PublicID,
		&i.RfqVendorID,
		&i.DocumentDate,
		&i.ValidTo,
		&i.Status,
		&i.TotalValue,
		&i.Currency,
		&i.CreatedAt,
		&i.BindingUntil,
		&i.YourReference,
		&i.WarrantyTerms,
	)
	return i, err
}

const createRFQQuotationLine = `-- name: CreateRFQQuotationLine :exec
INSERT INTO rfq_quotation_lines (
    tenant_id, quotation_id, rfq_line_id, quantity_offered, 
    gross_price, discount_pct, discount_amount, freight_value,
    tax_code, tax_amount, effective_price,
    delivery_date_offered, notes, pricing_steps
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14
)
`

type CreateRFQQuotationLineParams struct {
	TenantID            int64          `json:"tenant_id"`
	QuotationID         int64          `json:"quotation_id"`
	RfqLineID           int64          `json:"rfq_line_id"`
	QuantityOffered     pgtype.Numeric `json:"quantity_offered"`
	GrossPrice          pgtype.Numeric `json:"gross_price"`
	DiscountPct         pgtype.Numeric `json:"discount_pct"`
	DiscountAmount      pgtype.Numeric `json:"discount_amount"`
	FreightValue        pgtype.Numeric `json:"freight_value"`
	TaxCode             pgtype.Text    `json:"tax_code"`
	TaxAmount           pgtype.Numeric `json:"tax_amount"`
	EffectivePrice      pgtype.Numeric `json:"effective_price"`
	DeliveryDateOffered pgtype.Date    `json:"delivery_date_offered"`
	Notes               pgtype.Text    `json:"notes"`
	PricingSteps        []byte         `json:"pricing_steps"`
}

func (q *Queries) CreateRFQQuotationLine(ctx context.Context, arg CreateRFQQuotationLineParams) error {
	_, err := q.db.Exec(ctx, createRFQQuotationLine,
		arg.TenantID,
		arg.QuotationID,
		arg.RfqLineID,
		arg.QuantityOffered,
		arg.GrossPrice,
		arg.DiscountPct,
		arg.DiscountAmount,
		arg.FreightValue,
		arg.TaxCode,
		arg.TaxAmount,
		arg.EffectivePrice,
		arg.DeliveryDateOffered,
		arg.Notes,
		arg.PricingSteps,
	)
	return err
}

const createRFQVendor = `-- name: CreateRFQVendor :exec
INSERT INTO rfq_vendors (
    tenant_id, rfq_id, supplier_id, status
) VALUES (
    $1, $2, $3, 'PENDING'
) ON CONFLICT (rfq_id, supplier_id) DO NOTHING
`

type CreateRFQVendorParams struct {
	TenantID   int64 `json:"tenant_id"`
	RfqID      int64 `json:"rfq_id"`
	SupplierID int64 `json:"supplier_id"`
}

func (q *Queries) CreateRFQVendor(ctx context.Context, arg CreateRFQVendorParams) error {
	_, err := q.db.Exec(ctx, createRFQVendor, arg.TenantID, arg.RfqID, arg.SupplierID)
	return err
}

const finaliseRFQStatus = `-- name: FinaliseRFQStatus :exec
UPDATE rfq_quotations
SET status = CASE WHEN rfq_quotations.id = $1 THEN 'ACCEPTED' ELSE 'REJECTED' END
WHERE rfq_vendor_id IN (SELECT id FROM rfq_vendors WHERE rfq_id = $2)
`

type FinaliseRFQStatusParams struct {
	ID    int64 `json:"id"`
	RfqID int64 `json:"rfq_id"`
}

func (q *Queries) FinaliseRFQStatus(ctx context.Context, arg FinaliseRFQStatusParams) error {
	_, err := q.db.Exec(ctx, finaliseRFQStatus, arg.ID, arg.RfqID)
	return err
}

const getRFQ = `-- name: GetRFQ :one
SELECT id, tenant_id, public_id, rfq_number, status, purchasing_org, purchasing_group, document_date, deadline_date, notes, created_by, created_at, updated_at, rfq_type, collective_number, validity_start, validity_end, apply_by_date, binding_days, purchasing_org_code, purchasing_group_code, your_reference, our_reference, salesperson, telephone, language_key, finalised_by, finalised_at, procurement_unit_id, procurement_team_id, requesting_site_id FROM rfq_documents WHERE id = $1 AND tenant_id = $2
`

type GetRFQParams struct {
	ID       int64 `json:"id"`
	TenantID int64 `json:"tenant_id"`
}

func (q *Queries) GetRFQ(ctx context.Context, arg GetRFQParams) (RfqDocument, error) {
	row := q.db.QueryRow(ctx, getRFQ, arg.ID, arg.TenantID)
	var i RfqDocument
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.PublicID,
		&i.RfqNumber,
		&i.Status,
		&i.PurchasingOrg,
		&i.PurchasingGroup,
		&i.DocumentDate,
		&i.DeadlineDate,
		&i.Notes,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.RfqType,
		&i.CollectiveNumber,
		&i.ValidityStart,
		&i.ValidityEnd,
		&i.ApplyByDate,
		&i.BindingDays,
		&i.PurchasingOrgCode,
		&i.PurchasingGroupCode,
		&i.YourReference,
		&i.OurReference,
		&i.Salesperson,
		&i.Telephone,
		&i.LanguageKey,
		&i.FinalisedBy,
		&i.FinalisedAt,
		&i.ProcurementUnitID,
		&i.ProcurementTeamID,
		&i.RequestingSiteID,
	)
	return i, err
}

const getRFQLines = `-- name: GetRFQLines :many
SELECT l.id, l.tenant_id, l.rfq_id, l.line_number, l.product_id, l.short_text, l.quantity, l.unit, l.delivery_date, l.receiving_zone_id, l.item_category, l.storage_location, l.material_group, l.req_tracking_no, l.planned_deliv_days, l.reason_for_order, l.has_schedule, p.code as product_code, p.name as product_name,
       (SELECT COUNT(*) FROM rfq_quotation_lines ql WHERE ql.rfq_line_id = l.id) as quote_count
FROM rfq_lines l
LEFT JOIN products p ON l.product_id = p.id
WHERE l.rfq_id = $1 AND l.tenant_id = $2
ORDER BY l.line_number ASC
`

type GetRFQLinesParams struct {
	RfqID    int64 `json:"rfq_id"`
	TenantID int64 `json:"tenant_id"`
}

type GetRFQLinesRow struct {
	ID               int64          `json:"id"`
	TenantID         int64          `json:"tenant_id"`
	RfqID            int64          `json:"rfq_id"`
	LineNumber       int32          `json:"line_number"`
	ProductID        int64          `json:"product_id"`
	ShortText        pgtype.Text    `json:"short_text"`
	Quantity         pgtype.Numeric `json:"quantity"`
	Unit             string         `json:"unit"`
	DeliveryDate     pgtype.Date    `json:"delivery_date"`
	ReceivingZoneID  pgtype.Int8    `json:"receiving_zone_id"`
	ItemCategory     pgtype.Text    `json:"item_category"`
	StorageLocation  pgtype.Text    `json:"storage_location"`
	MaterialGroup    pgtype.Text    `json:"material_group"`
	ReqTrackingNo    pgtype.Text    `json:"req_tracking_no"`
	PlannedDelivDays pgtype.Int4    `json:"planned_deliv_days"`
	ReasonForOrder   pgtype.Text    `json:"reason_for_order"`
	HasSchedule      bool           `json:"has_schedule"`
	ProductCode      pgtype.Text    `json:"product_code"`
	ProductName      pgtype.Text    `json:"product_name"`
	QuoteCount       int64          `json:"quote_count"`
}

func (q *Queries) GetRFQLines(ctx context.Context, arg GetRFQLinesParams) ([]GetRFQLinesRow, error) {
	rows, err := q.db.Query(ctx, getRFQLines, arg.RfqID, arg.TenantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetRFQLinesRow{}
	for rows.Next() {
		var i GetRFQLinesRow
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.RfqID,
			&i.LineNumber,
			&i.ProductID,
			&i.ShortText,
			&i.Quantity,
			&i.Unit,
			&i.DeliveryDate,
			&i.ReceivingZoneID,
			&i.ItemCategory,
			&i.StorageLocation,
			&i.MaterialGroup,
			&i.ReqTrackingNo,
			&i.PlannedDelivDays,
			&i.ReasonForOrder,
			&i.HasSchedule,
			&i.ProductCode,
			&i.ProductName,
			&i.QuoteCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getRFQQuotationLines = `-- name: GetRFQQuotationLines :many
SELECT ql.id, ql.tenant_id, ql.quotation_id, ql.rfq_line_id, ql.quantity_offered, ql.unit_price, ql.delivery_date_offered, ql.notes, ql.gross_price, ql.discount_pct, ql.discount_amount, ql.freight_value, ql.tax_code, ql.tax_amount, ql.effective_price, ql.is_rejected, ql.rejection_reason, ql.rejection_sent_at, ql.pricing_steps, rl.line_number, rl.product_id, rl.short_text, rl.unit as rfq_unit
FROM rfq_quotation_lines ql
JOIN rfq_lines rl ON ql.rfq_line_id = rl.id
WHERE ql.quotation_id = $1 AND ql.tenant_id = $2
`

type GetRFQQuotationLinesParams struct {
	QuotationID int64 `json:"quotation_id"`
	TenantID    int64 `json:"tenant_id"`
}

type GetRFQQuotationLinesRow struct {
	ID                  int64              `json:"id"`
	TenantID            int64              `json:"tenant_id"`
	QuotationID         int64              `json:"quotation_id"`
	RfqLineID           int64              `json:"rfq_line_id"`
	QuantityOffered     pgtype.Numeric     `json:"quantity_offered"`
	UnitPrice           pgtype.Numeric     `json:"unit_price"`
	DeliveryDateOffered pgtype.Date        `json:"delivery_date_offered"`
	Notes               pgtype.Text        `json:"notes"`
	GrossPrice          pgtype.Numeric     `json:"gross_price"`
	DiscountPct         pgtype.Numeric     `json:"discount_pct"`
	DiscountAmount      pgtype.Numeric     `json:"discount_amount"`
	FreightValue        pgtype.Numeric     `json:"freight_value"`
	TaxCode             pgtype.Text        `json:"tax_code"`
	TaxAmount           pgtype.Numeric     `json:"tax_amount"`
	EffectivePrice      pgtype.Numeric     `json:"effective_price"`
	IsRejected          bool               `json:"is_rejected"`
	RejectionReason     pgtype.Text        `json:"rejection_reason"`
	RejectionSentAt     pgtype.Timestamptz `json:"rejection_sent_at"`
	PricingSteps        []byte             `json:"pricing_steps"`
	LineNumber          int32              `json:"line_number"`
	ProductID           int64              `json:"product_id"`
	ShortText           pgtype.Text        `json:"short_text"`
	RfqUnit             string             `json:"rfq_unit"`
}

func (q *Queries) GetRFQQuotationLines(ctx context.Context, arg GetRFQQuotationLinesParams) ([]GetRFQQuotationLinesRow, error) {
	rows, err := q.db.Query(ctx, getRFQQuotationLines, arg.QuotationID, arg.TenantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetRFQQuotationLinesRow{}
	for rows.Next() {
		var i GetRFQQuotationLinesRow
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.QuotationID,
			&i.RfqLineID,
			&i.QuantityOffered,
			&i.UnitPrice,
			&i.DeliveryDateOffered,
			&i.Notes,
			&i.GrossPrice,
			&i.DiscountPct,
			&i.DiscountAmount,
			&i.FreightValue,
			&i.TaxCode,
			&i.TaxAmount,
			&i.EffectivePrice,
			&i.IsRejected,
			&i.RejectionReason,
			&i.RejectionSentAt,
			&i.PricingSteps,
			&i.LineNumber,
			&i.ProductID,
			&i.ShortText,
			&i.RfqUnit,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getRFQQuotations = `-- name: GetRFQQuotations :many
SELECT q.id, q.tenant_id, q.public_id, q.rfq_vendor_id, q.document_date, q.valid_to, q.status, q.total_value, q.currency, q.created_at, q.binding_until, q.your_reference, q.warranty_terms, s.name as vendor_name, s.public_id as vendor_public_id, s.code as vendor_code
FROM rfq_quotations q
JOIN rfq_vendors v ON q.rfq_vendor_id = v.id
JOIN suppliers s ON v.supplier_id = s.id
WHERE v.rfq_id = $1 AND q.tenant_id = $2
`

type GetRFQQuotationsParams struct {
	RfqID    int64 `json:"rfq_id"`
	TenantID int64 `json:"tenant_id"`
}

type GetRFQQuotationsRow struct {
	ID             int64              `json:"id"`
	TenantID       int64              `json:"tenant_id"`
	PublicID       pgtype.UUID        `json:"public_id"`
	RfqVendorID    int64              `json:"rfq_vendor_id"`
	DocumentDate   pgtype.Date        `json:"document_date"`
	ValidTo        pgtype.Date        `json:"valid_to"`
	Status         string             `json:"status"`
	TotalValue     pgtype.Numeric     `json:"total_value"`
	Currency       string             `json:"currency"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	BindingUntil   pgtype.Date        `json:"binding_until"`
	YourReference  pgtype.Text        `json:"your_reference"`
	WarrantyTerms  pgtype.Text        `json:"warranty_terms"`
	VendorName     string             `json:"vendor_name"`
	VendorPublicID pgtype.UUID        `json:"vendor_public_id"`
	VendorCode     string             `json:"vendor_code"`
}

func (q *Queries) GetRFQQuotations(ctx context.Context, arg GetRFQQuotationsParams) ([]GetRFQQuotationsRow, error) {
	rows, err := q.db.Query(ctx, getRFQQuotations, arg.RfqID, arg.TenantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetRFQQuotationsRow{}
	for rows.Next() {
		var i GetRFQQuotationsRow
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.PublicID,
			&i.RfqVendorID,
			&i.DocumentDate,
			&i.ValidTo,
			&i.Status,
			&i.TotalValue,
			&i.Currency,
			&i.CreatedAt,
			&i.BindingUntil,
			&i.YourReference,
			&i.WarrantyTerms,
			&i.VendorName,
			&i.VendorPublicID,
			&i.VendorCode,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getRFQVendors = `-- name: GetRFQVendors :many
SELECT v.id, v.tenant_id, v.rfq_id, v.supplier_id, v.status, v.notified_at, v.quote_received, v.is_selected, s.name as vendor_name, s.code as vendor_code
FROM rfq_vendors v
JOIN suppliers s ON v.supplier_id = s.id
WHERE v.rfq_id = $1 AND v.tenant_id = $2
`

type GetRFQVendorsParams struct {
	RfqID    int64 `json:"rfq_id"`
	TenantID int64 `json:"tenant_id"`
}

type GetRFQVendorsRow struct {
	ID            int64              `json:"id"`
	TenantID      int64              `json:"tenant_id"`
	RfqID         int64              `json:"rfq_id"`
	SupplierID    int64              `json:"supplier_id"`
	Status        string             `json:"status"`
	NotifiedAt    pgtype.Timestamptz `json:"notified_at"`
	QuoteReceived bool               `json:"quote_received"`
	IsSelected    bool               `json:"is_selected"`
	VendorName    string             `json:"vendor_name"`
	VendorCode    string             `json:"vendor_code"`
}

func (q *Queries) GetRFQVendors(ctx context.Context, arg GetRFQVendorsParams) ([]GetRFQVendorsRow, error) {
	rows, err := q.db.Query(ctx, getRFQVendors, arg.RfqID, arg.TenantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetRFQVendorsRow{}
	for rows.Next() {
		var i GetRFQVendorsRow
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.RfqID,
			&i.SupplierID,
			&i.Status,
			&i.NotifiedAt,
			&i.QuoteReceived,
			&i.IsSelected,
			&i.VendorName,
			&i.VendorCode,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRFQs = `-- name: ListRFQs :many
SELECT r.id, r.tenant_id, r.public_id, r.rfq_number, r.status, r.purchasing_org, r.purchasing_group, r.document_date, r.deadline_date, r.notes, r.created_by, r.created_at, r.updated_at, r.rfq_type, r.collective_number, r.validity_start, r.validity_end, r.apply_by_date, r.binding_days, r.purchasing_org_code, r.purchasing_group_code, r.your_reference, r.our_reference, r.salesperson, r.telephone, r.language_key, r.finalised_by, r.finalised_at, r.procurement_unit_id, r.procurement_team_id, r.requesting_site_id, 
       (SELECT COUNT(*) FROM rfq_lines WHERE rfq_id = r.id) as line_count,
       (SELECT COUNT(*) FROM rfq_vendors WHERE rfq_id = r.id) as vendor_count,
       (SELECT COUNT(*) FROM rfq_vendors WHERE rfq_id = r.id AND quote_received = true) as quotes_received
FROM rfq_documents r
WHERE r.tenant_id = $1 
  AND ($2::text = '' OR r.status = $2)
  AND ($3::text IS NULL OR r.collective_number = $3)
ORDER BY r.created_at DESC
`

type ListRFQsParams struct {
	TenantID         int64       `json:"tenant_id"`
	Column2          string      `json:"column_2"`
	CollectiveNumber pgtype.Text `json:"collective_number"`
}

type ListRFQsRow struct {
	ID                  int64              `json:"id"`
	TenantID            int64              `json:"tenant_id"`
	PublicID            pgtype.UUID        `json:"public_id"`
	RfqNumber           string             `json:"rfq_number"`
	Status              string             `json:"status"`
	PurchasingOrg       pgtype.Text        `json:"purchasing_org"`
	PurchasingGroup     pgtype.Text        `json:"purchasing_group"`
	DocumentDate        pgtype.Date        `json:"document_date"`
	DeadlineDate        pgtype.Date        `json:"deadline_date"`
	Notes               pgtype.Text        `json:"notes"`
	CreatedBy           pgtype.Int8        `json:"created_by"`
	CreatedAt           pgtype.Timestamptz `json:"created_at"`
	UpdatedAt           pgtype.Timestamptz `json:"updated_at"`
	RfqType             string             `json:"rfq_type"`
	CollectiveNumber    pgtype.Text        `json:"collective_number"`
	ValidityStart       pgtype.Date        `json:"validity_start"`
	ValidityEnd         pgtype.Date        `json:"validity_end"`
	ApplyByDate         pgtype.Date        `json:"apply_by_date"`
	BindingDays         pgtype.Int4        `json:"binding_days"`
	PurchasingOrgCode   pgtype.Text        `json:"purchasing_org_code"`
	PurchasingGroupCode pgtype.Text        `json:"purchasing_group_code"`
	YourReference       pgtype.Text        `json:"your_reference"`
	OurReference        pgtype.Text        `json:"our_reference"`
	Salesperson         pgtype.Text        `json:"salesperson"`
	Telephone           pgtype.Text        `json:"telephone"`
	LanguageKey         pgtype.Text        `json:"language_key"`
	FinalisedBy         pgtype.Int8        `json:"finalised_by"`
	FinalisedAt         pgtype.Timestamptz `json:"finalised_at"`
	ProcurementUnitID   pgtype.Int8        `json:"procurement_unit_id"`
	ProcurementTeamID   pgtype.Int8        `json:"procurement_team_id"`
	RequestingSiteID    pgtype.Int8        `json:"requesting_site_id"`
	LineCount           int64              `json:"line_count"`
	VendorCount         int64              `json:"vendor_count"`
	QuotesReceived      int64              `json:"quotes_received"`
}

func (q *Queries) ListRFQs(ctx context.Context, arg ListRFQsParams) ([]ListRFQsRow, error) {
	rows, err := q.db.Query(ctx, listRFQs, arg.TenantID, arg.Column2, arg.CollectiveNumber)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListRFQsRow{}
	for rows.Next() {
		var i ListRFQsRow
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.PublicID,
			&i.RfqNumber,
			&i.Status,
			&i.PurchasingOrg,
			&i.PurchasingGroup,
			&i.DocumentDate,
			&i.DeadlineDate,
			&i.Notes,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.RfqType,
			&i.CollectiveNumber,
			&i.ValidityStart,
			&i.ValidityEnd,
			&i.ApplyByDate,
			&i.BindingDays,
			&i.PurchasingOrgCode,
			&i.PurchasingGroupCode,
			&i.YourReference,
			&i.OurReference,
			&i.Salesperson,
			&i.Telephone,
			&i.LanguageKey,
			&i.FinalisedBy,
			&i.FinalisedAt,
			&i.ProcurementUnitID,
			&i.ProcurementTeamID,
			&i.RequestingSiteID,
			&i.LineCount,
			&i.VendorCount,
			&i.QuotesReceived,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markRejectionSent = `-- name: MarkRejectionSent :exec
UPDATE rfq_quotation_lines
SET rejection_sent_at = now()
WHERE quotation_id IN (
    SELECT id FROM rfq_quotations 
    WHERE rfq_vendor_id IN (
        SELECT id FROM rfq_vendors WHERE rfq_id = $1 AND supplier_id = ANY($2::bigint[])
    )
) AND is_rejected = true
`

type MarkRejectionSentParams struct {
	RfqID   int64   `json:"rfq_id"`
	Column2 []int64 `json:"column_2"`
}

func (q *Queries) MarkRejectionSent(ctx context.Context, arg MarkRejectionSentParams) error {
	_, err := q.db.Exec(ctx, markRejectionSent, arg.RfqID, arg.Column2)
	return err
}

const rejectQuotationLine = `-- name: RejectQuotationLine :exec
UPDATE rfq_quotation_lines
SET is_rejected = true, rejection_reason = $3, rejection_sent_at = NULL
WHERE id = $1 AND tenant_id = $2
`

type RejectQuotationLineParams struct {
	ID              int64       `json:"id"`
	TenantID        int64       `json:"tenant_id"`
	RejectionReason pgtype.Text `json:"rejection_reason"`
}

func (q *Queries) RejectQuotationLine(ctx context.Context, arg RejectQuotationLineParams) error {
	_, err := q.db.Exec(ctx, rejectQuotationLine, arg.ID, arg.TenantID, arg.RejectionReason)
	return err
}

const uninviteRFQVendor = `-- name: UninviteRFQVendor :exec
DELETE FROM rfq_vendors 
WHERE rfq_vendors.rfq_id = $1 AND rfq_vendors.supplier_id = $2 AND rfq_vendors.tenant_id = $3
AND NOT EXISTS (SELECT 1 FROM rfq_quotations WHERE rfq_vendor_id = rfq_vendors.id)
`

type UninviteRFQVendorParams struct {
	RfqID      int64 `json:"rfq_id"`
	SupplierID int64 `json:"supplier_id"`
	TenantID   int64 `json:"tenant_id"`
}

func (q *Queries) UninviteRFQVendor(ctx context.Context, arg UninviteRFQVendorParams) error {
	_, err := q.db.Exec(ctx, uninviteRFQVendor, arg.RfqID, arg.SupplierID, arg.TenantID)
	return err
}

const updateRFQFinalised = `-- name: UpdateRFQFinalised :exec
UPDATE rfq_documents
SET status = 'FINALISED', finalised_by = $3, finalised_at = now()
WHERE rfq_documents.id = $1 AND rfq_documents.tenant_id = $2
`

type UpdateRFQFinalisedParams struct {
	ID          int64       `json:"id"`
	TenantID    int64       `json:"tenant_id"`
	FinalisedBy pgtype.Int8 `json:"finalised_by"`
}

func (q *Queries) UpdateRFQFinalised(ctx context.Context, arg UpdateRFQFinalisedParams) error {
	_, err := q.db.Exec(ctx, updateRFQFinalised, arg.ID, arg.TenantID, arg.FinalisedBy)
	return err
}

const updateRFQHeader = `-- name: UpdateRFQHeader :one
UPDATE rfq_documents
SET
    deadline_date = $3,
    collective_number = $4,
    validity_start = $5,
    validity_end = $6,
    apply_by_date = $7,
    binding_days = $8,
    notes = $9,
    your_reference = $10,
    our_reference = $11,
    salesperson = $12,
    telephone = $13,
    updated_at = now()
WHERE id = $1 AND tenant_id = $2 AND status = 'DRAFT'
RETURNING id, tenant_id, public_id, rfq_number, status, purchasing_org, purchasing_group, document_date, deadline_date, notes, created_by, created_at, updated_at, rfq_type, collective_number, validity_start, validity_end, apply_by_date, binding_days, purchasing_org_code, purchasing_group_code, your_reference, our_reference, salesperson, telephone, language_key, finalised_by, finalised_at, procurement_unit_id, procurement_team_id, requesting_site_id
`

type UpdateRFQHeaderParams struct {
	ID               int64       `json:"id"`
	TenantID         int64       `json:"tenant_id"`
	DeadlineDate     pgtype.Date `json:"deadline_date"`
	CollectiveNumber pgtype.Text `json:"collective_number"`
	ValidityStart    pgtype.Date `json:"validity_start"`
	ValidityEnd      pgtype.Date `json:"validity_end"`
	ApplyByDate      pgtype.Date `json:"apply_by_date"`
	BindingDays      pgtype.Int4 `json:"binding_days"`
	Notes            pgtype.Text `json:"notes"`
	YourReference    pgtype.Text `json:"your_reference"`
	OurReference     pgtype.Text `json:"our_reference"`
	Salesperson      pgtype.Text `json:"salesperson"`
	Telephone        pgtype.Text `json:"telephone"`
}

func (q *Queries) UpdateRFQHeader(ctx context.Context, arg UpdateRFQHeaderParams) (RfqDocument, error) {
	row := q.db.QueryRow(ctx, updateRFQHeader,
		arg.ID,
		arg.TenantID,
		arg.DeadlineDate,
		arg.CollectiveNumber,
		arg.ValidityStart,
		arg.ValidityEnd,
		arg.ApplyByDate,
		arg.BindingDays,
		arg.Notes,
		arg.YourReference,
		arg.OurReference,
		arg.Salesperson,
		arg.Telephone,
	)
	var i RfqDocument
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.PublicID,
		&i.RfqNumber,
		&i.Status,
		&i.PurchasingOrg,
		&i.PurchasingGroup,
		&i.DocumentDate,
		&i.DeadlineDate,
		&i.Notes,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.RfqType,
		&i.CollectiveNumber,
		&i.ValidityStart,
		&i.ValidityEnd,
		&i.ApplyByDate,
		&i.BindingDays,
		&i.PurchasingOrgCode,
		&i.PurchasingGroupCode,
		&i.YourReference,
		&i.OurReference,
		&i.Salesperson,
		&i.Telephone,
		&i.LanguageKey,
		&i.FinalisedBy,
		&i.FinalisedAt,
		&i.ProcurementUnitID,
		&i.ProcurementTeamID,
		&i.RequestingSiteID,
	)
	return i, err
}

const updateRFQLine = `-- name: UpdateRFQLine :one
UPDATE rfq_lines
SET
    quantity = $3,
    unit = $4,
    delivery_date = $5,
    planned_deliv_days = $6,
    reason_for_order = $7,
    storage_location = $8,
    short_text = $9,
    updated_at = now()
WHERE rfq_lines.id = $1 AND rfq_lines.tenant_id = $2
AND NOT EXISTS (SELECT 1 FROM rfq_quotation_lines WHERE rfq_line_id = rfq_lines.id)
RETURNING id, tenant_id, rfq_id, line_number, product_id, short_text, quantity, unit, delivery_date, receiving_zone_id, item_category, storage_location, material_group, req_tracking_no, planned_deliv_days, reason_for_order, has_schedule
`

type UpdateRFQLineParams struct {
	ID               int64          `json:"id"`
	TenantID         int64          `json:"tenant_id"`
	Quantity         pgtype.Numeric `json:"quantity"`
	Unit             string         `json:"unit"`
	DeliveryDate     pgtype.Date    `json:"delivery_date"`
	PlannedDelivDays pgtype.Int4    `json:"planned_deliv_days"`
	ReasonForOrder   pgtype.Text    `json:"reason_for_order"`
	StorageLocation  pgtype.Text    `json:"storage_location"`
	ShortText        pgtype.Text    `json:"short_text"`
}

func (q *Queries) UpdateRFQLine(ctx context.Context, arg UpdateRFQLineParams) (RfqLine, error) {
	row := q.db.QueryRow(ctx, updateRFQLine,
		arg.ID,
		arg.TenantID,
		arg.Quantity,
		arg.Unit,
		arg.DeliveryDate,
		arg.PlannedDelivDays,
		arg.ReasonForOrder,
		arg.StorageLocation,
		arg.ShortText,
	)
	var i RfqLine
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.RfqID,
		&i.LineNumber,
		&i.ProductID,
		&i.ShortText,
		&i.Quantity,
		&i.Unit,
		&i.DeliveryDate,
		&i.ReceivingZoneID,
		&i.ItemCategory,
		&i.StorageLocation,
		&i.MaterialGroup,
		&i.ReqTrackingNo,
		&i.PlannedDelivDays,
		&i.ReasonForOrder,
		&i.HasSchedule,
	)
	return i, err
}

const updateRFQStatus = `-- name: UpdateRFQStatus :exec
UPDATE rfq_documents
SET status = $3, updated_at = now()
WHERE tenant_id = $1 AND id = $2
`

type UpdateRFQStatusParams struct {
	TenantID int64  `json:"tenant_id"`
	ID       int64  `json:"id"`
	Status   string `json:"status"`
}

func (q *Queries) UpdateRFQStatus(ctx context.Context, arg UpdateRFQStatusParams) error {
	_, err := q.db.Exec(ctx, updateRFQStatus, arg.TenantID, arg.ID, arg.Status)
	return err
}

const updateRFQWinnerVendor = `-- name: UpdateRFQWinnerVendor :exec
UPDATE rfq_vendors
SET is_selected = true
WHERE rfq_id = $1 AND supplier_id = $2 AND tenant_id = $3
`

type UpdateRFQWinnerVendorParams struct {
	RfqID      int64 `json:"rfq_id"`
	SupplierID int64 `json:"supplier_id"`
	TenantID   int64 `json:"tenant_id"`
}

func (q *Queries) UpdateRFQWinnerVendor(ctx context.Context, arg UpdateRFQWinnerVendorParams) error {
	_, err := q.db.Exec(ctx, updateRFQWinnerVendor, arg.RfqID, arg.SupplierID, arg.TenantID)
	return err
}
