// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0
// source: rfq_config.sql

package dbgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createDeliverySchedule = `-- name: CreateDeliverySchedule :exec
INSERT INTO rfq_delivery_schedules (
    tenant_id, rfq_line_id, delivery_date, quantity, is_fixed
) VALUES (
    $1, $2, $3, $4, $5
)
`

type CreateDeliveryScheduleParams struct {
	TenantID     int64          `json:"tenant_id"`
	RfqLineID    int64          `json:"rfq_line_id"`
	DeliveryDate pgtype.Date    `json:"delivery_date"`
	Quantity     pgtype.Numeric `json:"quantity"`
	IsFixed      bool           `json:"is_fixed"`
}

func (q *Queries) CreateDeliverySchedule(ctx context.Context, arg CreateDeliveryScheduleParams) error {
	_, err := q.db.Exec(ctx, createDeliverySchedule,
		arg.TenantID,
		arg.RfqLineID,
		arg.DeliveryDate,
		arg.Quantity,
		arg.IsFixed,
	)
	return err
}

const createOrderReason = `-- name: CreateOrderReason :one
INSERT INTO rfq_order_reasons (
    tenant_id, reason_code, description
) VALUES (
    $1, $2, $3
) ON CONFLICT (tenant_id, reason_code) DO NOTHING
RETURNING id, tenant_id, reason_code, description, is_active
`

type CreateOrderReasonParams struct {
	TenantID    int64  `json:"tenant_id"`
	ReasonCode  string `json:"reason_code"`
	Description string `json:"description"`
}

func (q *Queries) CreateOrderReason(ctx context.Context, arg CreateOrderReasonParams) (RfqOrderReason, error) {
	row := q.db.QueryRow(ctx, createOrderReason, arg.TenantID, arg.ReasonCode, arg.Description)
	var i RfqOrderReason
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.ReasonCode,
		&i.Description,
		&i.IsActive,
	)
	return i, err
}

const createRFQType = `-- name: CreateRFQType :one
INSERT INTO rfq_document_types (
    tenant_id, type_code, description, is_gp_bid
) VALUES (
    $1, $2, $3, $4
) ON CONFLICT (tenant_id, type_code) DO NOTHING
RETURNING id, tenant_id, type_code, description, is_gp_bid, is_active, created_at
`

type CreateRFQTypeParams struct {
	TenantID    int64  `json:"tenant_id"`
	TypeCode    string `json:"type_code"`
	Description string `json:"description"`
	IsGpBid     bool   `json:"is_gp_bid"`
}

func (q *Queries) CreateRFQType(ctx context.Context, arg CreateRFQTypeParams) (RfqDocumentType, error) {
	row := q.db.QueryRow(ctx, createRFQType,
		arg.TenantID,
		arg.TypeCode,
		arg.Description,
		arg.IsGpBid,
	)
	var i RfqDocumentType
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.TypeCode,
		&i.Description,
		&i.IsGpBid,
		&i.IsActive,
		&i.CreatedAt,
	)
	return i, err
}

const deleteDeliverySchedulesForLine = `-- name: DeleteDeliverySchedulesForLine :exec
DELETE FROM rfq_delivery_schedules
WHERE rfq_line_id = $1
`

func (q *Queries) DeleteDeliverySchedulesForLine(ctx context.Context, rfqLineID int64) error {
	_, err := q.db.Exec(ctx, deleteDeliverySchedulesForLine, rfqLineID)
	return err
}

const getDeliverySchedules = `-- name: GetDeliverySchedules :many
SELECT id, tenant_id, rfq_line_id, delivery_date, quantity, is_fixed, created_at FROM rfq_delivery_schedules
WHERE rfq_line_id = $1
ORDER BY delivery_date ASC
`

func (q *Queries) GetDeliverySchedules(ctx context.Context, rfqLineID int64) ([]RfqDeliverySchedule, error) {
	rows, err := q.db.Query(ctx, getDeliverySchedules, rfqLineID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []RfqDeliverySchedule{}
	for rows.Next() {
		var i RfqDeliverySchedule
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.RfqLineID,
			&i.DeliveryDate,
			&i.Quantity,
			&i.IsFixed,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getOrderReasons = `-- name: GetOrderReasons :many
SELECT id, tenant_id, reason_code, description, is_active FROM rfq_order_reasons
WHERE tenant_id = $1 AND is_active = true
ORDER BY reason_code ASC
`

func (q *Queries) GetOrderReasons(ctx context.Context, tenantID int64) ([]RfqOrderReason, error) {
	rows, err := q.db.Query(ctx, getOrderReasons, tenantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []RfqOrderReason{}
	for rows.Next() {
		var i RfqOrderReason
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.ReasonCode,
			&i.Description,
			&i.IsActive,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getRFQTypes = `-- name: GetRFQTypes :many
SELECT id, tenant_id, type_code, description, is_gp_bid, is_active, created_at FROM rfq_document_types
WHERE tenant_id = $1 AND is_active = true
ORDER BY type_code ASC
`

func (q *Queries) GetRFQTypes(ctx context.Context, tenantID int64) ([]RfqDocumentType, error) {
	rows, err := q.db.Query(ctx, getRFQTypes, tenantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []RfqDocumentType{}
	for rows.Next() {
		var i RfqDocumentType
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.TypeCode,
			&i.Description,
			&i.IsGpBid,
			&i.IsActive,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateOrderReason = `-- name: UpdateOrderReason :one
UPDATE rfq_order_reasons
SET description = $3, is_active = $4
WHERE tenant_id = $1 AND reason_code = $2
RETURNING id, tenant_id, reason_code, description, is_active
`

type UpdateOrderReasonParams struct {
	TenantID    int64  `json:"tenant_id"`
	ReasonCode  string `json:"reason_code"`
	Description string `json:"description"`
	IsActive    bool   `json:"is_active"`
}

func (q *Queries) UpdateOrderReason(ctx context.Context, arg UpdateOrderReasonParams) (RfqOrderReason, error) {
	row := q.db.QueryRow(ctx, updateOrderReason,
		arg.TenantID,
		arg.ReasonCode,
		arg.Description,
		arg.IsActive,
	)
	var i RfqOrderReason
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.ReasonCode,
		&i.Description,
		&i.IsActive,
	)
	return i, err
}

const updateRFQType = `-- name: UpdateRFQType :one
UPDATE rfq_document_types
SET description = $3, is_gp_bid = $4, is_active = $5, created_at = now()
WHERE tenant_id = $1 AND type_code = $2
RETURNING id, tenant_id, type_code, description, is_gp_bid, is_active, created_at
`

type UpdateRFQTypeParams struct {
	TenantID    int64  `json:"tenant_id"`
	TypeCode    string `json:"type_code"`
	Description string `json:"description"`
	IsGpBid     bool   `json:"is_gp_bid"`
	IsActive    bool   `json:"is_active"`
}

func (q *Queries) UpdateRFQType(ctx context.Context, arg UpdateRFQTypeParams) (RfqDocumentType, error) {
	row := q.db.QueryRow(ctx, updateRFQType,
		arg.TenantID,
		arg.TypeCode,
		arg.Description,
		arg.IsGpBid,
		arg.IsActive,
	)
	var i RfqDocumentType
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.TypeCode,
		&i.Description,
		&i.IsGpBid,
		&i.IsActive,
		&i.CreatedAt,
	)
	return i, err
}
