// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.20.0
// source: sales_orders.sql

package dbgen

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const addSalesOrderLine = `-- name: AddSalesOrderLine :one
INSERT INTO sales_order_lines (
    sales_order_id, line_number, material_id,
    description, quantity, unit_of_measure,
    unit_price, discount_pct
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8
)
RETURNING id, public_id, sales_order_id, line_number, material_id, description, quantity, unit_of_measure, unit_price, discount_pct, line_total, delivered_qty, status, created_at
`

type AddSalesOrderLineParams struct {
	SalesOrderID  int64          `json:"sales_order_id"`
	LineNumber    int32          `json:"line_number"`
	MaterialID    pgtype.Int8    `json:"material_id"`
	Description   string         `json:"description"`
	Quantity      pgtype.Numeric `json:"quantity"`
	UnitOfMeasure string         `json:"unit_of_measure"`
	UnitPrice     pgtype.Numeric `json:"unit_price"`
	DiscountPct   pgtype.Numeric `json:"discount_pct"`
}

func (q *Queries) AddSalesOrderLine(ctx context.Context, arg AddSalesOrderLineParams) (SalesOrderLine, error) {
	row := q.db.QueryRow(ctx, addSalesOrderLine,
		arg.SalesOrderID,
		arg.LineNumber,
		arg.MaterialID,
		arg.Description,
		arg.Quantity,
		arg.UnitOfMeasure,
		arg.UnitPrice,
		arg.DiscountPct,
	)
	var i SalesOrderLine
	err := row.Scan(
		&i.ID,
		&i.PublicID,
		&i.SalesOrderID,
		&i.LineNumber,
		&i.MaterialID,
		&i.Description,
		&i.Quantity,
		&i.UnitOfMeasure,
		&i.UnitPrice,
		&i.DiscountPct,
		&i.LineTotal,
		&i.DeliveredQty,
		&i.Status,
		&i.CreatedAt,
	)
	return i, err
}

const cancelSalesOrder = `-- name: CancelSalesOrder :one
UPDATE sales_orders
SET status     = 'CANCELLED',
    updated_at = NOW()
WHERE id = $1
  AND status IN ('DRAFT', 'CONFIRMED')
  AND tenant_id = $2
RETURNING id, public_id, tenant_id, so_number, customer_id, status, order_date, requested_date, currency, subtotal, tax_amount, total_amount, notes, created_by, confirmed_at, confirmed_by, created_at, updated_at
`

type CancelSalesOrderParams struct {
	ID       int64 `json:"id"`
	TenantID int64 `json:"tenant_id"`
}

func (q *Queries) CancelSalesOrder(ctx context.Context, arg CancelSalesOrderParams) (SalesOrder, error) {
	row := q.db.QueryRow(ctx, cancelSalesOrder, arg.ID, arg.TenantID)
	var i SalesOrder
	err := row.Scan(
		&i.ID,
		&i.PublicID,
		&i.TenantID,
		&i.SoNumber,
		&i.CustomerID,
		&i.Status,
		&i.OrderDate,
		&i.RequestedDate,
		&i.Currency,
		&i.Subtotal,
		&i.TaxAmount,
		&i.TotalAmount,
		&i.Notes,
		&i.CreatedBy,
		&i.ConfirmedAt,
		&i.ConfirmedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const confirmSalesOrder = `-- name: ConfirmSalesOrder :one
UPDATE sales_orders
SET status       = 'CONFIRMED',
    confirmed_at = NOW(),
    confirmed_by = $2,
    updated_at   = NOW()
WHERE id = $1
  AND status = 'DRAFT'
  AND tenant_id = $3
RETURNING id, public_id, tenant_id, so_number, customer_id, status, order_date, requested_date, currency, subtotal, tax_amount, total_amount, notes, created_by, confirmed_at, confirmed_by, created_at, updated_at
`

type ConfirmSalesOrderParams struct {
	ID          int64       `json:"id"`
	ConfirmedBy pgtype.Int8 `json:"confirmed_by"`
	TenantID    int64       `json:"tenant_id"`
}

func (q *Queries) ConfirmSalesOrder(ctx context.Context, arg ConfirmSalesOrderParams) (SalesOrder, error) {
	row := q.db.QueryRow(ctx, confirmSalesOrder, arg.ID, arg.ConfirmedBy, arg.TenantID)
	var i SalesOrder
	err := row.Scan(
		&i.ID,
		&i.PublicID,
		&i.TenantID,
		&i.SoNumber,
		&i.CustomerID,
		&i.Status,
		&i.OrderDate,
		&i.RequestedDate,
		&i.Currency,
		&i.Subtotal,
		&i.TaxAmount,
		&i.TotalAmount,
		&i.Notes,
		&i.CreatedBy,
		&i.ConfirmedAt,
		&i.ConfirmedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createCustomer = `-- name: CreateCustomer :one
INSERT INTO customers (
    tenant_id, code, name, email, phone,
    address, city, country, currency, payment_terms, credit_limit
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11
)
RETURNING id, public_id, tenant_id, code, name, email, phone, address, city, country, currency, credit_limit, payment_terms, is_active, created_at, updated_at
`

type CreateCustomerParams struct {
	TenantID     int64          `json:"tenant_id"`
	Code         string         `json:"code"`
	Name         string         `json:"name"`
	Email        pgtype.Text    `json:"email"`
	Phone        pgtype.Text    `json:"phone"`
	Address      pgtype.Text    `json:"address"`
	City         pgtype.Text    `json:"city"`
	Country      pgtype.Text    `json:"country"`
	Currency     pgtype.Text    `json:"currency"`
	PaymentTerms pgtype.Text    `json:"payment_terms"`
	CreditLimit  pgtype.Numeric `json:"credit_limit"`
}

func (q *Queries) CreateCustomer(ctx context.Context, arg CreateCustomerParams) (Customer, error) {
	row := q.db.QueryRow(ctx, createCustomer,
		arg.TenantID,
		arg.Code,
		arg.Name,
		arg.Email,
		arg.Phone,
		arg.Address,
		arg.City,
		arg.Country,
		arg.Currency,
		arg.PaymentTerms,
		arg.CreditLimit,
	)
	var i Customer
	err := row.Scan(
		&i.ID,
		&i.PublicID,
		&i.TenantID,
		&i.Code,
		&i.Name,
		&i.Email,
		&i.Phone,
		&i.Address,
		&i.City,
		&i.Country,
		&i.Currency,
		&i.CreditLimit,
		&i.PaymentTerms,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createSalesOrder = `-- name: CreateSalesOrder :one
INSERT INTO sales_orders (
    tenant_id, customer_id, order_date,
    requested_date, currency, notes, created_by
) VALUES (
    $1, $2, $3, $4, $5, $6, $7
)
RETURNING id, public_id, tenant_id, so_number, customer_id, status, order_date, requested_date, currency, subtotal, tax_amount, total_amount, notes, created_by, confirmed_at, confirmed_by, created_at, updated_at
`

type CreateSalesOrderParams struct {
	TenantID      int64       `json:"tenant_id"`
	CustomerID    int64       `json:"customer_id"`
	OrderDate     pgtype.Date `json:"order_date"`
	RequestedDate pgtype.Date `json:"requested_date"`
	Currency      pgtype.Text `json:"currency"`
	Notes         pgtype.Text `json:"notes"`
	CreatedBy     pgtype.Int8 `json:"created_by"`
}

func (q *Queries) CreateSalesOrder(ctx context.Context, arg CreateSalesOrderParams) (SalesOrder, error) {
	row := q.db.QueryRow(ctx, createSalesOrder,
		arg.TenantID,
		arg.CustomerID,
		arg.OrderDate,
		arg.RequestedDate,
		arg.Currency,
		arg.Notes,
		arg.CreatedBy,
	)
	var i SalesOrder
	err := row.Scan(
		&i.ID,
		&i.PublicID,
		&i.TenantID,
		&i.SoNumber,
		&i.CustomerID,
		&i.Status,
		&i.OrderDate,
		&i.RequestedDate,
		&i.Currency,
		&i.Subtotal,
		&i.TaxAmount,
		&i.TotalAmount,
		&i.Notes,
		&i.CreatedBy,
		&i.ConfirmedAt,
		&i.ConfirmedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getCustomerByID = `-- name: GetCustomerByID :one
SELECT id, public_id, tenant_id, code, name, email, phone, address, city, country, currency, credit_limit, payment_terms, is_active, created_at, updated_at FROM customers
WHERE id = $1 AND tenant_id = $2
`

type GetCustomerByIDParams struct {
	ID       int64 `json:"id"`
	TenantID int64 `json:"tenant_id"`
}

func (q *Queries) GetCustomerByID(ctx context.Context, arg GetCustomerByIDParams) (Customer, error) {
	row := q.db.QueryRow(ctx, getCustomerByID, arg.ID, arg.TenantID)
	var i Customer
	err := row.Scan(
		&i.ID,
		&i.PublicID,
		&i.TenantID,
		&i.Code,
		&i.Name,
		&i.Email,
		&i.Phone,
		&i.Address,
		&i.City,
		&i.Country,
		&i.Currency,
		&i.CreditLimit,
		&i.PaymentTerms,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getDealFlowDashboard = `-- name: GetDealFlowDashboard :one
SELECT
    COUNT(*)                                              AS total_orders,
    COUNT(*) FILTER (WHERE status = 'DRAFT')             AS draft,
    COUNT(*) FILTER (WHERE status = 'CONFIRMED')         AS confirmed,
    COUNT(*) FILTER (WHERE status = 'DISPATCHED')        AS dispatched,
    COUNT(*) FILTER (WHERE status = 'DELIVERED')         AS delivered,
    COUNT(*) FILTER (WHERE status = 'CANCELLED')         AS cancelled,
    COALESCE(SUM(total_amount)
      FILTER (WHERE status != 'CANCELLED'), 0)           AS total_revenue,
    COALESCE(SUM(total_amount)
      FILTER (WHERE status = 'CONFIRMED'), 0)            AS pending_value,
    COALESCE(AVG(total_amount)
      FILTER (WHERE status != 'CANCELLED' AND status != 'DRAFT'), 0) AS avg_order_value
FROM sales_orders
WHERE tenant_id = $1
  AND created_at >= NOW() - INTERVAL '90 days'
`

type GetDealFlowDashboardRow struct {
	TotalOrders   int64       `json:"total_orders"`
	Draft         int64       `json:"draft"`
	Confirmed     int64       `json:"confirmed"`
	Dispatched    int64       `json:"dispatched"`
	Delivered     int64       `json:"delivered"`
	Cancelled     int64       `json:"cancelled"`
	TotalRevenue  interface{} `json:"total_revenue"`
	PendingValue  interface{} `json:"pending_value"`
	AvgOrderValue interface{} `json:"avg_order_value"`
}

func (q *Queries) GetDealFlowDashboard(ctx context.Context, tenantID int64) (GetDealFlowDashboardRow, error) {
	row := q.db.QueryRow(ctx, getDealFlowDashboard, tenantID)
	var i GetDealFlowDashboardRow
	err := row.Scan(
		&i.TotalOrders,
		&i.Draft,
		&i.Confirmed,
		&i.Dispatched,
		&i.Delivered,
		&i.Cancelled,
		&i.TotalRevenue,
		&i.PendingValue,
		&i.AvgOrderValue,
	)
	return i, err
}

const getSalesOrderLines = `-- name: GetSalesOrderLines :many
SELECT
    sol.id, sol.public_id, sol.sales_order_id, sol.line_number, sol.material_id, sol.description, sol.quantity, sol.unit_of_measure, sol.unit_price, sol.discount_pct, sol.line_total, sol.delivered_qty, sol.status, sol.created_at,
    m.code AS material_code,
    m.name AS material_name
FROM sales_order_lines sol
LEFT JOIN products m ON m.id = sol.material_id
WHERE sol.sales_order_id = $1
ORDER BY sol.line_number
`

type GetSalesOrderLinesRow struct {
	ID            int64              `json:"id"`
	PublicID      uuid.UUID          `json:"public_id"`
	SalesOrderID  int64              `json:"sales_order_id"`
	LineNumber    int32              `json:"line_number"`
	MaterialID    pgtype.Int8        `json:"material_id"`
	Description   string             `json:"description"`
	Quantity      pgtype.Numeric     `json:"quantity"`
	UnitOfMeasure string             `json:"unit_of_measure"`
	UnitPrice     pgtype.Numeric     `json:"unit_price"`
	DiscountPct   pgtype.Numeric     `json:"discount_pct"`
	LineTotal     pgtype.Numeric     `json:"line_total"`
	DeliveredQty  pgtype.Numeric     `json:"delivered_qty"`
	Status        pgtype.Text        `json:"status"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
	MaterialCode  pgtype.Text        `json:"material_code"`
	MaterialName  pgtype.Text        `json:"material_name"`
}

func (q *Queries) GetSalesOrderLines(ctx context.Context, salesOrderID int64) ([]GetSalesOrderLinesRow, error) {
	rows, err := q.db.Query(ctx, getSalesOrderLines, salesOrderID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetSalesOrderLinesRow{}
	for rows.Next() {
		var i GetSalesOrderLinesRow
		if err := rows.Scan(
			&i.ID,
			&i.PublicID,
			&i.SalesOrderID,
			&i.LineNumber,
			&i.MaterialID,
			&i.Description,
			&i.Quantity,
			&i.UnitOfMeasure,
			&i.UnitPrice,
			&i.DiscountPct,
			&i.LineTotal,
			&i.DeliveredQty,
			&i.Status,
			&i.CreatedAt,
			&i.MaterialCode,
			&i.MaterialName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getSalesOrderWithLines = `-- name: GetSalesOrderWithLines :one
SELECT
    so.id, so.public_id, so.tenant_id, so.so_number, so.customer_id, so.status, so.order_date, so.requested_date, so.currency, so.subtotal, so.tax_amount, so.total_amount, so.notes, so.created_by, so.confirmed_at, so.confirmed_by, so.created_at, so.updated_at,
    c.name  AS customer_name,
    c.code  AS customer_code,
    c.email AS customer_email
FROM sales_orders so
JOIN customers c ON c.id = so.customer_id
WHERE so.public_id = $1 AND so.tenant_id = $2
`

type GetSalesOrderWithLinesParams struct {
	PublicID uuid.UUID `json:"public_id"`
	TenantID int64     `json:"tenant_id"`
}

type GetSalesOrderWithLinesRow struct {
	ID            int64              `json:"id"`
	PublicID      uuid.UUID          `json:"public_id"`
	TenantID      int64              `json:"tenant_id"`
	SoNumber      string             `json:"so_number"`
	CustomerID    int64              `json:"customer_id"`
	Status        string             `json:"status"`
	OrderDate     pgtype.Date        `json:"order_date"`
	RequestedDate pgtype.Date        `json:"requested_date"`
	Currency      pgtype.Text        `json:"currency"`
	Subtotal      pgtype.Numeric     `json:"subtotal"`
	TaxAmount     pgtype.Numeric     `json:"tax_amount"`
	TotalAmount   pgtype.Numeric     `json:"total_amount"`
	Notes         pgtype.Text        `json:"notes"`
	CreatedBy     pgtype.Int8        `json:"created_by"`
	ConfirmedAt   pgtype.Timestamptz `json:"confirmed_at"`
	ConfirmedBy   pgtype.Int8        `json:"confirmed_by"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
	UpdatedAt     pgtype.Timestamptz `json:"updated_at"`
	CustomerName  string             `json:"customer_name"`
	CustomerCode  string             `json:"customer_code"`
	CustomerEmail pgtype.Text        `json:"customer_email"`
}

func (q *Queries) GetSalesOrderWithLines(ctx context.Context, arg GetSalesOrderWithLinesParams) (GetSalesOrderWithLinesRow, error) {
	row := q.db.QueryRow(ctx, getSalesOrderWithLines, arg.PublicID, arg.TenantID)
	var i GetSalesOrderWithLinesRow
	err := row.Scan(
		&i.ID,
		&i.PublicID,
		&i.TenantID,
		&i.SoNumber,
		&i.CustomerID,
		&i.Status,
		&i.OrderDate,
		&i.RequestedDate,
		&i.Currency,
		&i.Subtotal,
		&i.TaxAmount,
		&i.TotalAmount,
		&i.Notes,
		&i.CreatedBy,
		&i.ConfirmedAt,
		&i.ConfirmedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CustomerName,
		&i.CustomerCode,
		&i.CustomerEmail,
	)
	return i, err
}

const listCustomers = `-- name: ListCustomers :many
SELECT id, public_id, tenant_id, code, name, email, phone, address, city, country, currency, credit_limit, payment_terms, is_active, created_at, updated_at FROM customers
WHERE tenant_id = $1 AND is_active = true
ORDER BY name ASC
`

func (q *Queries) ListCustomers(ctx context.Context, tenantID int64) ([]Customer, error) {
	rows, err := q.db.Query(ctx, listCustomers, tenantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Customer{}
	for rows.Next() {
		var i Customer
		if err := rows.Scan(
			&i.ID,
			&i.PublicID,
			&i.TenantID,
			&i.Code,
			&i.Name,
			&i.Email,
			&i.Phone,
			&i.Address,
			&i.City,
			&i.Country,
			&i.Currency,
			&i.CreditLimit,
			&i.PaymentTerms,
			&i.IsActive,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSalesOrders = `-- name: ListSalesOrders :many
SELECT
    so.id, so.public_id, so.tenant_id, so.so_number, so.customer_id, so.status, so.order_date, so.requested_date, so.currency, so.subtotal, so.tax_amount, so.total_amount, so.notes, so.created_by, so.confirmed_at, so.confirmed_by, so.created_at, so.updated_at,
    c.name  AS customer_name,
    c.code  AS customer_code,
    c.email AS customer_email,
    (SELECT COUNT(*) FROM sales_order_lines sol
     WHERE sol.sales_order_id = so.id) AS line_count
FROM sales_orders so
JOIN customers c ON c.id = so.customer_id
WHERE so.tenant_id = $1
ORDER BY so.created_at DESC
LIMIT $2 OFFSET $3
`

type ListSalesOrdersParams struct {
	TenantID int64 `json:"tenant_id"`
	Limit    int32 `json:"limit"`
	Offset   int32 `json:"offset"`
}

type ListSalesOrdersRow struct {
	ID            int64              `json:"id"`
	PublicID      uuid.UUID          `json:"public_id"`
	TenantID      int64              `json:"tenant_id"`
	SoNumber      string             `json:"so_number"`
	CustomerID    int64              `json:"customer_id"`
	Status        string             `json:"status"`
	OrderDate     pgtype.Date        `json:"order_date"`
	RequestedDate pgtype.Date        `json:"requested_date"`
	Currency      pgtype.Text        `json:"currency"`
	Subtotal      pgtype.Numeric     `json:"subtotal"`
	TaxAmount     pgtype.Numeric     `json:"tax_amount"`
	TotalAmount   pgtype.Numeric     `json:"total_amount"`
	Notes         pgtype.Text        `json:"notes"`
	CreatedBy     pgtype.Int8        `json:"created_by"`
	ConfirmedAt   pgtype.Timestamptz `json:"confirmed_at"`
	ConfirmedBy   pgtype.Int8        `json:"confirmed_by"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
	UpdatedAt     pgtype.Timestamptz `json:"updated_at"`
	CustomerName  string             `json:"customer_name"`
	CustomerCode  string             `json:"customer_code"`
	CustomerEmail pgtype.Text        `json:"customer_email"`
	LineCount     int64              `json:"line_count"`
}

func (q *Queries) ListSalesOrders(ctx context.Context, arg ListSalesOrdersParams) ([]ListSalesOrdersRow, error) {
	rows, err := q.db.Query(ctx, listSalesOrders, arg.TenantID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListSalesOrdersRow{}
	for rows.Next() {
		var i ListSalesOrdersRow
		if err := rows.Scan(
			&i.ID,
			&i.PublicID,
			&i.TenantID,
			&i.SoNumber,
			&i.CustomerID,
			&i.Status,
			&i.OrderDate,
			&i.RequestedDate,
			&i.Currency,
			&i.Subtotal,
			&i.TaxAmount,
			&i.TotalAmount,
			&i.Notes,
			&i.CreatedBy,
			&i.ConfirmedAt,
			&i.ConfirmedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.CustomerName,
			&i.CustomerCode,
			&i.CustomerEmail,
			&i.LineCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateSalesOrderStatus = `-- name: UpdateSalesOrderStatus :one
UPDATE sales_orders
SET status     = $2,
    updated_at = NOW()
WHERE id = $1 AND tenant_id = $3
RETURNING id, public_id, tenant_id, so_number, customer_id, status, order_date, requested_date, currency, subtotal, tax_amount, total_amount, notes, created_by, confirmed_at, confirmed_by, created_at, updated_at
`

type UpdateSalesOrderStatusParams struct {
	ID       int64  `json:"id"`
	Status   string `json:"status"`
	TenantID int64  `json:"tenant_id"`
}

func (q *Queries) UpdateSalesOrderStatus(ctx context.Context, arg UpdateSalesOrderStatusParams) (SalesOrder, error) {
	row := q.db.QueryRow(ctx, updateSalesOrderStatus, arg.ID, arg.Status, arg.TenantID)
	var i SalesOrder
	err := row.Scan(
		&i.ID,
		&i.PublicID,
		&i.TenantID,
		&i.SoNumber,
		&i.CustomerID,
		&i.Status,
		&i.OrderDate,
		&i.RequestedDate,
		&i.Currency,
		&i.Subtotal,
		&i.TaxAmount,
		&i.TotalAmount,
		&i.Notes,
		&i.CreatedBy,
		&i.ConfirmedAt,
		&i.ConfirmedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
