// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.20.0
// source: schema.sql

package dbgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createInventoryEvent = `-- name: CreateInventoryEvent :one
INSERT INTO inventory_events (
    tenant_id, event_type, hu_id, child_hu_id, 
    from_location_id, to_location_id, quantity, unit, 
    actor_user_id, reference_doc, metadata
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11
) RETURNING id, tenant_id, event_type, hu_id, child_hu_id, product_id, from_location_id, to_location_id, quantity, unit, actor_user_id, reference_doc, metadata, created_at, site_id, zone_id, from_zone_id, to_zone_id, notes
`

type CreateInventoryEventParams struct {
	TenantID       pgtype.Int8    `json:"tenant_id"`
	EventType      string         `json:"event_type"`
	HuID           pgtype.Int8    `json:"hu_id"`
	ChildHuID      pgtype.Int8    `json:"child_hu_id"`
	FromLocationID pgtype.Int8    `json:"from_location_id"`
	ToLocationID   pgtype.Int8    `json:"to_location_id"`
	Quantity       pgtype.Numeric `json:"quantity"`
	Unit           pgtype.Text    `json:"unit"`
	ActorUserID    pgtype.Int8    `json:"actor_user_id"`
	ReferenceDoc   pgtype.Text    `json:"reference_doc"`
	Metadata       []byte         `json:"metadata"`
}

func (q *Queries) CreateInventoryEvent(ctx context.Context, arg CreateInventoryEventParams) (InventoryEvent, error) {
	row := q.db.QueryRow(ctx, createInventoryEvent,
		arg.TenantID,
		arg.EventType,
		arg.HuID,
		arg.ChildHuID,
		arg.FromLocationID,
		arg.ToLocationID,
		arg.Quantity,
		arg.Unit,
		arg.ActorUserID,
		arg.ReferenceDoc,
		arg.Metadata,
	)
	var i InventoryEvent
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.EventType,
		&i.HuID,
		&i.ChildHuID,
		&i.ProductID,
		&i.FromLocationID,
		&i.ToLocationID,
		&i.Quantity,
		&i.Unit,
		&i.ActorUserID,
		&i.ReferenceDoc,
		&i.Metadata,
		&i.CreatedAt,
		&i.SiteID,
		&i.ZoneID,
		&i.FromZoneID,
		&i.ToZoneID,
		&i.Notes,
	)
	return i, err
}

const getBarcode = `-- name: GetBarcode :one
SELECT id, tenant_id, code, entity_type, entity_id, is_active, created_at FROM barcodes
WHERE tenant_id = $1 AND code = $2 AND is_active = true LIMIT 1
`

type GetBarcodeParams struct {
	TenantID pgtype.Int8 `json:"tenant_id"`
	Code     string      `json:"code"`
}

func (q *Queries) GetBarcode(ctx context.Context, arg GetBarcodeParams) (Barcode, error) {
	row := q.db.QueryRow(ctx, getBarcode, arg.TenantID, arg.Code)
	var i Barcode
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Code,
		&i.EntityType,
		&i.EntityID,
		&i.IsActive,
		&i.CreatedAt,
	)
	return i, err
}

const getHUByBarcode = `-- name: GetHUByBarcode :one
SELECT hu.id, hu.public_id, hu.tenant_id, hu.parent_hu_id, hu.product_id, hu.batch_id, hu.location_id, hu.code, hu.quantity, hu.unit, hu.status, hu.label_version, hu.created_at, hu.updated_at, hu.site_id, hu.zone_id, hu.consumed_at, hu.consumed_by
FROM handling_units hu
JOIN barcodes b ON b.entity_id = hu.id AND b.entity_type = 'HU'
WHERE b.tenant_id = $1 AND b.code = $2 AND b.is_active = true LIMIT 1
`

type GetHUByBarcodeParams struct {
	TenantID pgtype.Int8 `json:"tenant_id"`
	Code     string      `json:"code"`
}

func (q *Queries) GetHUByBarcode(ctx context.Context, arg GetHUByBarcodeParams) (HandlingUnit, error) {
	row := q.db.QueryRow(ctx, getHUByBarcode, arg.TenantID, arg.Code)
	var i HandlingUnit
	err := row.Scan(
		&i.ID,
		&i.PublicID,
		&i.TenantID,
		&i.ParentHuID,
		&i.ProductID,
		&i.BatchID,
		&i.LocationID,
		&i.Code,
		&i.Quantity,
		&i.Unit,
		&i.Status,
		&i.LabelVersion,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.SiteID,
		&i.ZoneID,
		&i.ConsumedAt,
		&i.ConsumedBy,
	)
	return i, err
}

const getHUByID = `-- name: GetHUByID :one
SELECT id, public_id, tenant_id, parent_hu_id, product_id, batch_id, location_id, code, quantity, unit, status, label_version, created_at, updated_at, site_id, zone_id, consumed_at, consumed_by FROM handling_units
WHERE id = $1 LIMIT 1
`

func (q *Queries) GetHUByID(ctx context.Context, id int64) (HandlingUnit, error) {
	row := q.db.QueryRow(ctx, getHUByID, id)
	var i HandlingUnit
	err := row.Scan(
		&i.ID,
		&i.PublicID,
		&i.TenantID,
		&i.ParentHuID,
		&i.ProductID,
		&i.BatchID,
		&i.LocationID,
		&i.Code,
		&i.Quantity,
		&i.Unit,
		&i.Status,
		&i.LabelVersion,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.SiteID,
		&i.ZoneID,
		&i.ConsumedAt,
		&i.ConsumedBy,
	)
	return i, err
}

const getHUWithDetails = `-- name: GetHUWithDetails :one
SELECT 
    hu.id, hu.public_id, hu.tenant_id, hu.parent_hu_id, hu.product_id, hu.batch_id, hu.location_id, hu.code, hu.quantity, hu.unit, hu.status, hu.label_version, hu.created_at, hu.updated_at, hu.site_id, hu.zone_id, hu.consumed_at, hu.consumed_by,
    p.code as product_code,
    p.name as product_name,
    l.code as location_code
FROM handling_units hu
JOIN products p ON hu.product_id = p.id
JOIN locations l ON hu.location_id = l.id
WHERE hu.id = $1 LIMIT 1
`

type GetHUWithDetailsRow struct {
	ID           int64              `json:"id"`
	PublicID     pgtype.UUID        `json:"public_id"`
	TenantID     pgtype.Int8        `json:"tenant_id"`
	ParentHuID   pgtype.Int8        `json:"parent_hu_id"`
	ProductID    pgtype.Int8        `json:"product_id"`
	BatchID      pgtype.Int8        `json:"batch_id"`
	LocationID   pgtype.Int8        `json:"location_id"`
	Code         pgtype.Text        `json:"code"`
	Quantity     pgtype.Numeric     `json:"quantity"`
	Unit         string             `json:"unit"`
	Status       string             `json:"status"`
	LabelVersion int32              `json:"label_version"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
	SiteID       pgtype.Int8        `json:"site_id"`
	ZoneID       pgtype.Int8        `json:"zone_id"`
	ConsumedAt   pgtype.Timestamptz `json:"consumed_at"`
	ConsumedBy   pgtype.Int8        `json:"consumed_by"`
	ProductCode  string             `json:"product_code"`
	ProductName  string             `json:"product_name"`
	LocationCode string             `json:"location_code"`
}

func (q *Queries) GetHUWithDetails(ctx context.Context, id int64) (GetHUWithDetailsRow, error) {
	row := q.db.QueryRow(ctx, getHUWithDetails, id)
	var i GetHUWithDetailsRow
	err := row.Scan(
		&i.ID,
		&i.PublicID,
		&i.TenantID,
		&i.ParentHuID,
		&i.ProductID,
		&i.BatchID,
		&i.LocationID,
		&i.Code,
		&i.Quantity,
		&i.Unit,
		&i.Status,
		&i.LabelVersion,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.SiteID,
		&i.ZoneID,
		&i.ConsumedAt,
		&i.ConsumedBy,
		&i.ProductCode,
		&i.ProductName,
		&i.LocationCode,
	)
	return i, err
}

const getLocationByBarcode = `-- name: GetLocationByBarcode :one
SELECT l.id, l.public_id, l.tenant_id, l.warehouse_id, l.code, l.zone, l.capacity, l.unit, l.is_active
FROM locations l
JOIN barcodes b ON b.entity_id = l.id AND b.entity_type = 'LOCATION'
WHERE b.tenant_id = $1 AND b.code = $2 AND b.is_active = true LIMIT 1
`

type GetLocationByBarcodeParams struct {
	TenantID pgtype.Int8 `json:"tenant_id"`
	Code     string      `json:"code"`
}

func (q *Queries) GetLocationByBarcode(ctx context.Context, arg GetLocationByBarcodeParams) (Location, error) {
	row := q.db.QueryRow(ctx, getLocationByBarcode, arg.TenantID, arg.Code)
	var i Location
	err := row.Scan(
		&i.ID,
		&i.PublicID,
		&i.TenantID,
		&i.WarehouseID,
		&i.Code,
		&i.Zone,
		&i.Capacity,
		&i.Unit,
		&i.IsActive,
	)
	return i, err
}

const getLocationStock = `-- name: GetLocationStock :many
SELECT 
    hu.id, hu.public_id, hu.tenant_id, hu.parent_hu_id, hu.product_id, hu.batch_id, hu.location_id, hu.code, hu.quantity, hu.unit, hu.status, hu.label_version, hu.created_at, hu.updated_at, hu.site_id, hu.zone_id, hu.consumed_at, hu.consumed_by,
    p.code as product_code,
    p.name as product_name
FROM handling_units hu
JOIN products p ON hu.product_id = p.id
WHERE hu.location_id = $1 AND hu.quantity > 0
`

type GetLocationStockRow struct {
	ID           int64              `json:"id"`
	PublicID     pgtype.UUID        `json:"public_id"`
	TenantID     pgtype.Int8        `json:"tenant_id"`
	ParentHuID   pgtype.Int8        `json:"parent_hu_id"`
	ProductID    pgtype.Int8        `json:"product_id"`
	BatchID      pgtype.Int8        `json:"batch_id"`
	LocationID   pgtype.Int8        `json:"location_id"`
	Code         pgtype.Text        `json:"code"`
	Quantity     pgtype.Numeric     `json:"quantity"`
	Unit         string             `json:"unit"`
	Status       string             `json:"status"`
	LabelVersion int32              `json:"label_version"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
	SiteID       pgtype.Int8        `json:"site_id"`
	ZoneID       pgtype.Int8        `json:"zone_id"`
	ConsumedAt   pgtype.Timestamptz `json:"consumed_at"`
	ConsumedBy   pgtype.Int8        `json:"consumed_by"`
	ProductCode  string             `json:"product_code"`
	ProductName  string             `json:"product_name"`
}

func (q *Queries) GetLocationStock(ctx context.Context, locationID pgtype.Int8) ([]GetLocationStockRow, error) {
	rows, err := q.db.Query(ctx, getLocationStock, locationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetLocationStockRow{}
	for rows.Next() {
		var i GetLocationStockRow
		if err := rows.Scan(
			&i.ID,
			&i.PublicID,
			&i.TenantID,
			&i.ParentHuID,
			&i.ProductID,
			&i.BatchID,
			&i.LocationID,
			&i.Code,
			&i.Quantity,
			&i.Unit,
			&i.Status,
			&i.LabelVersion,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.SiteID,
			&i.ZoneID,
			&i.ConsumedAt,
			&i.ConsumedBy,
			&i.ProductCode,
			&i.ProductName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getTenantByID = `-- name: GetTenantByID :one
SELECT id, public_id, name, slug, created_at FROM tenants
WHERE id = $1 LIMIT 1
`

func (q *Queries) GetTenantByID(ctx context.Context, id int64) (Tenant, error) {
	row := q.db.QueryRow(ctx, getTenantByID, id)
	var i Tenant
	err := row.Scan(
		&i.ID,
		&i.PublicID,
		&i.Name,
		&i.Slug,
		&i.CreatedAt,
	)
	return i, err
}

const getTenantBySlug = `-- name: GetTenantBySlug :one
SELECT id, public_id, name, slug, created_at FROM tenants
WHERE slug = $1 LIMIT 1
`

func (q *Queries) GetTenantBySlug(ctx context.Context, slug string) (Tenant, error) {
	row := q.db.QueryRow(ctx, getTenantBySlug, slug)
	var i Tenant
	err := row.Scan(
		&i.ID,
		&i.PublicID,
		&i.Name,
		&i.Slug,
		&i.CreatedAt,
	)
	return i, err
}

const getUserByUsername = `-- name: GetUserByUsername :one
SELECT id, public_id, tenant_id, username, email, password_hash, created_at FROM users
WHERE username = $1 LIMIT 1
`

func (q *Queries) GetUserByUsername(ctx context.Context, username string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByUsername, username)
	var i User
	err := row.Scan(
		&i.ID,
		&i.PublicID,
		&i.TenantID,
		&i.Username,
		&i.Email,
		&i.PasswordHash,
		&i.CreatedAt,
	)
	return i, err
}

const getUserRoles = `-- name: GetUserRoles :many
SELECT r.name 
FROM roles r
JOIN user_roles ur ON r.id = ur.role_id
WHERE ur.user_id = $1
`

func (q *Queries) GetUserRoles(ctx context.Context, userID int64) ([]string, error) {
	rows, err := q.db.Query(ctx, getUserRoles, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var name string
		if err := rows.Scan(&name); err != nil {
			return nil, err
		}
		items = append(items, name)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listLocations = `-- name: ListLocations :many
SELECT id, public_id, tenant_id, warehouse_id, code, zone, capacity, unit, is_active FROM locations
WHERE tenant_id = $1 AND is_active = true
ORDER BY code ASC
`

func (q *Queries) ListLocations(ctx context.Context, tenantID pgtype.Int8) ([]Location, error) {
	rows, err := q.db.Query(ctx, listLocations, tenantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Location{}
	for rows.Next() {
		var i Location
		if err := rows.Scan(
			&i.ID,
			&i.PublicID,
			&i.TenantID,
			&i.WarehouseID,
			&i.Code,
			&i.Zone,
			&i.Capacity,
			&i.Unit,
			&i.IsActive,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRecentEvents = `-- name: ListRecentEvents :many
SELECT 
    e.id, e.tenant_id, e.event_type, e.hu_id, e.child_hu_id, e.product_id, e.from_location_id, e.to_location_id, e.quantity, e.unit, e.actor_user_id, e.reference_doc, e.metadata, e.created_at, e.site_id, e.zone_id, e.from_zone_id, e.to_zone_id, e.notes,
    u.username as actor_name,
    hu.public_id as hu_public_id
FROM inventory_events e
LEFT JOIN users u ON e.actor_user_id = u.id
LEFT JOIN handling_units hu ON e.hu_id = hu.id
WHERE e.tenant_id = $1
ORDER BY e.created_at DESC
LIMIT $2
`

type ListRecentEventsParams struct {
	TenantID pgtype.Int8 `json:"tenant_id"`
	Limit    int32       `json:"limit"`
}

type ListRecentEventsRow struct {
	ID             pgtype.Int8        `json:"id"`
	TenantID       pgtype.Int8        `json:"tenant_id"`
	EventType      string             `json:"event_type"`
	HuID           pgtype.Int8        `json:"hu_id"`
	ChildHuID      pgtype.Int8        `json:"child_hu_id"`
	ProductID      pgtype.Int8        `json:"product_id"`
	FromLocationID pgtype.Int8        `json:"from_location_id"`
	ToLocationID   pgtype.Int8        `json:"to_location_id"`
	Quantity       pgtype.Numeric     `json:"quantity"`
	Unit           pgtype.Text        `json:"unit"`
	ActorUserID    pgtype.Int8        `json:"actor_user_id"`
	ReferenceDoc   pgtype.Text        `json:"reference_doc"`
	Metadata       []byte             `json:"metadata"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	SiteID         pgtype.Int8        `json:"site_id"`
	ZoneID         pgtype.Int8        `json:"zone_id"`
	FromZoneID     pgtype.Int8        `json:"from_zone_id"`
	ToZoneID       pgtype.Int8        `json:"to_zone_id"`
	Notes          pgtype.Text        `json:"notes"`
	ActorName      pgtype.Text        `json:"actor_name"`
	HuPublicID     pgtype.UUID        `json:"hu_public_id"`
}

func (q *Queries) ListRecentEvents(ctx context.Context, arg ListRecentEventsParams) ([]ListRecentEventsRow, error) {
	rows, err := q.db.Query(ctx, listRecentEvents, arg.TenantID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListRecentEventsRow{}
	for rows.Next() {
		var i ListRecentEventsRow
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.EventType,
			&i.HuID,
			&i.ChildHuID,
			&i.ProductID,
			&i.FromLocationID,
			&i.ToLocationID,
			&i.Quantity,
			&i.Unit,
			&i.ActorUserID,
			&i.ReferenceDoc,
			&i.Metadata,
			&i.CreatedAt,
			&i.SiteID,
			&i.ZoneID,
			&i.FromZoneID,
			&i.ToZoneID,
			&i.Notes,
			&i.ActorName,
			&i.HuPublicID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRecentHUs = `-- name: ListRecentHUs :many
SELECT 
    hu.id, hu.public_id, hu.tenant_id, hu.parent_hu_id, hu.product_id, hu.batch_id, hu.location_id, hu.code, hu.quantity, hu.unit, hu.status, hu.label_version, hu.created_at, hu.updated_at, hu.site_id, hu.zone_id, hu.consumed_at, hu.consumed_by,
    p.code as product_code,
    l.code as location_code
FROM handling_units hu
JOIN products p ON hu.product_id = p.id
JOIN locations l ON hu.location_id = l.id
WHERE hu.tenant_id = $1
ORDER BY hu.updated_at DESC
LIMIT $2
`

type ListRecentHUsParams struct {
	TenantID pgtype.Int8 `json:"tenant_id"`
	Limit    int32       `json:"limit"`
}

type ListRecentHUsRow struct {
	ID           int64              `json:"id"`
	PublicID     pgtype.UUID        `json:"public_id"`
	TenantID     pgtype.Int8        `json:"tenant_id"`
	ParentHuID   pgtype.Int8        `json:"parent_hu_id"`
	ProductID    pgtype.Int8        `json:"product_id"`
	BatchID      pgtype.Int8        `json:"batch_id"`
	LocationID   pgtype.Int8        `json:"location_id"`
	Code         pgtype.Text        `json:"code"`
	Quantity     pgtype.Numeric     `json:"quantity"`
	Unit         string             `json:"unit"`
	Status       string             `json:"status"`
	LabelVersion int32              `json:"label_version"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
	SiteID       pgtype.Int8        `json:"site_id"`
	ZoneID       pgtype.Int8        `json:"zone_id"`
	ConsumedAt   pgtype.Timestamptz `json:"consumed_at"`
	ConsumedBy   pgtype.Int8        `json:"consumed_by"`
	ProductCode  string             `json:"product_code"`
	LocationCode string             `json:"location_code"`
}

func (q *Queries) ListRecentHUs(ctx context.Context, arg ListRecentHUsParams) ([]ListRecentHUsRow, error) {
	rows, err := q.db.Query(ctx, listRecentHUs, arg.TenantID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListRecentHUsRow{}
	for rows.Next() {
		var i ListRecentHUsRow
		if err := rows.Scan(
			&i.ID,
			&i.PublicID,
			&i.TenantID,
			&i.ParentHuID,
			&i.ProductID,
			&i.BatchID,
			&i.LocationID,
			&i.Code,
			&i.Quantity,
			&i.Unit,
			&i.Status,
			&i.LabelVersion,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.SiteID,
			&i.ZoneID,
			&i.ConsumedAt,
			&i.ConsumedBy,
			&i.ProductCode,
			&i.LocationCode,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateHULocation = `-- name: UpdateHULocation :exec
UPDATE handling_units
SET location_id = $2, updated_at = now()
WHERE id = $1
`

type UpdateHULocationParams struct {
	ID         int64       `json:"id"`
	LocationID pgtype.Int8 `json:"location_id"`
}

func (q *Queries) UpdateHULocation(ctx context.Context, arg UpdateHULocationParams) error {
	_, err := q.db.Exec(ctx, updateHULocation, arg.ID, arg.LocationID)
	return err
}

const updateHUStatus = `-- name: UpdateHUStatus :exec
UPDATE handling_units
SET status = $2, updated_at = now()
WHERE id = $1
`

type UpdateHUStatusParams struct {
	ID     int64  `json:"id"`
	Status string `json:"status"`
}

func (q *Queries) UpdateHUStatus(ctx context.Context, arg UpdateHUStatusParams) error {
	_, err := q.db.Exec(ctx, updateHUStatus, arg.ID, arg.Status)
	return err
}
