// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: shipments.sql

package dbgen

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const addShipmentLine = `-- name: AddShipmentLine :one
INSERT INTO shipment_lines (
    shipment_id, sales_order_line_id, line_number,
    description, quantity, unit_of_measure, material_id
) VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, public_id, shipment_id, sales_order_line_id, line_number, description, quantity, unit_of_measure, material_id, created_at
`

type AddShipmentLineParams struct {
	ShipmentID       int64          `json:"shipment_id"`
	SalesOrderLineID pgtype.Int8    `json:"sales_order_line_id"`
	LineNumber       int32          `json:"line_number"`
	Description      string         `json:"description"`
	Quantity         pgtype.Numeric `json:"quantity"`
	UnitOfMeasure    string         `json:"unit_of_measure"`
	MaterialID       pgtype.Int8    `json:"material_id"`
}

func (q *Queries) AddShipmentLine(ctx context.Context, arg AddShipmentLineParams) (ShipmentLine, error) {
	row := q.db.QueryRow(ctx, addShipmentLine,
		arg.ShipmentID,
		arg.SalesOrderLineID,
		arg.LineNumber,
		arg.Description,
		arg.Quantity,
		arg.UnitOfMeasure,
		arg.MaterialID,
	)
	var i ShipmentLine
	err := row.Scan(
		&i.ID,
		&i.PublicID,
		&i.ShipmentID,
		&i.SalesOrderLineID,
		&i.LineNumber,
		&i.Description,
		&i.Quantity,
		&i.UnitOfMeasure,
		&i.MaterialID,
		&i.CreatedAt,
	)
	return i, err
}

const assignCarrier = `-- name: AssignCarrier :one
UPDATE shipments
SET carrier_id   = $2,
    tracking_ref = $3,
    planned_date = $4,
    updated_at   = NOW()
WHERE id = $1 AND tenant_id = $5
  AND status IN ('PENDING','PICKING','PACKED')
RETURNING id, public_id, tenant_id, shipment_number, sales_order_id, carrier_id, status, ship_from_site, ship_to_address, ship_to_city, ship_to_country, tracking_ref, planned_date, dispatched_at, delivered_at, notes, created_by, created_at, updated_at
`

type AssignCarrierParams struct {
	ID          int64       `json:"id"`
	CarrierID   pgtype.Int8 `json:"carrier_id"`
	TrackingRef pgtype.Text `json:"tracking_ref"`
	PlannedDate pgtype.Date `json:"planned_date"`
	TenantID    int64       `json:"tenant_id"`
}

func (q *Queries) AssignCarrier(ctx context.Context, arg AssignCarrierParams) (Shipment, error) {
	row := q.db.QueryRow(ctx, assignCarrier,
		arg.ID,
		arg.CarrierID,
		arg.TrackingRef,
		arg.PlannedDate,
		arg.TenantID,
	)
	var i Shipment
	err := row.Scan(
		&i.ID,
		&i.PublicID,
		&i.TenantID,
		&i.ShipmentNumber,
		&i.SalesOrderID,
		&i.CarrierID,
		&i.Status,
		&i.ShipFromSite,
		&i.ShipToAddress,
		&i.ShipToCity,
		&i.ShipToCountry,
		&i.TrackingRef,
		&i.PlannedDate,
		&i.DispatchedAt,
		&i.DeliveredAt,
		&i.Notes,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createCarrier = `-- name: CreateCarrier :one
INSERT INTO carriers (
    tenant_id, code, name, mode,
    tracking_url, contact_name, contact_email, contact_phone
) VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
RETURNING id, public_id, tenant_id, code, name, mode, tracking_url, contact_name, contact_email, contact_phone, is_active, created_at
`

type CreateCarrierParams struct {
	TenantID     int64       `json:"tenant_id"`
	Code         string      `json:"code"`
	Name         string      `json:"name"`
	Mode         string      `json:"mode"`
	TrackingUrl  pgtype.Text `json:"tracking_url"`
	ContactName  pgtype.Text `json:"contact_name"`
	ContactEmail pgtype.Text `json:"contact_email"`
	ContactPhone pgtype.Text `json:"contact_phone"`
}

func (q *Queries) CreateCarrier(ctx context.Context, arg CreateCarrierParams) (Carrier, error) {
	row := q.db.QueryRow(ctx, createCarrier,
		arg.TenantID,
		arg.Code,
		arg.Name,
		arg.Mode,
		arg.TrackingUrl,
		arg.ContactName,
		arg.ContactEmail,
		arg.ContactPhone,
	)
	var i Carrier
	err := row.Scan(
		&i.ID,
		&i.PublicID,
		&i.TenantID,
		&i.Code,
		&i.Name,
		&i.Mode,
		&i.TrackingUrl,
		&i.ContactName,
		&i.ContactEmail,
		&i.ContactPhone,
		&i.IsActive,
		&i.CreatedAt,
	)
	return i, err
}

const createShipment = `-- name: CreateShipment :one
INSERT INTO shipments (
    tenant_id, sales_order_id, carrier_id,
    ship_to_address, ship_to_city, ship_to_country,
    planned_date, notes, created_by
) VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)
RETURNING id, public_id, tenant_id, shipment_number, sales_order_id, carrier_id, status, ship_from_site, ship_to_address, ship_to_city, ship_to_country, tracking_ref, planned_date, dispatched_at, delivered_at, notes, created_by, created_at, updated_at
`

type CreateShipmentParams struct {
	TenantID      int64       `json:"tenant_id"`
	SalesOrderID  pgtype.Int8 `json:"sales_order_id"`
	CarrierID     pgtype.Int8 `json:"carrier_id"`
	ShipToAddress pgtype.Text `json:"ship_to_address"`
	ShipToCity    pgtype.Text `json:"ship_to_city"`
	ShipToCountry pgtype.Text `json:"ship_to_country"`
	PlannedDate   pgtype.Date `json:"planned_date"`
	Notes         pgtype.Text `json:"notes"`
	CreatedBy     pgtype.Int8 `json:"created_by"`
}

func (q *Queries) CreateShipment(ctx context.Context, arg CreateShipmentParams) (Shipment, error) {
	row := q.db.QueryRow(ctx, createShipment,
		arg.TenantID,
		arg.SalesOrderID,
		arg.CarrierID,
		arg.ShipToAddress,
		arg.ShipToCity,
		arg.ShipToCountry,
		arg.PlannedDate,
		arg.Notes,
		arg.CreatedBy,
	)
	var i Shipment
	err := row.Scan(
		&i.ID,
		&i.PublicID,
		&i.TenantID,
		&i.ShipmentNumber,
		&i.SalesOrderID,
		&i.CarrierID,
		&i.Status,
		&i.ShipFromSite,
		&i.ShipToAddress,
		&i.ShipToCity,
		&i.ShipToCountry,
		&i.TrackingRef,
		&i.PlannedDate,
		&i.DispatchedAt,
		&i.DeliveredAt,
		&i.Notes,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const dispatchShipment = `-- name: DispatchShipment :one
UPDATE shipments
SET status        = 'DISPATCHED',
    dispatched_at = NOW(),
    updated_at    = NOW()
WHERE id = $1
  AND tenant_id = $2
  AND status IN ('PACKED','PICKING','PENDING')
  AND carrier_id IS NOT NULL
RETURNING id, public_id, tenant_id, shipment_number, sales_order_id, carrier_id, status, ship_from_site, ship_to_address, ship_to_city, ship_to_country, tracking_ref, planned_date, dispatched_at, delivered_at, notes, created_by, created_at, updated_at
`

type DispatchShipmentParams struct {
	ID       int64 `json:"id"`
	TenantID int64 `json:"tenant_id"`
}

func (q *Queries) DispatchShipment(ctx context.Context, arg DispatchShipmentParams) (Shipment, error) {
	row := q.db.QueryRow(ctx, dispatchShipment, arg.ID, arg.TenantID)
	var i Shipment
	err := row.Scan(
		&i.ID,
		&i.PublicID,
		&i.TenantID,
		&i.ShipmentNumber,
		&i.SalesOrderID,
		&i.CarrierID,
		&i.Status,
		&i.ShipFromSite,
		&i.ShipToAddress,
		&i.ShipToCity,
		&i.ShipToCountry,
		&i.TrackingRef,
		&i.PlannedDate,
		&i.DispatchedAt,
		&i.DeliveredAt,
		&i.Notes,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getRouteRunnerDashboard = `-- name: GetRouteRunnerDashboard :one
SELECT
    COUNT(*)                                                  AS total_shipments,
    COUNT(*) FILTER (WHERE status = 'PENDING')                AS pending,
    COUNT(*) FILTER (WHERE status IN ('PICKING','PACKED'))    AS in_progress,
    COUNT(*) FILTER (WHERE status = 'DISPATCHED')             AS dispatched,
    COUNT(*) FILTER (WHERE status = 'IN_TRANSIT')             AS in_transit,
    COUNT(*) FILTER (WHERE status = 'DELIVERED')              AS delivered,
    COUNT(*) FILTER (WHERE status = 'CANCELLED')              AS cancelled,
    COUNT(*) FILTER (WHERE status = 'DISPATCHED'
      AND planned_date < CURRENT_DATE)                        AS overdue
FROM shipments
WHERE tenant_id = $1
`

type GetRouteRunnerDashboardRow struct {
	TotalShipments int64 `json:"total_shipments"`
	Pending        int64 `json:"pending"`
	InProgress     int64 `json:"in_progress"`
	Dispatched     int64 `json:"dispatched"`
	InTransit      int64 `json:"in_transit"`
	Delivered      int64 `json:"delivered"`
	Cancelled      int64 `json:"cancelled"`
	Overdue        int64 `json:"overdue"`
}

func (q *Queries) GetRouteRunnerDashboard(ctx context.Context, tenantID int64) (GetRouteRunnerDashboardRow, error) {
	row := q.db.QueryRow(ctx, getRouteRunnerDashboard, tenantID)
	var i GetRouteRunnerDashboardRow
	err := row.Scan(
		&i.TotalShipments,
		&i.Pending,
		&i.InProgress,
		&i.Dispatched,
		&i.InTransit,
		&i.Delivered,
		&i.Cancelled,
		&i.Overdue,
	)
	return i, err
}

const getShipmentByPublicID = `-- name: GetShipmentByPublicID :one
SELECT
    s.id, s.public_id, s.tenant_id, s.shipment_number, s.sales_order_id, s.carrier_id, s.status, s.ship_from_site, s.ship_to_address, s.ship_to_city, s.ship_to_country, s.tracking_ref, s.planned_date, s.dispatched_at, s.delivered_at, s.notes, s.created_by, s.created_at, s.updated_at,
    so.so_number,
    c_cust.name  AS customer_name,
    carr.name    AS carrier_name,
    carr.mode    AS carrier_mode,
    carr.tracking_url
FROM shipments s
LEFT JOIN sales_orders  so     ON so.id    = s.sales_order_id
LEFT JOIN customers     c_cust ON c_cust.id = so.customer_id
LEFT JOIN carriers      carr   ON carr.id  = s.carrier_id
WHERE s.public_id = $1 AND s.tenant_id = $2
`

type GetShipmentByPublicIDParams struct {
	PublicID uuid.UUID `json:"public_id"`
	TenantID int64     `json:"tenant_id"`
}

type GetShipmentByPublicIDRow struct {
	ID             int64              `json:"id"`
	PublicID       uuid.UUID          `json:"public_id"`
	TenantID       int64              `json:"tenant_id"`
	ShipmentNumber string             `json:"shipment_number"`
	SalesOrderID   pgtype.Int8        `json:"sales_order_id"`
	CarrierID      pgtype.Int8        `json:"carrier_id"`
	Status         string             `json:"status"`
	ShipFromSite   pgtype.Int8        `json:"ship_from_site"`
	ShipToAddress  pgtype.Text        `json:"ship_to_address"`
	ShipToCity     pgtype.Text        `json:"ship_to_city"`
	ShipToCountry  pgtype.Text        `json:"ship_to_country"`
	TrackingRef    pgtype.Text        `json:"tracking_ref"`
	PlannedDate    pgtype.Date        `json:"planned_date"`
	DispatchedAt   pgtype.Timestamptz `json:"dispatched_at"`
	DeliveredAt    pgtype.Timestamptz `json:"delivered_at"`
	Notes          pgtype.Text        `json:"notes"`
	CreatedBy      pgtype.Int8        `json:"created_by"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	UpdatedAt      pgtype.Timestamptz `json:"updated_at"`
	SoNumber       pgtype.Text        `json:"so_number"`
	CustomerName   pgtype.Text        `json:"customer_name"`
	CarrierName    pgtype.Text        `json:"carrier_name"`
	CarrierMode    pgtype.Text        `json:"carrier_mode"`
	TrackingUrl    pgtype.Text        `json:"tracking_url"`
}

func (q *Queries) GetShipmentByPublicID(ctx context.Context, arg GetShipmentByPublicIDParams) (GetShipmentByPublicIDRow, error) {
	row := q.db.QueryRow(ctx, getShipmentByPublicID, arg.PublicID, arg.TenantID)
	var i GetShipmentByPublicIDRow
	err := row.Scan(
		&i.ID,
		&i.PublicID,
		&i.TenantID,
		&i.ShipmentNumber,
		&i.SalesOrderID,
		&i.CarrierID,
		&i.Status,
		&i.ShipFromSite,
		&i.ShipToAddress,
		&i.ShipToCity,
		&i.ShipToCountry,
		&i.TrackingRef,
		&i.PlannedDate,
		&i.DispatchedAt,
		&i.DeliveredAt,
		&i.Notes,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.SoNumber,
		&i.CustomerName,
		&i.CarrierName,
		&i.CarrierMode,
		&i.TrackingUrl,
	)
	return i, err
}

const getShipmentLines = `-- name: GetShipmentLines :many
SELECT
    sl.id, sl.public_id, sl.shipment_id, sl.sales_order_line_id, sl.line_number, sl.description, sl.quantity, sl.unit_of_measure, sl.material_id, sl.created_at,
    m.code AS material_code,
    m.name AS material_name
FROM shipment_lines sl
LEFT JOIN products m ON m.id = sl.material_id
WHERE sl.shipment_id = $1
ORDER BY sl.line_number
`

type GetShipmentLinesRow struct {
	ID               int64              `json:"id"`
	PublicID         uuid.UUID          `json:"public_id"`
	ShipmentID       int64              `json:"shipment_id"`
	SalesOrderLineID pgtype.Int8        `json:"sales_order_line_id"`
	LineNumber       int32              `json:"line_number"`
	Description      string             `json:"description"`
	Quantity         pgtype.Numeric     `json:"quantity"`
	UnitOfMeasure    string             `json:"unit_of_measure"`
	MaterialID       pgtype.Int8        `json:"material_id"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
	MaterialCode     pgtype.Text        `json:"material_code"`
	MaterialName     pgtype.Text        `json:"material_name"`
}

func (q *Queries) GetShipmentLines(ctx context.Context, shipmentID int64) ([]GetShipmentLinesRow, error) {
	rows, err := q.db.Query(ctx, getShipmentLines, shipmentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetShipmentLinesRow{}
	for rows.Next() {
		var i GetShipmentLinesRow
		if err := rows.Scan(
			&i.ID,
			&i.PublicID,
			&i.ShipmentID,
			&i.SalesOrderLineID,
			&i.LineNumber,
			&i.Description,
			&i.Quantity,
			&i.UnitOfMeasure,
			&i.MaterialID,
			&i.CreatedAt,
			&i.MaterialCode,
			&i.MaterialName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCarriers = `-- name: ListCarriers :many
SELECT id, public_id, tenant_id, code, name, mode, tracking_url, contact_name, contact_email, contact_phone, is_active, created_at FROM carriers
WHERE tenant_id = $1 AND is_active = true
ORDER BY name ASC
`

func (q *Queries) ListCarriers(ctx context.Context, tenantID int64) ([]Carrier, error) {
	rows, err := q.db.Query(ctx, listCarriers, tenantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Carrier{}
	for rows.Next() {
		var i Carrier
		if err := rows.Scan(
			&i.ID,
			&i.PublicID,
			&i.TenantID,
			&i.Code,
			&i.Name,
			&i.Mode,
			&i.TrackingUrl,
			&i.ContactName,
			&i.ContactEmail,
			&i.ContactPhone,
			&i.IsActive,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listShipments = `-- name: ListShipments :many
SELECT
    s.id, s.public_id, s.tenant_id, s.shipment_number, s.sales_order_id, s.carrier_id, s.status, s.ship_from_site, s.ship_to_address, s.ship_to_city, s.ship_to_country, s.tracking_ref, s.planned_date, s.dispatched_at, s.delivered_at, s.notes, s.created_by, s.created_at, s.updated_at,
    so.so_number,
    c_cust.name  AS customer_name,
    carr.name    AS carrier_name,
    carr.mode    AS carrier_mode,
    (SELECT COUNT(*) FROM shipment_lines sl
     WHERE sl.shipment_id = s.id) AS line_count
FROM shipments s
LEFT JOIN sales_orders  so     ON so.id    = s.sales_order_id
LEFT JOIN customers     c_cust ON c_cust.id = so.customer_id
LEFT JOIN carriers      carr   ON carr.id  = s.carrier_id
WHERE s.tenant_id = $1
ORDER BY s.created_at DESC
LIMIT $2 OFFSET $3
`

type ListShipmentsParams struct {
	TenantID int64 `json:"tenant_id"`
	Limit    int32 `json:"limit"`
	Offset   int32 `json:"offset"`
}

type ListShipmentsRow struct {
	ID             int64              `json:"id"`
	PublicID       uuid.UUID          `json:"public_id"`
	TenantID       int64              `json:"tenant_id"`
	ShipmentNumber string             `json:"shipment_number"`
	SalesOrderID   pgtype.Int8        `json:"sales_order_id"`
	CarrierID      pgtype.Int8        `json:"carrier_id"`
	Status         string             `json:"status"`
	ShipFromSite   pgtype.Int8        `json:"ship_from_site"`
	ShipToAddress  pgtype.Text        `json:"ship_to_address"`
	ShipToCity     pgtype.Text        `json:"ship_to_city"`
	ShipToCountry  pgtype.Text        `json:"ship_to_country"`
	TrackingRef    pgtype.Text        `json:"tracking_ref"`
	PlannedDate    pgtype.Date        `json:"planned_date"`
	DispatchedAt   pgtype.Timestamptz `json:"dispatched_at"`
	DeliveredAt    pgtype.Timestamptz `json:"delivered_at"`
	Notes          pgtype.Text        `json:"notes"`
	CreatedBy      pgtype.Int8        `json:"created_by"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	UpdatedAt      pgtype.Timestamptz `json:"updated_at"`
	SoNumber       pgtype.Text        `json:"so_number"`
	CustomerName   pgtype.Text        `json:"customer_name"`
	CarrierName    pgtype.Text        `json:"carrier_name"`
	CarrierMode    pgtype.Text        `json:"carrier_mode"`
	LineCount      int64              `json:"line_count"`
}

func (q *Queries) ListShipments(ctx context.Context, arg ListShipmentsParams) ([]ListShipmentsRow, error) {
	rows, err := q.db.Query(ctx, listShipments, arg.TenantID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListShipmentsRow{}
	for rows.Next() {
		var i ListShipmentsRow
		if err := rows.Scan(
			&i.ID,
			&i.PublicID,
			&i.TenantID,
			&i.ShipmentNumber,
			&i.SalesOrderID,
			&i.CarrierID,
			&i.Status,
			&i.ShipFromSite,
			&i.ShipToAddress,
			&i.ShipToCity,
			&i.ShipToCountry,
			&i.TrackingRef,
			&i.PlannedDate,
			&i.DispatchedAt,
			&i.DeliveredAt,
			&i.Notes,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.SoNumber,
			&i.CustomerName,
			&i.CarrierName,
			&i.CarrierMode,
			&i.LineCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markDelivered = `-- name: MarkDelivered :one
UPDATE shipments
SET status       = 'DELIVERED',
    delivered_at = NOW(),
    updated_at   = NOW()
WHERE id = $1 AND tenant_id = $2
  AND status = 'DISPATCHED'
RETURNING id, public_id, tenant_id, shipment_number, sales_order_id, carrier_id, status, ship_from_site, ship_to_address, ship_to_city, ship_to_country, tracking_ref, planned_date, dispatched_at, delivered_at, notes, created_by, created_at, updated_at
`

type MarkDeliveredParams struct {
	ID       int64 `json:"id"`
	TenantID int64 `json:"tenant_id"`
}

func (q *Queries) MarkDelivered(ctx context.Context, arg MarkDeliveredParams) (Shipment, error) {
	row := q.db.QueryRow(ctx, markDelivered, arg.ID, arg.TenantID)
	var i Shipment
	err := row.Scan(
		&i.ID,
		&i.PublicID,
		&i.TenantID,
		&i.ShipmentNumber,
		&i.SalesOrderID,
		&i.CarrierID,
		&i.Status,
		&i.ShipFromSite,
		&i.ShipToAddress,
		&i.ShipToCity,
		&i.ShipToCountry,
		&i.TrackingRef,
		&i.PlannedDate,
		&i.DispatchedAt,
		&i.DeliveredAt,
		&i.Notes,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateShipmentStatus = `-- name: UpdateShipmentStatus :one
UPDATE shipments
SET status     = $2,
    updated_at = NOW()
WHERE id = $1 AND tenant_id = $3
RETURNING id, public_id, tenant_id, shipment_number, sales_order_id, carrier_id, status, ship_from_site, ship_to_address, ship_to_city, ship_to_country, tracking_ref, planned_date, dispatched_at, delivered_at, notes, created_by, created_at, updated_at
`

type UpdateShipmentStatusParams struct {
	ID       int64  `json:"id"`
	Status   string `json:"status"`
	TenantID int64  `json:"tenant_id"`
}

func (q *Queries) UpdateShipmentStatus(ctx context.Context, arg UpdateShipmentStatusParams) (Shipment, error) {
	row := q.db.QueryRow(ctx, updateShipmentStatus, arg.ID, arg.Status, arg.TenantID)
	var i Shipment
	err := row.Scan(
		&i.ID,
		&i.PublicID,
		&i.TenantID,
		&i.ShipmentNumber,
		&i.SalesOrderID,
		&i.CarrierID,
		&i.Status,
		&i.ShipFromSite,
		&i.ShipToAddress,
		&i.ShipToCity,
		&i.ShipToCountry,
		&i.TrackingRef,
		&i.PlannedDate,
		&i.DispatchedAt,
		&i.DeliveredAt,
		&i.Notes,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
