// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.20.0
// source: vendor_scorecard.sql

package dbgen

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const getScorecardEvents = `-- name: GetScorecardEvents :many
SELECT id, public_id, tenant_id, supplier_id, event_type, reference_type, reference_id, reference_code, score_impact, notes, recorded_by, recorded_at FROM vendor_scorecard_events
WHERE tenant_id = $1
  AND supplier_id = $2
  AND recorded_at >= $3
ORDER BY recorded_at DESC
`

type GetScorecardEventsParams struct {
	TenantID   int64              `json:"tenant_id"`
	SupplierID int64              `json:"supplier_id"`
	RecordedAt pgtype.Timestamptz `json:"recorded_at"`
}

func (q *Queries) GetScorecardEvents(ctx context.Context, arg GetScorecardEventsParams) ([]VendorScorecardEvent, error) {
	rows, err := q.db.Query(ctx, getScorecardEvents, arg.TenantID, arg.SupplierID, arg.RecordedAt)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []VendorScorecardEvent{}
	for rows.Next() {
		var i VendorScorecardEvent
		if err := rows.Scan(
			&i.ID,
			&i.PublicID,
			&i.TenantID,
			&i.SupplierID,
			&i.EventType,
			&i.ReferenceType,
			&i.ReferenceID,
			&i.ReferenceCode,
			&i.ScoreImpact,
			&i.Notes,
			&i.RecordedBy,
			&i.RecordedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getScorecardSummary = `-- name: GetScorecardSummary :one
SELECT
    COUNT(*)                                              AS total_suppliers,
    COUNT(*) FILTER (WHERE auto_score >= 90)             AS excellent,
    COUNT(*) FILTER (WHERE auto_score >= 70
                       AND auto_score < 90)              AS good,
    COUNT(*) FILTER (WHERE auto_score >= 50
                       AND auto_score < 70)              AS needs_improvement,
    COUNT(*) FILTER (WHERE auto_score < 50)              AS critical,
    COALESCE(ROUND(AVG(auto_score), 1), 0)::numeric      AS avg_score
FROM vendor_scorecards
WHERE tenant_id = $1
`

type GetScorecardSummaryRow struct {
	TotalSuppliers   int64          `json:"total_suppliers"`
	Excellent        int64          `json:"excellent"`
	Good             int64          `json:"good"`
	NeedsImprovement int64          `json:"needs_improvement"`
	Critical         int64          `json:"critical"`
	AvgScore         pgtype.Numeric `json:"avg_score"`
}

func (q *Queries) GetScorecardSummary(ctx context.Context, tenantID pgtype.Int8) (GetScorecardSummaryRow, error) {
	row := q.db.QueryRow(ctx, getScorecardSummary, tenantID)
	var i GetScorecardSummaryRow
	err := row.Scan(
		&i.TotalSuppliers,
		&i.Excellent,
		&i.Good,
		&i.NeedsImprovement,
		&i.Critical,
		&i.AvgScore,
	)
	return i, err
}

const getVendorScorecardBySupplier = `-- name: GetVendorScorecardBySupplier :one
SELECT vs.id, vs.supplier_id, vs.period_start, vs.period_end, vs.price_score, vs.delivery_score, vs.quality_score, vs.response_score, vs.overall_score, vs.price_notes, vs.delivery_notes, vs.quality_notes, vs.response_notes, vs.evaluated_by, vs.auto_calculated, vs.created_at, vs.auto_score, vs.compliance_score, vs.total_orders, vs.on_time_count, vs.late_count, vs.quality_pass, vs.quality_fail, vs.last_calculated, vs.calculated_by, vs.tenant_id, vs.updated_at, s.name AS supplier_name, s.public_id AS supplier_code
FROM vendor_scorecards vs
JOIN suppliers s ON s.id = vs.supplier_id
WHERE vs.tenant_id = $1 AND vs.supplier_id = $2
`

type GetVendorScorecardBySupplierParams struct {
	TenantID   pgtype.Int8 `json:"tenant_id"`
	SupplierID int64       `json:"supplier_id"`
}

type GetVendorScorecardBySupplierRow struct {
	ID              int64              `json:"id"`
	SupplierID      int64              `json:"supplier_id"`
	PeriodStart     pgtype.Date        `json:"period_start"`
	PeriodEnd       pgtype.Date        `json:"period_end"`
	PriceScore      pgtype.Numeric     `json:"price_score"`
	DeliveryScore   pgtype.Numeric     `json:"delivery_score"`
	QualityScore    pgtype.Numeric     `json:"quality_score"`
	ResponseScore   pgtype.Numeric     `json:"response_score"`
	OverallScore    pgtype.Numeric     `json:"overall_score"`
	PriceNotes      pgtype.Text        `json:"price_notes"`
	DeliveryNotes   pgtype.Text        `json:"delivery_notes"`
	QualityNotes    pgtype.Text        `json:"quality_notes"`
	ResponseNotes   pgtype.Text        `json:"response_notes"`
	EvaluatedBy     pgtype.Text        `json:"evaluated_by"`
	AutoCalculated  pgtype.Bool        `json:"auto_calculated"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	AutoScore       pgtype.Numeric     `json:"auto_score"`
	ComplianceScore pgtype.Numeric     `json:"compliance_score"`
	TotalOrders     pgtype.Int4        `json:"total_orders"`
	OnTimeCount     pgtype.Int4        `json:"on_time_count"`
	LateCount       pgtype.Int4        `json:"late_count"`
	QualityPass     pgtype.Int4        `json:"quality_pass"`
	QualityFail     pgtype.Int4        `json:"quality_fail"`
	LastCalculated  pgtype.Timestamptz `json:"last_calculated"`
	CalculatedBy    pgtype.Text        `json:"calculated_by"`
	TenantID        pgtype.Int8        `json:"tenant_id"`
	UpdatedAt       pgtype.Timestamptz `json:"updated_at"`
	SupplierName    string             `json:"supplier_name"`
	SupplierCode    pgtype.UUID        `json:"supplier_code"`
}

func (q *Queries) GetVendorScorecardBySupplier(ctx context.Context, arg GetVendorScorecardBySupplierParams) (GetVendorScorecardBySupplierRow, error) {
	row := q.db.QueryRow(ctx, getVendorScorecardBySupplier, arg.TenantID, arg.SupplierID)
	var i GetVendorScorecardBySupplierRow
	err := row.Scan(
		&i.ID,
		&i.SupplierID,
		&i.PeriodStart,
		&i.PeriodEnd,
		&i.PriceScore,
		&i.DeliveryScore,
		&i.QualityScore,
		&i.ResponseScore,
		&i.OverallScore,
		&i.PriceNotes,
		&i.DeliveryNotes,
		&i.QualityNotes,
		&i.ResponseNotes,
		&i.EvaluatedBy,
		&i.AutoCalculated,
		&i.CreatedAt,
		&i.AutoScore,
		&i.ComplianceScore,
		&i.TotalOrders,
		&i.OnTimeCount,
		&i.LateCount,
		&i.QualityPass,
		&i.QualityFail,
		&i.LastCalculated,
		&i.CalculatedBy,
		&i.TenantID,
		&i.UpdatedAt,
		&i.SupplierName,
		&i.SupplierCode,
	)
	return i, err
}

const listScorecardEvents = `-- name: ListScorecardEvents :many

SELECT vse.id, vse.public_id, vse.tenant_id, vse.supplier_id, vse.event_type, vse.reference_type, vse.reference_id, vse.reference_code, vse.score_impact, vse.notes, vse.recorded_by, vse.recorded_at, u.username AS recorded_by_name
FROM vendor_scorecard_events vse
LEFT JOIN users u ON u.id = vse.recorded_by
WHERE vse.tenant_id = $1 AND vse.supplier_id = $2
ORDER BY vse.recorded_at DESC
LIMIT $3 OFFSET $4
`

type ListScorecardEventsParams struct {
	TenantID   int64 `json:"tenant_id"`
	SupplierID int64 `json:"supplier_id"`
	Limit      int32 `json:"limit"`
	Offset     int32 `json:"offset"`
}

type ListScorecardEventsRow struct {
	ID             int64              `json:"id"`
	PublicID       uuid.UUID          `json:"public_id"`
	TenantID       int64              `json:"tenant_id"`
	SupplierID     int64              `json:"supplier_id"`
	EventType      string             `json:"event_type"`
	ReferenceType  pgtype.Text        `json:"reference_type"`
	ReferenceID    pgtype.Int8        `json:"reference_id"`
	ReferenceCode  pgtype.Text        `json:"reference_code"`
	ScoreImpact    pgtype.Numeric     `json:"score_impact"`
	Notes          pgtype.Text        `json:"notes"`
	RecordedBy     pgtype.Int8        `json:"recorded_by"`
	RecordedAt     pgtype.Timestamptz `json:"recorded_at"`
	RecordedByName pgtype.Text        `json:"recorded_by_name"`
}

// worst performers first
func (q *Queries) ListScorecardEvents(ctx context.Context, arg ListScorecardEventsParams) ([]ListScorecardEventsRow, error) {
	rows, err := q.db.Query(ctx, listScorecardEvents,
		arg.TenantID,
		arg.SupplierID,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListScorecardEventsRow{}
	for rows.Next() {
		var i ListScorecardEventsRow
		if err := rows.Scan(
			&i.ID,
			&i.PublicID,
			&i.TenantID,
			&i.SupplierID,
			&i.EventType,
			&i.ReferenceType,
			&i.ReferenceID,
			&i.ReferenceCode,
			&i.ScoreImpact,
			&i.Notes,
			&i.RecordedBy,
			&i.RecordedAt,
			&i.RecordedByName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listVendorScorecards = `-- name: ListVendorScorecards :many
SELECT
    vs.id, vs.supplier_id, vs.period_start, vs.period_end, vs.price_score, vs.delivery_score, vs.quality_score, vs.response_score, vs.overall_score, vs.price_notes, vs.delivery_notes, vs.quality_notes, vs.response_notes, vs.evaluated_by, vs.auto_calculated, vs.created_at, vs.auto_score, vs.compliance_score, vs.total_orders, vs.on_time_count, vs.late_count, vs.quality_pass, vs.quality_fail, vs.last_calculated, vs.calculated_by, vs.tenant_id, vs.updated_at,
    s.name  AS supplier_name,
    s.public_id  AS supplier_code,
    s.email AS supplier_email,
    (SELECT COUNT(*) FROM vendor_scorecard_events e
     WHERE e.supplier_id = vs.supplier_id
       AND e.tenant_id = vs.tenant_id
       AND e.recorded_at >= NOW() - INTERVAL '30 days'
    ) AS events_last_30d
FROM vendor_scorecards vs
JOIN suppliers s ON s.id = vs.supplier_id
WHERE vs.tenant_id = $1
ORDER BY vs.auto_score ASC
`

type ListVendorScorecardsRow struct {
	ID              int64              `json:"id"`
	SupplierID      int64              `json:"supplier_id"`
	PeriodStart     pgtype.Date        `json:"period_start"`
	PeriodEnd       pgtype.Date        `json:"period_end"`
	PriceScore      pgtype.Numeric     `json:"price_score"`
	DeliveryScore   pgtype.Numeric     `json:"delivery_score"`
	QualityScore    pgtype.Numeric     `json:"quality_score"`
	ResponseScore   pgtype.Numeric     `json:"response_score"`
	OverallScore    pgtype.Numeric     `json:"overall_score"`
	PriceNotes      pgtype.Text        `json:"price_notes"`
	DeliveryNotes   pgtype.Text        `json:"delivery_notes"`
	QualityNotes    pgtype.Text        `json:"quality_notes"`
	ResponseNotes   pgtype.Text        `json:"response_notes"`
	EvaluatedBy     pgtype.Text        `json:"evaluated_by"`
	AutoCalculated  pgtype.Bool        `json:"auto_calculated"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	AutoScore       pgtype.Numeric     `json:"auto_score"`
	ComplianceScore pgtype.Numeric     `json:"compliance_score"`
	TotalOrders     pgtype.Int4        `json:"total_orders"`
	OnTimeCount     pgtype.Int4        `json:"on_time_count"`
	LateCount       pgtype.Int4        `json:"late_count"`
	QualityPass     pgtype.Int4        `json:"quality_pass"`
	QualityFail     pgtype.Int4        `json:"quality_fail"`
	LastCalculated  pgtype.Timestamptz `json:"last_calculated"`
	CalculatedBy    pgtype.Text        `json:"calculated_by"`
	TenantID        pgtype.Int8        `json:"tenant_id"`
	UpdatedAt       pgtype.Timestamptz `json:"updated_at"`
	SupplierName    string             `json:"supplier_name"`
	SupplierCode    pgtype.UUID        `json:"supplier_code"`
	SupplierEmail   pgtype.Text        `json:"supplier_email"`
	EventsLast30d   int64              `json:"events_last_30d"`
}

func (q *Queries) ListVendorScorecards(ctx context.Context, tenantID pgtype.Int8) ([]ListVendorScorecardsRow, error) {
	rows, err := q.db.Query(ctx, listVendorScorecards, tenantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListVendorScorecardsRow{}
	for rows.Next() {
		var i ListVendorScorecardsRow
		if err := rows.Scan(
			&i.ID,
			&i.SupplierID,
			&i.PeriodStart,
			&i.PeriodEnd,
			&i.PriceScore,
			&i.DeliveryScore,
			&i.QualityScore,
			&i.ResponseScore,
			&i.OverallScore,
			&i.PriceNotes,
			&i.DeliveryNotes,
			&i.QualityNotes,
			&i.ResponseNotes,
			&i.EvaluatedBy,
			&i.AutoCalculated,
			&i.CreatedAt,
			&i.AutoScore,
			&i.ComplianceScore,
			&i.TotalOrders,
			&i.OnTimeCount,
			&i.LateCount,
			&i.QualityPass,
			&i.QualityFail,
			&i.LastCalculated,
			&i.CalculatedBy,
			&i.TenantID,
			&i.UpdatedAt,
			&i.SupplierName,
			&i.SupplierCode,
			&i.SupplierEmail,
			&i.EventsLast30d,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const recordScorecardEvent = `-- name: RecordScorecardEvent :one
INSERT INTO vendor_scorecard_events (
    tenant_id, supplier_id, event_type,
    reference_type, reference_id, reference_code,
    score_impact, notes, recorded_by
) VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)
RETURNING id, public_id, tenant_id, supplier_id, event_type, reference_type, reference_id, reference_code, score_impact, notes, recorded_by, recorded_at
`

type RecordScorecardEventParams struct {
	TenantID      int64          `json:"tenant_id"`
	SupplierID    int64          `json:"supplier_id"`
	EventType     string         `json:"event_type"`
	ReferenceType pgtype.Text    `json:"reference_type"`
	ReferenceID   pgtype.Int8    `json:"reference_id"`
	ReferenceCode pgtype.Text    `json:"reference_code"`
	ScoreImpact   pgtype.Numeric `json:"score_impact"`
	Notes         pgtype.Text    `json:"notes"`
	RecordedBy    pgtype.Int8    `json:"recorded_by"`
}

func (q *Queries) RecordScorecardEvent(ctx context.Context, arg RecordScorecardEventParams) (VendorScorecardEvent, error) {
	row := q.db.QueryRow(ctx, recordScorecardEvent,
		arg.TenantID,
		arg.SupplierID,
		arg.EventType,
		arg.ReferenceType,
		arg.ReferenceID,
		arg.ReferenceCode,
		arg.ScoreImpact,
		arg.Notes,
		arg.RecordedBy,
	)
	var i VendorScorecardEvent
	err := row.Scan(
		&i.ID,
		&i.PublicID,
		&i.TenantID,
		&i.SupplierID,
		&i.EventType,
		&i.ReferenceType,
		&i.ReferenceID,
		&i.ReferenceCode,
		&i.ScoreImpact,
		&i.Notes,
		&i.RecordedBy,
		&i.RecordedAt,
	)
	return i, err
}

const updateVendorScorecardCalculated = `-- name: UpdateVendorScorecardCalculated :exec
UPDATE vendor_scorecards
SET auto_score        = $3,
    delivery_score    = $4,
    quality_score     = $5,
    compliance_score  = $6,
    total_orders      = $7,
    on_time_count     = $8,
    late_count        = $9,
    quality_pass      = $10,
    quality_fail      = $11,
    last_calculated   = $12,
    calculated_by     = 'SYSTEM',
    updated_at        = NOW()
WHERE tenant_id = $1 AND supplier_id = $2
`

type UpdateVendorScorecardCalculatedParams struct {
	TenantID        pgtype.Int8        `json:"tenant_id"`
	SupplierID      int64              `json:"supplier_id"`
	AutoScore       pgtype.Numeric     `json:"auto_score"`
	DeliveryScore   pgtype.Numeric     `json:"delivery_score"`
	QualityScore    pgtype.Numeric     `json:"quality_score"`
	ComplianceScore pgtype.Numeric     `json:"compliance_score"`
	TotalOrders     pgtype.Int4        `json:"total_orders"`
	OnTimeCount     pgtype.Int4        `json:"on_time_count"`
	LateCount       pgtype.Int4        `json:"late_count"`
	QualityPass     pgtype.Int4        `json:"quality_pass"`
	QualityFail     pgtype.Int4        `json:"quality_fail"`
	LastCalculated  pgtype.Timestamptz `json:"last_calculated"`
}

func (q *Queries) UpdateVendorScorecardCalculated(ctx context.Context, arg UpdateVendorScorecardCalculatedParams) error {
	_, err := q.db.Exec(ctx, updateVendorScorecardCalculated,
		arg.TenantID,
		arg.SupplierID,
		arg.AutoScore,
		arg.DeliveryScore,
		arg.QualityScore,
		arg.ComplianceScore,
		arg.TotalOrders,
		arg.OnTimeCount,
		arg.LateCount,
		arg.QualityPass,
		arg.QualityFail,
		arg.LastCalculated,
	)
	return err
}
